### ISSUE TITLE
How to detect HitTest on the infinite extension of a detected plane ? 

### ISSUE THREAD

**Issue by RegisAG** [google-ar/arcore-android-sdk#241] opened 2018-03-14 14:34 UTC
I want to detect the hitTests on the infinite extension of a defined detected plane.

I see that there is isHitInPolygon() but too restrictive. There is also isPoseInExtents but detects the hits only the overall rectangular surface.

How to detect a HitTest on the infinite extension of a detected plane ? A workaround would be to modify the size of the plane but does not seem possible. 

Thanks for your help.

**Comment by inio** [comment] 2018-03-14 18:54
To do this you'll need to do the math on your own:

1. Project the point to a ray by inverting the (projection*camera) matrix and multiplying through a couple points

2. Intersect that ray with the infinite plane

**Comment by RegisAG** [comment] 2018-03-14 20:02
Thanks for your answer but may you give more details? 

Questions:
What do you mean by "project the point to a ray"? What point? 
What do you mean by "couple points" ?
"the infinite plane": how do you create it?

Thanks for all the details you may give. 

Would be great to include this feature in the SDK.

**Comment by inio** [comment] 2018-03-14 20:17
These are all fairly standard 3D graphics concepts not specific to ARCore.  Maybe try asking on the 3D graphics StackOverflow or just using Unity which provides all of these things?

**Comment by inio** [comment] 2018-03-14 20:17
Duplicate of #52

**Closed by inio** 2018-03-14 20:17 UTC
Labels: question
