### ISSUE TITLE
Nokia 6.1 (2018) Support?

### ISSUE THREAD

**Issue by jieseattle** [google-ar/arcore-android-sdk#392] opened 2018-05-20 08:27 UTC
Although we have Nokia 6.1 (2018) in the supported device list, even after the latest 8.1.0 May update there's no ARCore support. Something wrong with your list? The exact model is TA-1054.

**Comment by inio** [comment] 2018-05-22 14:34
I've asked for clarification.  It sounds like it should be supported.

If possible could you please provide the build fingerprint of the device?  It can be read with `adb shell getprop ro.build.fingerprint`.

**Comment by inio** [comment] 2018-05-22 21:00
As far as we can tell that device is a "Nokia 6", not a "Nokia 6.1" and is not supported.

**Comment by inio** [comment] 2018-05-22 21:00
Duplicate of #89

**Closed by inio** 2018-05-22 21:00 UTC
Labels: device support, feature request

**Comment by jieseattle** [comment] 2018-05-23 00:32
Nokia 6.1 aka new Nokia 6 in 2018. You need to check your fact. BTW I installed arcore 1.2 apk and now it is working well.
