### ISSUE TITLE
ARCore crash on Oreo Update form Nougat 7.0

### ISSUE THREAD

**Issue by Attaullah123** [google-ar/arcore-android-sdk#358] opened 2018-05-07 06:57 UTC
Hi,
I have S7 edge device, ARCore run perfectly on 7.0 but after updating my device on Oreo application crash on it , show this message (Your device is not supporting Augmented reality) please give me a solution
Thanks

**Comment by inio** [comment] 2018-05-07 21:04
Does the error message actually say "Your device is not supporting Augmented reality"?  That's not an error message I'm familiar with.

Please include a logcat capture around the generation of the error.  That will help us figure out why you're getting this error.

Also, double check your device is on our [supported device list](https://developers.google.com/ar/discover/#supported_devices).  Note that Samsung devices with model numbers ending in 0 and 8 are not supported.

**Comment by Attaullah123** [comment] 2018-05-08 06:15
Thanks for reply, I already mention Arcore is perfectly running on 7.0, when it's update on Oreo version than going to crash and my device model number is SM-G935F which is supported for Arcore

**Comment by Attaullah123** [comment] 2018-05-08 07:59
This is my logcat error 
![logcat error](https://user-images.githubusercontent.com/20942660/39745037-05c50692-525b-11e8-8481-691f0de8fe12.png)

**Comment by inio** [comment] 2018-05-08 19:10
@Attaullah123 the interesting bit is just off the top of your screen there.

I do however see a message about com.google.ar.core dying.  Does this device have a very old Google Play Services?  The Google Play Store should also-update Google Play Services regularly, but if not please update it manually.

Also, ARCore is not supported on devices that do not ship with the Google Play Store or do not have regular access to it.

**Comment by inio** [comment] 2018-05-13 16:38
I see in the screenshot you have a S7 Edge.

**Comment by inio** [comment] 2018-05-13 16:39
Duplicate of #350

**Closed by inio** 2018-05-13 16:39 UTC
Labels: question
