### ISSUE TITLE
[Question] Setting texture name

### ISSUE THREAD

**Issue by iBicha** [google-ar/arcore-android-sdk#222] opened 2018-03-06 17:23 UTC
Would setting the rendering texture to 0 using `ArSession_setCameraTextureName` when background rendering is not needed, be an optimization?

**Comment by inio** [comment] 2018-03-06 18:19
If that works it wouldn't save much.  The hardware scaler is still going to be writing the texture image to DRAM.

**Comment by inio** [comment] 2018-03-06 18:20
Duplicate of #31

**Closed by inio** 2018-03-06 18:20 UTC
