### ISSUE TITLE
XIAOMI REDMI Note 8 not supported.

### ISSUE THREAD

**Issue by adelfi43** [google-ar/arcore-android-sdk#971] opened 2019-12-23 14:58 UTC
I would like to ask the developers to give support on the XIAOMI REDMI Note 8, please.
Kind regards and HAPPY HOLYDAYS!

**Comment by kenthoes** [comment] 2019-12-30 20:17
This is in accordance with my wishes because Redmi Note 7 can, I agree with you. Hopefully there is good news so that Redmi Note 8 can use Arcore.

**Comment by Shaunimsorry** [comment] 2020-01-02 06:04
+1 on this as well going to change phone cuz of this.

**Comment by chateaufiesta** [comment] 2020-01-02 14:17
> This is in accordance with my wishes because Redmi Note 7 can, I agree with you. Hopefully there is good news so that Redmi Note 8 can use Arcore.

Same.

**Comment by zyzzyvo** [comment] 2020-01-06 08:09
Ill support this one. I bought Redmi note 8 thinking it can use ARCore but was disappointed when i can't find on playstore

**Comment by HasinduLanka** [comment] 2020-01-07 00:28
come on... It won't be hard to get things working with redmi note 8

**Comment by TetsuDoragon** [comment] 2020-01-31 21:45
Pls google

**Comment by TNFB** [comment] 2020-02-01 12:46
Yea i have hope

**Comment by AlaaZorkane** [comment] 2020-02-04 03:55
Any updates on this?? Xiaomi 7 already supports ARCore, can't see why new gen Xiaomi is lacking the support.

**Comment by CleytonSarutobi** [comment] 2020-02-12 14:17
Any news for Redmi Note 8/Pro?

**Comment by Allgon** [comment] 2020-02-14 18:47
pls we need arcore for redmi note 8 and pro

**Comment by PiporGames** [comment] 2020-02-25 18:48
I think we should open another thread for xiaomi redmi note 8 pro as this one uses other cameras that doesn't appear in Note 8

**Comment by PiporGames** [comment] 2020-02-25 18:50
By the way, how are arcore updates done? Is there a way to know what new devices are added?.

**Comment by Allgon** [comment] 2020-02-25 18:55
> By the way, how are arcore updates done? Is there a way to know what new devices are added?.

ı personally look for the supported devices list for note 8 pro

**Comment by Allgon** [comment] 2020-02-25 18:57
> I think we should open another thread for xiaomi redmi note 8 pro as this one uses other cameras that doesn't appear in Note 8

it doesnt matter to them. if note 8 going to support it pro will come with it too it is a neccesity

**Comment by PiporGames** [comment] 2020-02-25 21:27
> > By the way, how are arcore updates done? Is there a way to know what new devices are added?.
> 
> ı personally look for the supported devices list for note 8 pro

Me too

**Comment by dexter-v** [comment] 2020-03-04 05:41
+1 
The issue is still open for this device. Hopefully it will be supported soon.

**Comment by PiporGames** [comment] 2020-03-04 06:27
Is this github being ran by the actual Google Team or is it just a community extension?

**Comment by Allgon** [comment] 2020-03-04 13:42
> Is this github being ran by the actual Google Team or is it just a community extension?

pretty sure its offical

**Comment by Talaren** [comment] 2020-03-04 17:46
+1
hoefully it will be supported soon.
Please work on this ticket, please.

**Comment by PiporGames** [comment] 2020-03-04 20:44
Do you think Android 10 update will mess something?

**Comment by PiporGames** [comment] 2020-03-04 20:45
by the way, my Note 8 Pro is still in Android 9, and it's suposed to update the last weekend... I'm PGGEUMX

**Comment by Shaunimsorry** [comment] 2020-03-06 06:49
i think its a hardware issue not a software one ? could be the device is incapable
tried some basic tests in unity and it was an instant crash

**Comment by dexter-v** [comment] 2020-03-06 07:07
> i think its a hardware issue not a software one ? could be the device is incapable
> tried some basic tests in unity and it was an instant crash

How do you get from a crash in Unity that it must be hardware not software. If someone has a RN8 with root they can try the Magisk module to enable AR and see whether it shows any signs of working.

**Comment by PiporGames** [comment] 2020-03-08 21:08
Still no updates?

**Comment by PiporGames** [comment] 2020-03-08 21:14
By the way, i have been reading other posts. What does #89 means? Why they close every post with #89?

**Comment by DraksoN94** [comment] 2020-03-12 02:33
I tested the Magisk module that enable AR, but under the fingerprint of a pixel 2, so I imagine it only uses one camera to do the math, so performance is not the best, but it is functional.

**Comment by DraksoN94** [comment] 2020-03-12 02:36
Please google team gives native support to RN8 is an excellent smartphone and very capable to perform the necessary tasks for AR.

**Comment by dexter-v** [comment] 2020-03-12 04:30
@PiporGames #83 is sort of like general "support this device" thread.
@DraksoN94 great to hear it is working. Thank you for trying it out. Now all we have to do is pray that RN8 will be supported soon. There are more than 5 million devices out there.

**Comment by PiporGames** [comment] 2020-03-16 08:33
Guys, RN8 PRO UPDATE IS HERE! THANKS TO ALL FOR THE UPDATE!!!. The use the update, I used APKUpdater, i'm not sure if google play is enabled, must try later. I'm very excited!

**Comment by PiporGames** [comment] 2020-03-16 08:33
You can now close this thread.

**Comment by PiporGames** [comment] 2020-03-16 08:37
Although the update 1.16 is here, it doesn't figure in Google's Device List and Google Play don't recognize the devices as Arcore. However, at least, Minecraft Earth is operating now.

**Comment by PiporGames** [comment] 2020-03-16 08:43
Guess we need to wait until it becomes "public".

**Comment by dexter-v** [comment] 2020-03-16 09:54
The APK from apkmirror installs but all apps crash. 
Not working on RN8(non Pro) 11.0.7 Global MI firmware.

**Comment by PiporGames** [comment] 2020-03-16 10:02
Are you using 1.16 update? Uninstall arcore and Try using ApkUpdater.

**Comment by dexter-v** [comment] 2020-03-16 10:04
Yes, it's the 1.16 update. I downloaded the Measure app from google to try but it crashes with internal error.

**Comment by PiporGames** [comment] 2020-03-16 10:09
I have an RN8 Pro. Some applications don't work because it doesn't figure in the google devices list. Others work because it skips this list. My version is 1.16.200302043

**Comment by PiporGames** [comment] 2020-03-16 10:11
Arcore measure ap dosn't work either on me.

**Comment by PiporGames** [comment] 2020-03-16 10:11
Try another app...

**Comment by CleytonSarutobi** [comment] 2020-03-16 10:21
I try in Pokémon GO, but don't work. I was so happy that I was finally going to be able to take cool pictures, but it still doesn't work, I'll wait.

**Comment by PiporGames** [comment] 2020-03-16 10:26
All apps i have used it crashes or freezes. Only two of them works. Minecraft Earth and Froggie Jump. I'm quite disappointed.

**Comment by CleytonSarutobi** [comment] 2020-03-16 10:31
The way is to wait to fix it, maybe it's a bug.

**Comment by dexter-v** [comment] 2020-03-16 10:31
@PiporGames Don't be disappointed you are now able to play a game you wanted. True it's not working for all other things but it is a improvement for you.

**Comment by PiporGames** [comment] 2020-03-16 10:44
@dexter-v yeah you're right

**Comment by CleytonSarutobi** [comment] 2020-03-18 20:49
There was an update today for ARCore, and this time it's working perfectly on Pokémon GO in my Redmi Note 8 Pro, thanks Google.

**Comment by PiporGames** [comment] 2020-03-18 20:59
Sure, an update has been realeased these morning. For now, all applications are working fine. Pokemon Go, Minecraft Earth, RulerAR, FnaF AR, etc... are working fine. I will keep an eye on new apps that I find. For, now, the final stage is to wait until Google publishes the full support in Play Store.

**Comment by TechSlave** [comment] 2020-03-18 21:03
Does it work with Redmi Note 8? I don't have the pro and i'm worried

**Comment by PiporGames** [comment] 2020-03-18 21:15
Try it for yourself, install the lastest apk from APK pure.

**Comment by TechSlave** [comment] 2020-03-18 21:17
just did, didn't work

**Comment by dexter-v** [comment] 2020-03-19 07:24
It doesn't work on RN8. Tried both Google Measure and Elements. There first one gives error device not supported the second crashes. So fixes for RN8 are still needed. Hopefully Google is working on them. The development for RN8Pro gives me hope.

**Comment by Shaunimsorry** [comment] 2020-03-19 13:07
Just tried to run some AR measure apps no joy, also tried to update the ARCore via APKPure's app since i have a chinese Note 8, no joy. GPS is also barely working might be time to flash the global rom onto her.

Currently running MIUI 11.0.5

**Comment by PiporGames** [comment] 2020-03-19 13:13
I'm using Europe Stable Rom MIUI 11.0.2 / Android 10

**Comment by Shaunimsorry** [comment] 2020-03-19 14:44
> I'm using Europe Stable Rom MIUI 11.0.2 / Android 10 / Redmi Note 8 Pro

is the AR working ? maybe a flash is the key then

**Comment by PiporGames** [comment] 2020-03-19 16:50
For me it's working with no problems, only that playstore don't recognize the device as Arcore compatible, so you need to install through ApK

**Comment by adelfi43** [comment] 2020-03-19 18:15
Just to give explanation, PiporGames has the Note 8 Pro while this thread
is for the Note 8.
Good to know that you can use it, Pipor! Gives us the expectation that
someone could develop for the Note 8 too.
Best regards,
Henrique

**Comment by dexter-v** [comment] 2020-03-19 18:54
@adelfi43 took the words out of my mouth. The thread is for RN8. To summarize AR is working on RN8Pro if you download the apk manually. It does NOT work on RN8 currently. Let's hope they will support it in the future. Thanks @PiporGames for the recent development.

**Comment by PiporGames** [comment] 2020-03-19 20:11
My thread was closed because of duplicate thread and they said me that this was the main thread.

**Comment by PiporGames** [comment] 2020-03-19 20:12
Let's wait and see for support for RN8

**Comment by jiten-parmar** [comment] 2020-03-21 09:46
I am having Redmi note 8 pro please guide me how to use ar core+ on Pokemon go

**Comment by PiporGames** [comment] 2020-03-21 11:16
PokemonGo only works with Arcore on redmi note 8 pro, not with the plus variant

**Comment by A-khames** [comment] 2020-03-21 13:07
I do not understand why all this delay ??
realme released phone at the same time supports this feature !!!

**Comment by PiporGames** [comment] 2020-03-21 13:09
Commercial treatments I guess.

**Comment by A-khames** [comment] 2020-03-21 13:12
I got this phone to work on my graduation project and now I don't know what to do! 
I am very sad.

**Comment by PiporGames** [comment] 2020-03-21 13:33
Arcore is just a feature to play or test some applications in AR. The phone is capable of much more!. Google is the one who decides to support, or not, the device.

**Comment by OMustafar** [comment] 2020-03-28 02:17
I strongly request my Redmi Note 8 to support ARCore. I feel like I'm especially being forced away from all the great things, especially whenever I see Redmi Note 7 on the supported devices list.

**Comment by HasinduLanka** [comment] 2020-04-01 11:29
Yeah, come on... we need AR core on Redmi note 8

**Comment by CleytonSarutobi** [comment] 2020-04-03 23:56
You who have Note 8, look if it was released, because a friend of mine said that he managed to install it through the Playstore. I went to check and it really shows that it is now compatible.
![IMG_20200403_205057_285](https://user-images.githubusercontent.com/60781760/78413385-8fe3ee80-75ed-11ea-9484-561d6832bc34.jpg)

**Comment by Shaunimsorry** [comment] 2020-04-03 23:59
> You who have Note 8, look if it was released, because a friend of mine said that he managed to install it through the Playstore. I went to check and it really shows that it is now compatible.
> ![IMG_20200403_205057_285](https://user-images.githubusercontent.com/60781760/78413385-8fe3ee80-75ed-11ea-9484-561d6832bc34.jpg)

Holy wow, checked and it appears to now be compatible ! will run some tests asap on this, amazing !!!! expect a response shortly

**Comment by Shaunimsorry** [comment] 2020-04-04 00:05
Update:
Google Play Services AR now shows up in the store
Installed Google LLC Measure app
Phone kept vibrating as it struggled to find the floor but! it was working on some level, i could see points and basic surface detection

You can see its barely working, BUT its getting there
Trying out other measurement apps now!

Very excited

**Comment by adelfi43** [comment] 2020-04-04 00:08
Great! You are right! I´ve just downloaded through Play Store!
Finally!
Thanks guys!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by dexter-v** [comment] 2020-04-04 06:55
Confirmed, available, installed, AR Elements working. Congrats all and thank you Google dev team and Xiaomi.

**Comment by OMustafar** [comment] 2020-04-04 13:52
Yep, just downloaded from the Play Store. Works perfectly. Thanks Google and Xiaomi!

**Comment by A-khames** [comment] 2020-04-04 14:17
Good news .. now supported

**Comment by dexter-v** [comment] 2020-04-04 16:31
@OMustafar definitely not working perfectly, AR Elements loses tracking and Google measure doesn't work pretty much at all. Hopefully all bugs will be cleared with further development and the device will be added to the list of supported devices and work perfectly.

**Comment by CleytonSarutobi** [comment] 2020-04-07 00:19
![Screenshot_2020-04-06-21-17-33-379_com android chrome](https://user-images.githubusercontent.com/60781760/78616951-29104080-784c-11ea-9d01-0cd1df312c91.jpg)
Now, officially the Redmi Note 8, 8 Pro and 8T support ARCore.

**Comment by anujroadrage** [comment] 2020-07-28 04:58
When the support for redmi note 9 pro max will be provided.

**Comment by PiporGames** [comment] 2020-07-28 08:18
Why are you asking here? You know very well this is for Redmi Note 8 / Pro / T

**Closed** 2021-02-01 19:26 UTC
Labels: device support

**Comment by ivoras** [comment] 2021-06-22 07:05
Bump, at least of a sort. This is now mid 2021, and an AR app I've published is available on mobile phones mentioned in the ARCore device compatibility list, EXCEPT on Xiaomi Redmi Note 8 Pro, where at least two users reported the app store doesn't allow them to install the app, stating there's no compatible version (the devices are verified on the compatible devices list, with no "unsupported" hw variants).

My app does not have any entries in the device exclusion list. It's strange, because the users can, and do, have ARCore installed. 

Has anyone encountered that? How can I start looking into what's going on - why are Note 8 Pro devices barred from installing my app? ([link to the app on Google Store](https://play.google.com/store/apps/details?id=vision.equinox.app&hl=en)).

![203019249_318463423106335_6514378655916207844_n](https://user-images.githubusercontent.com/2300424/122879060-c021c500-d338-11eb-8ca5-449a4ae24c37.jpg)
![202593436_240290510878295_7945949652774809385_n](https://user-images.githubusercontent.com/2300424/122879070-c44de280-d338-11eb-87e4-cb14bb80020f.jpg)

**Comment by GMAGD** [comment] 2021-09-14 13:58
redmi note 8 2021  not working with ARCore ! :(

**Comment by dradb** [comment] 2022-04-12 07:10
Redmi Note 8 Pro supports ARCore ... BUT without depth.  
Note 9, 10, 105G, 10 Pro,  DO support depth.

**Comment by PiporGames** [comment] 2022-04-12 08:02
> Redmi Note 8 Pro supports ARCore ... BUT without depth. Note 9, 10, 105G, 10 Pro, DO support depth.

Does Depth need a custom sensor, or is it software thing?
