### ISSUE TITLE
Xperia XZ Premium ARcore working good but..

### ISSUE THREAD

**Issue by Indashio** [google-ar/arcore-android-sdk#227] opened 2018-03-07 09:47 UTC
Hi I use ARCore on my xz premium it works after restart phone. 5,10 minutes and ARCore not working good. Objects does not detect space. They work like a sticker not ar object

**Comment by inio** [comment] 2018-03-07 16:23
It is very odd that it is working **at all* on that device.  It is certainly not supported.

What device fingerprint does it report?  You can get this by running `adb shell getprop ro.build.fingerprint`

**Comment by Indashio** [comment] 2018-03-07 18:07
I set fingerprint from Pixel XL with Pixelify And it's normally working but only 5,10 minutes You know why ?

**Comment by Indashio** [comment] 2018-03-07 18:27
Link with video how it works on XZ Premium: https://megawrzuta.pl/download/79c9ce71b1ffbdc6088aa6d0cebf499e.html

**Comment by inio** [comment] 2018-03-07 18:28
Because we have not calibrated that device.  Given that it drifts out of function as you describe, it is possible will will be entirely impossible to calibrate that device.

Making ARCore work requires careful calibration of the exact behavior of the camera and IMU, in particular their timing.  What's likely happening is that shortly after reboot the camera and IMU of your device behave similarly enough to that of a pixel for the system to work.  Once the device has been up for more than a few minutes, the timestamps coming from one of them start to drift, and we can no longer solve the device motion because the two signals disagree.  Even a few milliseconds of error is enough to mess up tracking.

**Comment by inio** [comment] 2018-03-07 18:28
Duplicate of #89

**Closed by inio** 2018-03-07 18:28 UTC
Labels: device support, invalid
