### ISSUE TITLE
Supported Sony Xperia XZ Premium

### ISSUE THREAD

**Issue by FrostyM** [google-ar/arcore-android-sdk#609] opened 2018-10-16 15:52 UTC
In version 1.5 i see the XZ Premium on supported list but not XZs G8231, as far as i know its exactly the same camera. Other difference that is the reason for this?
Also in the files i find a lot of info for XZs but not in asset device database files, in version 1.3 the device profile eisted for XZs but then removed but still the calibration info for the phone is in the libarcore file in v1.5. Getting support soon? Whats missing?

**Comment by inio** [comment] 2018-10-18 17:53
Duplicate of #89

**Closed by inio** 2018-10-18 17:53 UTC
