### ISSUE TITLE
ARCore: how to detect insufficient lighting ? 

### ISSUE THREAD

**Issue by RegisAG** [google-ar/arcore-android-sdk#344] opened 2018-04-30 16:40 UTC
Hi,

ARCore will not be able to detect surfaces if the lighting is insufficient.

Question : how to detect insufficient lighting in order to be able to inform the user ?

I could use a timer to display an alert after a few seconds but I will not know if the lack of surface detection is due to an insufficient lighting or another reason (no feature points, etc...)

So, how to check if the insufficient lighting is the probable reason of the non-detection of planes ? 

Thanks.

**Comment by inio** [comment] 2018-04-30 18:01
lighting estimation may work even while not tracking and provide this.

**Comment by inio** [comment] 2018-04-30 18:01
Duplicate of #238

**Closed by inio** 2018-04-30 18:01 UTC
