### ISSUE TITLE
CPU Frame Size of the New ARCore 1.1 is only 640 X 480

### ISSUE THREAD

**Issue by WissamElkadi** [google-ar/arcore-android-sdk#293] opened 2018-04-06 11:39 UTC
Hi
Can I get 1280 X 720 frame size from the new ARCore 1.1 ArFrame_acquireCameraImage ?

Cheers,
Wissam

**Comment by inio** [comment] 2018-04-06 16:55
This is the primary reason I haven't closed #92 yet.  This ties in with #153.

**Comment by inio** [comment] 2018-04-06 16:55
Duplicate of #153

**Closed by inio** 2018-04-06 16:55 UTC
