### ISSUE TITLE
Asus ZenFon3 get availability SUPPORTED_NOT_INSTALLED but also "device isn't compatible with this version"

### ISSUE THREAD

**Issue by dev4711** [google-ar/arcore-android-sdk#485] opened 2018-07-13 12:38 UTC
Asus ZenFon3, with Android 7. 

Get from the checkAvailability(this) a SUPPORTED_NOT_INSTALLED but when opening arcore in the playstore to install, can't install and get the message "your device isn't compatible with this version".
The availability check should rather return a UNSUPPORTED_DEVICE_NOT_CAPABLE.

**Comment by dev4711** [comment] 2018-07-13 13:57
Same problem occurs for the moto g4 with android 7.

**Comment by inio** [comment] 2018-07-13 23:45
That's rather odd.  Could you post a logcat?

**Comment by dev4711** [comment] 2018-07-17 07:23
private fun checkIsARCoreUnsupported():Boolean
    {
        val availability = ArCoreApk.getInstance().checkAvailability(applicationContext)
        return availability.isUnsupported()
    }
returns false, because the availability is SUPPORTED_NOT_INSTALLED.

Its interesting because in the log statements which are related to the arcore are:

ARCore-InstallService: Install service connected
E/ARCore-InstallService: The device is not supported.
W/ARCore-InstallService: requestInstall = -5, launching fullscreen.
E/StandardArFragment: Error: Failed to create AR session
    com.google.ar.core.exceptions.UnavailableUserDeclinedInstallationException
        at com.google.ar.core.InstallActivity.finish(Unknown Source)

So the behavior is still "this application requires the latest version of arcore" dialog-> continue button to open play store -> "your device isn't compatible with this version." message in the play store.

**Comment by inio** [comment] 2018-07-23 20:34
Have you side-loaded a previous version of ARCore?  For better handling of areas where the Play Store servers are unavailable, we treat the presence of any ARCore APK to imply support.

**Comment by dev4711** [comment] 2018-07-26 08:30
Hmm okay no side-loaded verion of a previous ARCore is known as far as I know. So this means once any ar-core supporting apk is installed it will return always the state that it is supported?

**Comment by inio** [comment] 2018-07-27 23:46
no, once the ARCore APK itself is installed it will return supported.  This is done because are environments where we can install ARCore but cannot contact the Google Play Store servers to determine compatibility.

**Comment by inio** [comment] 2018-07-27 23:57
Oh, I just noticed something else:  Is your app marked as AR-Required?  If so (for similar reasons to above) checkAvailability will always return a `SUPPORTED_…` code.  See [Enable ARCore](https://developers.google.com/ar/develop/java/enable-arcore) for details on how to mark your app as Optional or Required.

**Comment by inio** [comment] 2018-08-07 22:18
@dev4711 I've been unable to reproduce this behavior.  Is it possible your app is marked AR-Required?

**Comment by dev4711** [comment] 2018-08-10 09:17
Yes the app(my app and justALine) is ar-required.

**Closed** 2018-09-27 17:14 UTC
Labels: bug, device support
