### ISSUE TITLE
Unable to recover planes and anchors after session resume in Developer Preview 2

### ISSUE THREAD

**Issue by mahjiang** [google-ar/arcore-android-sdk#164] opened 2018-02-07 20:48 UTC
Developer Preview 2 was supposed to include with it the ability to recover planes and anchors after sessions are paused then resumed, as indicated [here](https://github.com/google-ar/arcore-android-sdk/releases). However, I am unable to replicate this in the Hello AR sample app nor in an implementation of the SDK. Previously tracked planes remain in `Trackable.TrackingState PAUSED` and previously tracked anchors remain in `Trackable.TrackingState STOPPED` after resuming the session.

Please advise! Thanks in advance.

**Comment by JamiesonPryor** [comment] 2018-02-07 23:30
Hello, I'm actively looking into this and will respond ASAP.

**Comment by JamiesonPryor** [comment] 2018-02-08 01:09
I'm afraid I don't have a strong sense of what exactly is wrong.  Please keep in mind that the back button (not the home button) can actually close the app (not just pause) thus effectively destroying your session.  I've verified this is functioning correctly on 1.0, so perhaps this is due to an underlying complication that's been resolved.  My apologies.

**Comment by mahjiang** [comment] 2018-02-08 14:38
Just to clarify, do you mean that you are getting the same behavior as I am? If so, do you know when we can expect a fix? I have been testing this functionality using the recents button, backgrounding the app then bringing it back to the focus.

**Comment by JamiesonPryor** [comment] 2018-02-08 19:23
I apologize, my response was too vague.  I was also able to reproduce this issue.  It will be fixed in the 1.0 release.

**Comment by inio** [comment] 2018-02-23 16:58
This should be fixed with the new version of ARCore just released on the Play Store.  Update your ARCore and you should see planes and anchors coming back after pause/resume.

**Closed by inio** 2018-02-23 16:58 UTC
Labels: bug, fixed in upcoming release
