### ISSUE TITLE
Samsung Galaxy S6 support ?

### ISSUE THREAD

**Issue by motorsep** [google-ar/arcore-android-sdk#334] opened 2018-04-24 21:11 UTC
I am wondering when Samsung Galaxy S6 series support is coming to ARCore (S6 and S6 Edge in particular).

Thanks beforehand

**Comment by inio** [comment] 2018-04-25 00:07
Besides the devices listed at the top of #89, we cannot comment on supporting any specific devices.

**Comment by inio** [comment] 2018-04-25 00:07
Duplicate of #89

**Closed by inio** 2018-04-25 00:07 UTC
Labels: device support, duplicate
