### ISSUE TITLE
MI 6x Updated to MIUI10 still not support

### ISSUE THREAD

**Issue by LJHhahaha** [google-ar/arcore-android-sdk#559] opened 2018-09-11 02:02 UTC
I am a Unity user,my phone is XIAOMI 6X, I have tried befor update MIUI10,  yesterday  i updated to MIUI10， i tried again，still black screen， little disappointed。

**Comment by inio** [comment] 2018-09-12 17:34
The Xiaomi 6X is not on our [Supported Device List](https://developers.google.com/ar/discover/supported-devices).

**Comment by inio** [comment] 2018-09-12 17:34
Duplicate of #89

**Closed by inio** 2018-09-12 17:34 UTC
