### ISSUE TITLE
arcore1.0 does not support huawei P9(Android7.0)

### ISSUE THREAD

**Issue by gupengcheng** [google-ar/arcore-android-sdk#189] opened 2018-02-24 08:54 UTC
when i run hello_ar_java demo, it show 'This device does not support AR', can you tell me when it  will support more devices?

**Comment by inio** [comment] 2018-02-26 17:40
@gupengcheng What is your device fingerprint?  Capture it with:

    adb shell getprop ro.build.fingerprint

**Comment by inio** [comment] 2018-02-26 17:55
Oh, wait, sorry, that's not a supported device.

**Comment by inio** [comment] 2018-02-26 17:55
Duplicate of #89

**Comment by inio** [comment] 2018-02-26 17:56
Supported devices are listed here:

https://developers.google.com/ar/discover/#supported_devices

**Closed** 2018-02-26 19:18 UTC
Labels: device support, feature request
