### ISSUE TITLE
S6 on 6.0.1 -  NDK crash - ARCore 1.2

### ISSUE THREAD

**Issue by arco1082** [google-ar/arcore-android-sdk#386] opened 2018-05-16 20:57 UTC
We are trying to have one app that has ARCore as an optional library that enables additional features in our app.  We are using the Android NDK and the app crashes upon launch when the native library gets linked:
 java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memmove" referenced by "/lib/arm/libarcore_sdk_c.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)

Some relevant info:
- ARCore version : 1.2.0
- MinSDK: 21
-CompileSDK: 27
- TargetSDK: 27
- BuildTools: 27.0.3
- Device: S6
- Model: SM-G920V
- OS: 6.0.1

**Comment by inio** [comment] 2018-05-17 17:42
Duplicate of #212

**Closed by inio** 2018-05-17 17:42 UTC
