### ISSUE TITLE
ARCore 60 FPS feature doesn't work in the supported devices (e.g. Pixel)

### ISSUE THREAD

**Issue by xiaofengzhang777** [google-ar/arcore-android-sdk#1600] opened 2023-07-25 01:56 UTC
### SPECIFIC ISSUE ENCOUNTERED
Having acquired the `Google Pixel 7 Pro`, which supports 60FPS, I endeavored to execute sample `computer_vision_c` provided in the respective repository. Regrettably, the state of the texture rendering appeared far from achieving the desired 60FPS, hence necessitating this report.

### VERSIONS USED
- Android Studio: `Android Studio Electric Eel | 2022.1.1`
- ARCore SDK for Android: `1.38.0`
- Device manufacturer, model, and O/S: `Google / Pixel 7 Pro / Android 13`
- Google Play Services for AR (ARCore):  `1.38.231530493` (updated on Jun 28, 2023)

### STEPS TO REPRODUCE THE ISSUE
1. Open the `computer_vision_c` sample provided in the respective repository using Android Studio
2. Proceed to build the project
3. Execute the application

### ADDITIONAL COMMENTS
* A short while ago, due to the necessity of a 60FPS feature, I purchased the Pixel 7 Pro device after referencing the list of devices specified in the provided link:
  * https://developers.google.com/ar/devices
* For the purpose of addressing this issue, provided herein are the links to a list of other observed issues:
  * https://github.com/google-ar/arcore-android-sdk/issues/604
  * https://github.com/google-ar/arcore-android-sdk/issues/1573
  * https://github.com/google-ar/arcore-unity-sdk/issues/744
  * https://github.com/google-ar/arcore-android-sdk/issues/1119
* I've also attempted to rectify the issue by modifying function `void ComputerVisionApplication::obtainCameraConfigs()` within file `computer_vision_application.cc`. Despite changing the arguments in function `ArCameraConfigFilter_setTargetFps` with `AR_CAMERA_CONFIG_TARGET_FPS_60`, the camera preview rendering seems to remain at 30FPS.

It is my understanding that ARCore is advertised to support up to 60 frames per second (FPS), however, I am having difficulty achieving this performance. I'm unsure whether this is due to a fault in the device itself, a lack in the support of ARCore, or if it is a result of some errors in the usage of code. If indeed the support has been discontinued, it may be prudent to consider its removal from the official documentation for the sake of clarity and accuracy.

**Comment by xiaofengzhang777** [comment] 2023-07-25 02:16
I'd like to bring to your attention that when I executed the same sample on a `Pixel 4 XL` device, it worked perfectly at 60 FPS as a charm. I hope this information may prove useful in resolving this issue at hand.

**Comment by devbridie** [comment] 2023-08-02 14:13
Hi,
This is a current [known issue](https://github.com/google-ar/arcore-android-sdk/releases/tag/1.38.0) due to the tracking failure regression on these devices. We're currently working with the Pixel camera team to solve this issue within the camera stack; hoping to get a fix in soon.

**Comment by 15kingben** [comment] 2024-05-20 19:59
Late update, but this is now fixed, provided the device has the Android 14 update or later.

**Closed by 15kingben** 2024-05-20 19:59 UTC
Labels: bug
