### ISSUE TITLE
ARCore not detecting surfaces since updating to Android 9 on Xperia XZ1 Compact

### ISSUE THREAD

**Issue by fizixman83** [google-ar/arcore-android-sdk#660] opened 2018-12-03 16:48 UTC
Since updating to Android 9 a couple weeks ago, ARCore is no longer detecting any surfaces. It looks like it's picking up the scattered points, but no surfaces are being detected or generated.

Running "adb shell getprop ro.build.fingerprint" yields:

Sony/G8441/G8441:9/47.2.A.0.306/1344763102:user/release-keys

Prior to the update, running on Android 8 ARCore worked great.

**Comment by richard3575** [comment] 2018-12-06 13:48
Same here. Xperia xz Premium 
Was working fine, surface detection was very good.
Since update to Android PIE it's now as you say it just won't find any surface!!
Also have tested on Samsung Tab S3 and the same is happening - but, that's on Android 8.0
None of our apps work that previously have.

**Comment by inio** [comment] 2018-12-07 18:16
Duplicate of #639

**Closed by inio** 2018-12-07 18:16 UTC

**Comment by fizixman83** [comment] 2018-12-07 20:19
For future readers, ARCore 1.6 has resolved all my tracking issues on the Xperia XZ1 Compact with Android 9.
