### ISSUE TITLE
ARCore Depth Detection 

### ISSUE THREAD

**Issue by MustaphaGH** [google-ar/arcore-android-sdk#206] opened 2018-02-28 15:13 UTC
We are currently working with S8+ supporting the ARCore 1.0 . We are getting started with the universe of AR but as we can see with our tests and the examples of Google there's always that problem of depth ;

The question : Is ARCore going to support the depth detection ? and what devices will support it . 
As far as we can see , the ASUS ZenFone AR is able to detect the depth but can we add hardware/requirements to the S8 or another smartphones for it be able to support the detection of depth ? if yes what are those requirements .

Thank you.

**Comment by inio** [comment] 2018-02-28 16:09
Duplicate of #120

**Closed by inio** 2018-02-28 16:09 UTC

**Comment by inio** [comment] 2018-02-28 16:11
For the time being, our efforts are focused on enabling AR experiences on conventional smartphones using only the IMU and color camera.  This may include depth sensing from motion parallax beyond the feature point tracks offered today, but in the near term don't expect any enabling of additional depth sensors such as was found on the Tango devices.

**Comment by monsieurpooh** [comment] 2019-05-25 10:13
So, you're supporting gimmicks that no one is using, over actual useful functionality. Come on Google get your priorities straight. Aren't you supposed to be the pioneers of accessibility? Don't you know how many blind people can benefit from ubiquitous depth sensing? There's ways to make an app to convert that depth image data to audio, and then given enough time to acclimate they could literally navigate as well as a bat. RBG image does not work as well for simple navigation, IMO, because it requires better fidelity.
