### ISSUE TITLE
Could you add support for Lenovo Phab2 Pro?

### ISSUE THREAD

**Issue by romanvfp** [google-ar/arcore-android-sdk#102] opened 2017-12-29 10:44 UTC
Could you add support for Lenovo Phab2 Pro, too, please? Otherwise it is kind of weird that it supports more advanced TangoCore but does not support ARCore, while I am sure that technologically it can support ARCore. The device was released just 1 year ago, so it is still quite new and up-to-date

**Comment by inio** [comment] 2017-12-29 18:26
ARCore currently requires Android N or later, and Lenovo currently says that [the Phab2 Pro will not be getting updated to N](https://support.lenovo.com/us/en/solutions/ht501098#tablet), so this looks pretty unlikely.

**Comment by inio** [comment] 2017-12-29 18:29
Duplicate of #89

**Closed by inio** 2017-12-29 18:29 UTC
Labels: enhancement, question

**Comment by romanvfp** [comment] 2017-12-29 19:57
@inio Thank you for the reply! Is there no way for ARCore developers to add support for more older versions of Android?
