### ISSUE TITLE
How to detect what Object (or Anchor) was hit. Is it even possible?

### ISSUE THREAD

**Issue by Jhonnybsg** [google-ar/arcore-android-sdk#345] opened 2018-04-30 18:34 UTC
Currently there is a way to detect when a plane is hit with HitResult. 

I am trying to move different objects in the screen, individually using the SDK for Android (a native application, not using Unity3D). 

But how to detect what object was hit? Do you guys have any suggestion? I know that HitResult detects any trackable, but it was not clear in the reference if an Anchor is a trackable. 

I've come through concepts like raycast (what is implemented by HitResult) and colorpicking. Is it reasonable that implement those algorithms myself for that kind of application? Or there is a better way to do it only with what Arcore provides?

I believe these examples showed in this video are made with Unity3D. The example with the little house and tree is basically what I need to do. 
[https://www.youtube.com/watch?v=ttdPqly4OF8](https://www.youtube.com/watch?v=ttdPqly4OF8)

**Comment by inio** [comment] 2018-05-02 04:02
ARCore's sample code is intended to demonstrate the capabilities of ARCore's motion tracking and scene understanding. It is not intended as a full engine.  Hit testing against virtual objects is a standard 3D graphics problem and not related to AR applications specifically, and so is not included to keep the samples simple.

Consider using Unity or Unreal if you're looking for more engine-level capabilities, and keep an eye on #52.

**Comment by inio** [comment] 2018-05-02 04:02
Duplicate of #52

**Closed by inio** 2018-05-02 04:02 UTC
Labels: duplicate, feature request
