### ISSUE TITLE
get marker image quality programmatically

### ISSUE THREAD

**Issue by michaelvogt** [google-ar/arcore-android-sdk#411] opened 2018-06-03 13:45 UTC
I'm creating an app that is meant to shoot marker images on location. For this, it would be helpful when I could get the image quality that arcoreimg provides also programmatically.

Is something like this in the works or actually available?

**Comment by inio** [comment] 2018-06-04 18:16
Sorry, but I'm not quite following your question.  Are you asking how to get the camera image with the same quality as the screen image?  Right now, your best option is to use the approach in the computervision sample's [`TextureReader`](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/computervision_java/app/src/main/java/com/google/ar/core/examples/java/computervision/TextureReader.java)

**Comment by inio** [comment] 2018-06-04 18:16
Duplicate of #92

**Closed by inio** 2018-06-04 18:16 UTC

**Comment by DavidArayan** [comment] 2018-06-05 01:32
@inio I think @michaelvogt means grabbing the quality of the marker (in scale of 0-100) via the ARCore runtime the same way that the arcoreimg tool's "./arcoreimg eval-img dog.png" does. Please correct me if i'm wrong.

**Comment by michaelvogt** [comment] 2018-06-05 02:07
@DavidArayan Yes, you are correct. Tried to find a better wording for the question at #416

**Comment by inio** [comment] 2018-06-05 23:00
Sorry about the misunderstanding.  Thanks for the request, I've flagged #416 properly.

**Comment by inio** [comment] 2018-06-05 23:01
Duplicate of #416
