### ISSUE TITLE
Is there any plan for an android 3D engine like Scenekit in iOS?

### ISSUE THREAD

**Issue by geosky** [google-ar/arcore-android-sdk#98] opened 2017-12-25 14:21 UTC
There are tons of java-based 3D engines or cross-platform C++ engines for choosing, but which one for Android? It's quite unwise to import a huge 3D game engine, like u3d, into a native android app. While, we find it quite helpful to have  Scenekit in iOS. Building a native AR iOS app using Swift is much easier.

**Comment by nirajsanghvi** [comment] 2017-12-28 17:55
This issue looks like a dupe of #52

**Comment by inio** [comment] 2017-12-29 17:54
Duplicate of #52

**Closed by inio** 2017-12-29 17:54 UTC
