### ISSUE TITLE
Models are changing colors abruptly after latest update

### ISSUE THREAD

**Issue by knightcube** [google-ar/arcore-android-sdk#757] opened 2019-04-01 08:48 UTC
### SPECIFIC ISSUE ENCOUNTERED
While placing a model on the plane the colors of the models are getting affected when they are viewed from different angles. I have provided screenshots below -

These are for 1.8.0 - 
![Screenshot_20190401-141301](https://user-images.githubusercontent.com/22871961/55314939-da85d480-5488-11e9-9f44-18c17e07da7a.png)
![Screenshot_20190401-141240](https://user-images.githubusercontent.com/22871961/55314945-dd80c500-5488-11e9-9152-551cfa156118.png)

This is for 1.7.0
![Screenshot_20190401-141021](https://user-images.githubusercontent.com/22871961/55314950-deb1f200-5488-11e9-9c13-94c241be648a.png)

### VERSIONS USED
- Android Studio: `3.2.1`
- ARCore SDK for Android: `1.8.0`
- Device manufacturer, model, and O/S: `Nokia, 7 plus, Android`
- ARCore: `1.8.190311076`
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: `Nokia/Onyx_00WW/B2N_sprout:9/PPR1.180610.011/00WW_3_51F:user/release-keys`

###WORKAROUNDS
 I checked with 1.7.0 instead of 1.8.0. It works fine.

**Comment by ivstka95** [comment] 2019-04-02 12:36
@knightcube i think the problem is in AR Core update. i have the same problem in `SceneView` without AR. i created similar issue in sceneform repo https://github.com/google-ar/sceneform-android-sdk/issues/639

**Comment by knightcube** [comment] 2019-04-02 13:38
Yes correct @ivstka95

**Comment by afeozzz** [comment] 2019-04-03 08:35
Also there are problems with other blending types especially transparency, I've returned back to 1.7

**Comment by kobe-anacoimbra** [comment] 2019-04-04 11:10
I'm also having this problem! Went back to 1.7 and it's ok now.

**Comment by romainguy** [comment] 2019-04-09 01:20
Try to reimport your models, it should fix the issue.

**Comment by kobe-anacoimbra** [comment] 2019-04-09 01:24
@romainguy in my case, I'm using directly from .sfb link

**Comment by romainguy** [comment] 2019-04-09 01:35
Try to recreate the .sfb from the .sfa.

**Comment by fredsa** [comment] 2019-05-16 05:14
Closing issue so we can track this in the Sceneform issue tracker:
https://github.com/google-ar/sceneform-android-sdk/issues/639

**Closed by fredsa** 2019-05-16 05:14 UTC
Labels: bug
