### ISSUE TITLE
android.os.strictmode.LeakedClosableViolation when enabling StrictMode.enableDefaults()

### ISSUE THREAD

**Issue by dkmoon** [google-ar/arcore-android-sdk#1291] opened 2021-10-01 13:06 UTC
### SPECIFIC ISSUE ENCOUNTERED

If I enable the _StrictMode_, I get exception messages like below. I'm wondering if this is safe to ignore.

### VERSIONS USED
- Android Studio: 2020.3.1 patch 1
- ARCore SDK for Android: Android: com.google.ar:core:1.26.0
- Device manufacturer, model, and O/S: Samsung SM-J730K
- Google Play Services for AR (ARCore):  1.26.212010303
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: samsung/j7y17ltektt/j7y17ltektt:9/PPR1.180610.011/J730KKKS5CUD1:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Add  _StrictMode.enableDefaults();_ at the top of _AugmentedFacesActivity.onCreate()_
 1. Run the app
 1. Log messages like this are produced:
 
 ```
 D/StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1924)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:303)
        at android.hardware.HardwareBuffer.finalize(HardwareBuffer.java:253)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:292)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:279)
        at java.lang.Daemons$Daemon.run(Daemons.java:140)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.openWithCallSite(CloseGuard.java:259)
        at dalvik.system.CloseGuard.open(CloseGuard.java:230)
        at android.hardware.HardwareBuffer.<init>(HardwareBuffer.java:247)
        at com.google.ar.infrastructure.imagesubsystem.hardwarebufferstream.AndroidHardwareBufferStreamProvider.nativeHardwareBufferToJava(Native Method)
        at com.google.ar.infrastructure.nativedatasource.imagesubsystem.ImageSubsystemWrapper$HardwareBufferHandle.hardwareBuffer(PG:1)
        at com.google.ar.core.Session.nativeUpdate(Native Method)
        at com.google.ar.core.Session.update(Session.java:2)
        at com.google.ar.core.examples.java.augmentedfaces.AugmentedFacesActivity.onDrawFrame(AugmentedFacesActivity.java:278)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1577)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
```

### WORKAROUNDS (IF ANY)

N/A

**Comment by devbridie** [comment] 2021-11-04 16:29
We've pinned this down to expected behavior; this is a false positive from StrictMode. We create a Java `HardwareBuffer` using a long-lived native hardware buffer using [this constructor](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/hardware/HardwareBuffer.java;l=239?q=hardwarebuffer). However, StrictMode will raise a false positive on this because we're "creating" a HardwareBuffer and purposefully not closing it (as the underlying hardware buffer in native is still in use).

**Closed by devbridie** 2021-11-04 16:29 UTC
Labels: bug

**Comment by eleventigerssc** [comment] 2021-12-06 19:00
@devbridie how to go around the StrictMode violation even if the behavior expected?
