### ISSUE TITLE
Unknown ARCore error (UnavailableDeviceNotCompatibleException) after update to 1.9.190422056 on Oneplus 3T

### ISSUE THREAD

**Issue by ThomasMldr** [google-ar/arcore-android-sdk#781] opened 2019-05-10 08:42 UTC
### SPECIFIC ISSUE ENCOUNTERED
After an update to ARCore version 1.9.190422056 on my phone, the app is suddenly no longer working.
When opening Google Measure I get the following error:
"Unknown ARCore error (UnavailableDeviceNotCompatibleException)"
Other apps that use ARCore also get errors or become unresponsive.
My colleague has the same phone and also has the same problems.

### VERSIONS USED
- Android Studio: 
- ARCore for Android: 1.9.190422056
- Device manufacturer, model, and O/S: OnePlus 3T (ONEPLUS A3003), OxygenOS 5.0.8, Android 8.0.0

### STEPS TO REPRODUCE THE ISSUE
 1. Install ARCore 1.9.190422056 on OnePlus 3T
 2. Install Google Measure on OnePlus 3T
 3. Open Google Measure
 4. Get error

### ADDITIONAL COMMENTS
ARuleR (AR Ruler App by Grymala) also gives an error: "Failed to create AR session"
Pokémon GO in Snapshot mode just becomes unresponsive

**Comment by sc5148** [comment] 2019-05-11 19:03
I am facing the same issue too on OnePlus 3T

**Comment by raj5287** [comment] 2019-05-12 03:00
Yup facing the same issue. Any solution so far?

**Comment by coggy9** [comment] 2019-05-12 06:23
Also having the same issue on a OnePlus 3T. Google's Measure app gives me this error, and other ARCore apps just crash. Have to downgrade to get ARCore apps working again.

**Comment by ThomasMldr** [comment] 2019-05-12 07:59
@coggy9 how did you manage to downgrade? I tried downloading an older APK from apkmirror but when trying to install it, I get "App not installed" all the time... :-/

**Comment by raj5287** [comment] 2019-05-12 11:18
@ThomasMldr first uninstall the latest one and then try to install the lower version. It will work.

**Comment by ThomasMldr** [comment] 2019-05-12 11:30
Aha I had to uninstall separately on the 2 profiles on my phone. Afterwards it works... Thanks!

**Comment by ThomasMldr** [comment] 2019-05-12 11:31
Damnit, didn't mean to close issue

**Comment by fredsa** [comment] 2019-05-13 20:28
We expect this issue to be fixed in an upcoming release.

The 1.8.0 APK (`ARCore_1.8.0.apk`) is available from the 1.8.0 releases page:
https://github.com/google-ar/arcore-android-sdk/releases/tag/v1.8.0

Note that each version of the SDK requires the same or later version of the APK. In order to use the 1.8.0 APK:
- Make sure your SDK version is <= 1.8.0
- Side-load `ARCore_1.8.0.apk` on your device
- (Optionally) disable Wi-Fi and/or automatic app updates, to prevent the Play Store from updates ARCore to the latest version

**Comment by fredsa** [comment] 2019-05-16 22:53
Update: We're working to restore the Oneplus 3T device profile in an [ARCore](https://play.google.com/store/apps/details?id=com.google.ar.core) update. Targeting rollout to all devices early next week.

**Comment by raj5287** [comment] 2019-05-22 05:24
@ThomasMldr the issue is fixed now, hence can close it

**Comment by fredsa** [comment] 2019-05-22 22:37
The update to [ARCore](https://play.google.com/store/apps/details?id=com.google.ar.core) has been rolled out to 100% of devices.

**Closed by fredsa** 2019-05-22 22:37 UTC
Labels: bug, fixed in upcoming release

**Comment by fredsa** [comment] 2019-05-22 22:39
To update your device, use the Google Play Store.

The updated APK which can be side-loaded if that's more convenient for you is also available from the [releases](https://github.com/google-ar/arcore-android-sdk/releases) page.

**Comment by ThomasMldr** [comment] 2019-05-23 03:33
Can confirm that it works again after update. Thanks a lot, guys!
