### ISSUE TITLE
Is 'Huawei P20 Lite' supported ?

### ISSUE THREAD

**Issue by RegisAG** [google-ar/arcore-android-sdk#388] opened 2018-05-18 08:44 UTC
I see in the compatibility list that P20, P20 Pro are supported. What about P20 Lite ?

Thanks.

**Comment by inio** [comment] 2018-05-18 17:13
If it's not on the list it's not officially supported.

**Comment by inio** [comment] 2018-05-18 17:13
Duplicate of #89

**Closed by inio** 2018-05-18 17:13 UTC
