### ISSUE TITLE
Huawei Y6s ARCore Device Support?

### ISSUE THREAD

**Issue by DeviUserYT2** [google-ar/arcore-android-sdk#1015] opened 2020-03-11 13:12 UTC
### VERSIONS USED
- Android version: 9
- API level: 28

![image](https://user-images.githubusercontent.com/62062337/76420341-edb15c00-63dc-11ea-9268-7b99ad61b78c.png)

**Comment by sandyfriend** [comment] 2020-03-30 17:21
Duplicate of #89

**Closed** 2021-01-05 18:07 UTC
