### ISSUE TITLE
Galaxy Note8 Run Sample Failed. Exception creating session ：FatalException

### ISSUE THREAD

**Issue by yuyashuai** [google-ar/arcore-android-sdk#354] opened 2018-05-04 08:31 UTC
Device：Samsung Galaxy Note8 (SM-N950U)
OS:android 8.0
```
05-04 16:29:50.368 9567-9567/com.google.ar.core.examples.java.helloar E/ActivityThread: Failed to find provider info for com.google.ar.core.services.calibrationprovider
05-04 16:29:50.368 9567-9567/com.google.ar.core.examples.java.helloar E/native: session_create_implementation.cc:208 Calling readDeviceProfile failed.
    session_create_implementation.cc:546 Failed to create calibration provider
05-04 16:29:50.368 9567-9567/com.google.ar.core.examples.java.helloar W/native: session_create_implementation.cc:547 ArSession_createImplementation returning ArStatusErrorSpace::AR_ERROR_FATAL: .
05-04 16:29:50.383 9567-9567/com.google.ar.core.examples.java.helloar E/HelloArActivity: Exception creating session
    com.google.ar.core.exceptions.FatalException
        at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:349)
        at com.google.ar.core.Session.nativeCreateSession(Native Method)
        at com.google.ar.core.Session.<init>(Session.java:110)
        at com.google.ar.core.examples.java.helloar.HelloArActivity.onResume(HelloArActivity.java:134)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1361)
        at android.app.Activity.performResume(Activity.java:7352)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3765)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3830)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1746)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6940)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by inio** [comment] 2018-05-04 18:03
>     Failed to find provider info for com.google.ar.core.services.calibrationprovider

Does restarting fix the issue once, and then after the phone has been asleep for a few minutes it breaks this way again?

Did this device ship with access to the Google Play Store?  ARCore is currently only supported on devices that shiped from the factory with Google Play and have regular access to the Google Play Store with a signed-in account.

**Comment by inio** [comment] 2018-05-12 14:33
Duplicate of #350

**Closed by inio** 2018-05-12 14:33 UTC
