### ISSUE TITLE
Device not supported: Galaxy S8 Active

### ISSUE THREAD

**Issue by jbsperber** [google-ar/arcore-android-sdk#256] opened 2018-03-22 12:52 UTC
The Samsung Galaxy S8 Active (SM-G892A) is not supported, while other S8 phones are.  It's a less common variant, but the hardware is almost the same as the other S8's (at least in USA).  

Please add support for this device.

**Comment by inio** [comment] 2018-03-22 14:17
Duplicate of #89

**Closed by inio** 2018-03-22 14:17 UTC
