### ISSUE TITLE
Save and restore session

### ISSUE THREAD

**Issue by dpproduction** [google-ar/arcore-android-sdk#132] opened 2018-01-18 09:59 UTC
Hello guys, I have a suggestion for improvement sdk.
In the Developer Preview 2 there is an functionality that lets AR apps pause and resume AR sessions. 
it's great, but I think it would be even better to add the ability to save and restore current session(for example to file). 
This would give a lot of opportunities, for example, to exchange a session between people so that they would see the same AR objects in one place with different phones. 
It would also be very useful for quests. One person leaves a message in a secret place (saves the session), others look for him with an open camera (they are trying to restore the session).

**Comment by inio** [comment] 2018-01-18 15:15
Duplicate of #94

**Closed by inio** 2018-01-18 15:15 UTC
