### ISSUE TITLE
Integrate to project with minSdkVersion lower than 24

### ISSUE THREAD

**Issue by Xanvial** [google-ar/arcore-android-sdk#140] opened 2018-01-24 02:54 UTC
Hi,
From what I understand, the ARCore use native camera API which is introduced on API 24. But is it possible to use ARCore native cpp on the project that has minSdkVersion lower than 24 (for example 14)? 

On ARCore java the native camera is loaded only when we create new Session, so it's possible to check the device API before. Although, it seems using the provided exception is not working on this. 

But from what I tried a while ago on ARCore cpp, it will try to load the native camera library at the start of the application. So it will crash on devices with API lower than 24. Is there any workaround?

**Comment by inio** [comment] 2018-01-24 04:29
Our intent is to be able to have apps targeting API levels as low as 14 be able to use ARCore when it is available (obviously on API ≥ 24).  This didn't get tested fully for DP2 and I believe may be somewhat/fully broken.  At the very least session creation will likely fail in less than ideal ways in unsupported environments.  With the upcoming 1.0 release we'll have much better support for this.

**Comment by inio** [comment] 2018-01-24 21:08
Duplicate of #111

**Closed by inio** 2018-01-24 21:08 UTC
Labels: bug, fixed in upcoming release
