### ISSUE TITLE
ARCore without preview?

### ISSUE THREAD

**Issue by bell-one** [google-ar/arcore-android-sdk#259] opened 2018-03-26 02:39 UTC
Hello, 

I'd like to develop AR like application without camera view,

In unity ARcore sdk, I can get ARcore information without camera view,
but in android studio sdk, if i make viewport without glsurfaceview which get texture from camera.

ARcore doesn't work properly, is there any way to use ARCore without glsurfaceview on android studio? like unitySDK?

**Comment by inio** [comment] 2018-03-26 03:07
ARCore currently requires an OpenGL context.  You don't have to draw the camera image, but you need a context in which to update it.  The overhead this texture is quite low, since the data is generated by the hardware scaler without CPU involvement.

**Comment by inio** [comment] 2018-03-26 03:08
Duplicate of #31

**Comment by inio** [comment] 2018-03-26 03:09
Re-reading, I'd like to point out one thing: You only need an OpenGL context, not actually to draw anything with it.  A purely offscreen context created directly with EGL would work.

**Closed** 2018-03-26 03:38 UTC
Labels: feature request

**Comment by jayathu** [comment] 2021-07-23 17:25
I am doing a similar exploration and wanting to track ARCamera Pose without rendering any camera frames. Are there any examples/ sample code I can take a look to see how I can get started on that? For starters, what do I need to grab the OpenGL context and go from there? Any API references or sample code references would be appreciated! Thanks.

**Comment by devbridie** [comment] 2021-07-26 09:37
I'm not aware of any samples here, but you could look at e.g. [the implementation of GLThread in GLSurfaceView](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/opengl/java/android/opengl/GLSurfaceView.java;l=1253?q=GLSurfaceView). Keep in mind that this isn't a usecase we explicitly support so YMMV.
