### ISSUE TITLE
GetRecentDevicePose failed — ARCore stopped working at all on Samsung Galaxy S8

### ISSUE THREAD

**Issue by alekostsom** [google-ar/arcore-android-sdk#591] opened 2018-10-02 12:20 UTC
Hello,

ARCore was working really well on my device (Galaxy S8). Last time i checked was almost 1 month ago. Today, I updated to ARCore 1.5 and all the apps that use ARCore are not working anymore. None of them. Seems that tracking never starts. I cannot see the blue point cloud dots in the sample, nor a surface is ever detected. I checked the logs with adb logcat and noticed that i am indeed getting the following error as soon as ARCore tracking launches in the app: 

`10-02 14:29:18.845 25027 25266 W native  : pose_manager.cc:80 GetRecentDevicePose failed. generic::invalid_argument: Passed timestamp is invalid. Latest VIO t:nan, latest IMU t:nan, query t:1209.90166236`

I reset to factory settings, installed ARCore again (even older versions through adb), but i am still facing the above troubles. My device's fingerprint is:
`samsung/dreamltexx/dreamlte:8.0.0/R16NW/G950FXXU4CRI5:user/release-keys`

**Comment by inio** [comment] 2018-10-02 20:47
Thanks for the report.  We'll look into it.

**Comment by alekostsom** [comment] 2018-10-08 07:33
Hi, do you have any updates on this issue?

**Comment by inio** [comment] 2018-10-12 17:13
@Daemon0x0 Do you mean the Unity helloAR?  If so, please post issues/questions for the Unity integration on the [google-ar/arcore-unity-sdk issues board](https://github.com/google-ar/arcore-unity-sdk/issues).

**Comment by Daemon0x0** [comment] 2018-10-12 19:01
@inio Yes, thank  you very much.

**Comment by Th3MrKill3r** [comment] 2018-10-23 04:40
Any updates on the issue, i got last version and still crashing

**Comment by Lukasenko22** [comment] 2018-10-23 14:32
I just bought Xiaomi POCOPHONE F1 for my project to develop ARCore app, and I got this Error too. Every time when I have this bug, device restart is needed and then ARCore is working again, but it has to be fixed.

**Comment by inio** [comment] 2018-10-25 17:40
@Lukasenko22 Do you have a Chinese version of the POCOPHONE F1?  Only versions of this device that ship with the Play Store are supported.

**Comment by inio** [comment] 2018-10-25 17:50
@alekostsom @Th3MrKill3r Could either of you capture a logcat from session create through to this failure?

**Comment by syntax-error404** [comment] 2018-10-28 01:03
Having the same issue with S9. Worked for the first run of my app then second time gave me "This Device does not support ARCore."

**Comment by Lukasenko22** [comment] 2018-11-01 13:09
@inio I installed ARCore from Play Store, but In China, devices do not ship with the Google Play Store. I guess I dont have Chinese version, but how do I determine for sure?

**Comment by inio** [comment] 2018-11-14 19:01
@syntax-error404 Could you file a separate issue and capture a logcat?

@Lukasenko22 What is the build fingerprint of your device?  You can find this with `adb shell getprop ro.build.fingerprint`

**Comment by richard3575** [comment] 2018-12-06 14:07
We're seeing the same @alekostsom  - ARCore used to work brilliantly, but now is useless.
We noticed this on Sony Xperia XZ Premium, and also on Samsung Tab S3 (both supported devices).
Xperia stopped after Android 9.0 update
Tab S3 is new and on Android 8.0 but has the same effect.

Tested using Unity HelloAR world, Ikea AR app, Google Measure app - all of them are giving very poor surface detection. Some of them will not get anything, others get something, but drift and are wildly out.

**Comment by inio** [comment] 2018-12-07 18:49
@synthercat Probably just the restart that fixed it.  We don't keep any dynamic data in the ARCore app.

@richard3575 for Sony devices watch #639.  For the Tab S3, if you could report the build fingerprint (`adb shell getprop ro.build.fingerprint`) and capture a logcat that could be helpful.

**Comment by richard3575** [comment] 2018-12-10 11:55
Thanks @inio for the Samsung Tab S3 this has Android 8.0.0
samsung/gts3lltexx/gts3llte:8.0.0/R16NW/T825XXU2BRG3:user/release-keys
And here's a logcat
Let me know if there's anything else you need.
[logtcat.txt](https://github.com/google-ar/arcore-android-sdk/files/2663022/logtcat.txt)

**Comment by richard3575** [comment] 2018-12-20 11:15
HI @inio any update on this issue? We have bought a Samsung Tab S3 specifically for use with ARCore as it is listed as a supported device, yet at the moment it is not functioning. We'd really appreciate an update on what the issue might be and when we can expect it to be fixed.
Let us know if there's any other information you require to help resolve the issue and we'll glad assist. Thank you

**Comment by sauldelabrida** [comment] 2018-12-29 20:18
I had the same problem using a S7 Edge Android 8.0 and ARCore SDK 1.6 for Unity. It works changing the Unity ARCore SDK to 1.4 :)

**Comment by richard3575** [comment] 2019-01-09 14:06
Hi @inio Happy New year and all that - any update on this issue? It's been over 3 months this issue was raised and it's still a problem. We're going to have to return the device (at cost to us) as it is not able to do what Google said it could. It would be great to get some indication if this is an ARCore issue, or an OS issue and if it's Google or Samsung - but given the wide spread issues across a range of devices I'm guessing it's a Google issue.   Some confirmation of this and when we might expect a resolution would be greatly appreciated.

**Comment by fredsa** [comment] 2019-01-23 00:04
Changing issue title to reflect that this issue is about the original `pose_manager.cc:80 GetRecentDevicePose failed` issue reported by @alekostsom on a **Samsung Galaxy S8**.

**Comment by fredsa** [comment] 2019-01-23 00:09
@richard3575 Thank you for the logcat output. since you mentioned seeing the same issue across multiple devices (S9, S8, S3 Tab) I suspect there's an issue with the app and/or build process, rather than an ARCore platform issue.

Please try running the unmodified **HelloAR** sample project. When doing so:
- Download the latest ARCore for Android SDK ([releases page](https://github.com/google-ar/arcore-android-sdk/releases))
- Connect an [ARCore supported device](https://developers.google.com/ar/discover/supported-devices)
- Make sure you device is up to date (running the latest available version of the o/s)
- Verify that the latest version of [ARCore](https://play.google.com/store/apps/details?id=com.google.ar.core) is installed

If this does not work, feel free to file a new issue in this issue tracker. Please provide the requested information as defaulted in after clicking "New issue", as well as attaching the output of `adb logcat` when running the **HelloAR** sample.

**Comment by fredsa** [comment] 2019-01-23 00:13
Closing this issue for now.
@alekostsom — if you are still seeing the `pose_manager.cc:80 GetRecentDevicePose failed` issues on the S8 using the latest ARCore SDK for Android, please include attach the output of `adb logcat` using the above steps to run an unmodified **HelloAR** app, and we can reopen. If you're experiencing other issues, please file a new issue.

**Closed by fredsa** 2019-01-23 00:13 UTC
Labels: bug, motion tracking

**Comment by richard3575** [comment] 2019-01-23 14:24
@fredsa - thanks for getting back to me Fred, I'll do as you outlines, however, just for clarity, I'm not personally seeing the issue on all the devices listed, I was referring to other peoples posts. If you look through the list of issues from myself and others it's clear there's a bigger issue. 

Also, I can confirm that we had the same problem on a Sony ZX Premium #639  - however that is now working correctly again after a Sony update. We have the same .apk builds running on both devices.

**Comment by alekostsom** [comment] 2019-01-28 10:40
@fredsa - Thanks for getting back to me. Unfortunately the issue is still occuring. I run both the Google Measure app and the HelloAR sample, built with Unity. ARCore 1.6 installed: 
[Measure Google App-logcat.txt](https://github.com/google-ar/arcore-android-sdk/files/2802514/Measure.Google.App-logcat.txt)
[HelloAR Unity build-logcat.txt](https://github.com/google-ar/arcore-android-sdk/files/2802515/HelloAR.Unity.build-logcat.txt)

And still no other installed ARCore app is working. I guess the issue should be reopened.

Thank you.

**Comment by richard3575** [comment] 2019-01-29 16:24
I agree with @alekostsom we're still seeing the issue. @fredsa as requested I've run the tests and created a new ticket #701 with logcat.txt
Any help would be much appreciated as it's unclear why a supported device isn't giving good results, we're now a long way behind on our development. 
Thank you

**Comment by fredsa** [comment] 2019-03-01 19:15
Note that this issue is closed. The best place to follow up is on the relevant open issue, or file a new issue if yours is related to a different device than the one covered by the issue.
