### ISSUE TITLE
Call ArSession_destroy method is too slow

### ISSUE THREAD

**Issue by 01098996** [google-ar/arcore-android-sdk#323] opened 2018-04-19 14:45 UTC
Sometimes I call _ArSession_destroy_ method and get stuck for a few seconds. This happens when switching between ARCore to Camera. But Camera to ARCore will not.

**Comment by 01098996** [comment] 2018-04-19 14:48
My phone is OnePlus A5000

**Comment by 01098996** [comment] 2018-04-19 14:55
Here is the log that calls ArSession_destroy from start to end.

```
04-19 22:52:04.254 22473-22776/com.meitu.partynow I/native: session_c_api.cc:194 Deleting ArSession...
04-19 22:52:04.255 22473-22776/com.meitu.partynow I/native: feature_combo_node.cc:191 Cleared scoped_image buffers in feature_combo.
    landmark_associator.cc:16 Total number of unique processed features: 541
    landmark_associator.cc:20 Number of unique landmarks with at least two measurements: 0
    landmark_associator.cc:22 Total number of landmarks in the map: 0
    landmark_associator.cc:24 Total number of landmark candidates: 541
04-19 22:52:04.261 22473-22776/com.meitu.partynow I/native: android_camera.cc:613 Reset cleanly got to CLOSED state for camera 1
    android_camera.cc:613 Reset cleanly got to CLOSED state for camera 0
04-19 22:52:04.262 916-5699/? I/Camera2ClientBase: Closed Camera 0. Client was: com.meitu.partynow (PID 22473, UID 10109)
04-19 22:52:05.205 771-1318/? D/audio_hw_primary: out_standby: enter: stream (0xe95fa000) usecase(1: low-latency-playback)
04-19 22:52:05.227 771-1318/? D/audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback quat_i2s
04-19 22:52:05.228 771-1318/? D/soundtrigger: audio_extn_sound_trigger_update_stream_status: uc_id 1 of type 0 for Event 2, with Raise=0
04-19 22:52:05.228 771-1318/? D/hardware_info: hw_info_append_hw_type : device_name = speaker
04-19 22:52:05.228 771-1318/? E/voice: voice_is_in_call:in_call 0
04-19 22:52:05.228 771-1318/? D/audio_hw_primary: out_standby: exit
04-19 22:52:05.701 904-1039/? I/ThermalEngine: Monitor : quiet_therm = 33, msm_therm = 38, ufs_therm = -40, battery_therm = 314,current_now = 26000 
04-19 22:52:06.488 3727-3802/? D/NetworkStateUtils: netWorkState=0
04-19 22:52:09.676 22473-22873/com.meitu.partynow I/android.media.AudioTrack: play() packageName: com.meitu.partynow
04-19 22:52:09.677 915-1803/? D/AudioFlinger: setParameters(): io 0, keyvalue isVoipApp=0, calling pid 22473
04-19 22:52:09.677 1415-5205/? D/AudioPlaybackMonitor: Found a new active media playback. ID:4391 -- type:android.media.AudioTrack -- u/pid:10109/22473 -- state:started -- attr:AudioAttributes: usage=1 content=2 flags=0x200 tags= bundle=null
04-19 22:52:09.678 1415-5205/? D/MediaSessionStack: updateMediaButtonSessionIfNeeded, callers=com.android.server.media.MediaSessionService$1.onAudioPlaybackStarted:151 com.android.server.media.AudioPlaybackMonitor.dispatchPlaybackConfigChange:127 
04-19 22:52:10.073 22473-22778/com.meitu.partynow W/native: analytics_logger.cc:197 Could not send event. Event will be dropped.
04-19 22:52:10.074 22473-22778/com.meitu.partynow V/third_party/redwood/base/jni_common/src/jni_helper.cc: ~JniHelper: about to detach thread. (Called from line 155.)
    ~JniHelper: detached thread. (Called from line 155.)
04-19 22:52:10.074 22473-22776/com.meitu.partynow V/third_party/redwood/base/jni_common/src/jni_helper.cc: JniHelper: about to attach thread. (Called from line 35.)
    JniHelper: thread already attached. (Called from line 35.)
    ~JniHelper: did not need to detach thread. (Called from line 35.)
04-19 22:52:10.074 22473-22776/com.meitu.partynow I/native: session_c_api.cc:196 Deleted ArSession.
```

**Comment by inio** [comment] 2018-04-19 15:56
Duplicate of #249

**Comment by inio** [comment] 2018-04-19 15:57
Note: to use the camera you only need to pause the session.  It can be left extant or destroyed in the background.

**Closed by inio** 2018-04-19 15:56 UTC
