### ISSUE TITLE
Is the ARCore APK work with Nokia 7 plus?

### ISSUE THREAD

**Issue by Thaina** [google-ar/arcore-android-sdk#374] opened 2018-05-10 09:30 UTC
Actually I wish there would be a list of devices that ARCore APK could just run on. ARCore official support is too slow and cannot cope with newer devices launch in market

I have a plan to purchase Nokia 7 plus specifically but I also want to buy it to develop AR application. So if it may not support ARCore it would waste my money

So I want to make sure that at least I can do some AR development on it

**Comment by inio** [comment] 2018-05-10 20:08
For Nokia devices, ARCore is only currently supported on the 6.1 and 8 Sirocco.

**Comment by inio** [comment] 2018-05-10 20:09
Duplicate of #89

**Closed by inio** 2018-05-10 20:09 UTC

**Comment by Thaina** [comment] 2018-05-21 11:30
@inio I am not asking for official support. I just ask that is it able to run the sideloading APK. Which is not duplicate with #89

**Comment by inio** [comment] 2018-05-22 14:39
We are not going to marginally enable devices through side-loading.  The announced-but-unlaunched devices are a special case because we need to have calibrations present in the API for when they launch.

**Comment by prateekkumarweb** [comment] 2018-06-16 09:59
Nokia 7 plus is going to get support for ARCore soon. [Discussion link on Nokia community forum](https://community.phones.nokia.com/support/discussions/topics/7000027807)

**Comment by inio** [comment] 2018-06-17 22:33
Sorry, was moving a little too quick there.  I'm not aware of any commitment from Google to support the Nokia 7.  I would advise against buying a device for doing ARCore development until it either shows up on the supported device list or there's been a press release from the OEM or Google announcing support.  The above linked forum post doesn't seem super official.

**Comment by matemaciek** [comment] 2018-06-22 19:16
I've just installed arcore on my Nokia 7+ (-:

**Comment by inio** [comment] 2018-06-22 20:47
@prateekkumarweb Yes, as @matemaciek mentioned, the Nokia 7+ is now a supported device with ARCore 1.3.
