### ISSUE TITLE
ARCore + Torch

### ISSUE THREAD

**Issue by erikist** [google-ar/arcore-android-sdk#382] opened 2018-05-15 20:47 UTC
We have a desire to use ARCore in lowlight situations where you might need your phones torch to be enabled. When I try to do do this using either the `Camera` or `Camera2` API, it freezes the ARCore rendering (i am sure because it is opening a camera stream which ARCore is using). Is this simply impossible?

**Comment by inio** [comment] 2018-05-15 20:48
Duplicate of #153

**Closed by inio** 2018-05-15 20:48 UTC
