### ISSUE TITLE
arcore's compatibility

### ISSUE THREAD

**Issue by minggangLu** [google-ar/arcore-android-sdk#76] opened 2017-11-28 10:20 UTC
when can all android's devices in Chinese Mainland use the arcore,now the supported devices are only galaxy s8 and pixel,one plus 5 ,nexus 6p

**Comment by lvonasek** [comment] 2017-11-28 10:30
https://plus.google.com/+ChuckKnowledge/posts/APHmy4gN9C8

**Comment by inio** [comment] 2017-12-15 22:34
ARCore Developer Preview 2 is only officially supported on the Pixel phones and most models of the Samsung S8.  We're hard at work to support 100M devices with the launch of ARCore 1.0 (coming out of preview) in the coming months.

**Comment by inio** [comment] 2017-12-15 22:35
Duplicate of #89

**Closed by inio** 2017-12-15 22:35 UTC
