### ISSUE TITLE
ARCore Stops Working after screen is paused or exited in Moto G6

### ISSUE THREAD

**Issue by shinbuck** [google-ar/arcore-android-sdk#551] opened 2018-09-05 00:04 UTC
ARCore works properly when I initially load up an app (Just a Line). After a couple of shrinking the app to background and loading the app back up as the main screen, ARCore completely stops working. I closed out all apps and tried opening another AR app and no tracking is able to be detected. To resolve this issue, I would have to reset my entire phone in order for ARCore to work again.

**Comment by inio** [comment] 2018-09-05 00:07
Thanks for the report.

What is your device fingerprint?  You can find this using `adb shell getprop ro.build.fingerprint`

**Comment by shinbuck** [comment] 2018-09-05 00:12
motorola/ali/ali:8.0.0/OPSS27.104-15-10-4/4:user/release-keys

**Comment by Kwu564** [comment] 2018-09-10 07:26
Hi guys, I have the exact same problem with ARCore on my Moto G6 as well.

**Comment by inio** [comment] 2018-09-10 19:26
@Kwu564 Would you mind also providing your build fingerprint?

**Comment by Kwu564** [comment] 2018-09-10 20:51
motorola/ali_amz/ali:8.0.0/OPSS27.104-15-10-4/3:user/release-keys

**Comment by Kwu564** [comment] 2018-09-10 21:54
Actually, for me the problem is more like sometimes when I keep an ARCore app shrunk/minimized for an extended period of time especially after my phone automatically locks itself and then I load up the app, ARCore tracking completely stops working.

**Comment by Kwu564** [comment] 2018-09-15 06:14
@inio  I found a series of forum posts on the Motorola website regarding similar issues with ARCore on the Moto G6 and one of them said they fixed those issues by using an older version of ARCore: [](https://forums.lenovo.com/t5/Moto-G6-Moto-G6-Plus-Moto-G6/ARCore-support-for-Moto-G6/td-p/4118986/page/4)

**Comment by inio** [comment] 2018-09-27 16:52
Just noticed this is a duplicate, please move discussion there

**Comment by inio** [comment] 2018-09-27 16:53
Duplicate of #483

**Closed by inio** 2018-09-27 16:53 UTC
Labels: bug, device support
