### ISSUE TITLE
Camera preview quality too low for Mixed Reality

### ISSUE THREAD

**Issue by kurse** [google-ar/arcore-android-sdk#466] opened 2018-07-01 16:41 UTC
I am currently trying to use ARCore for a Mixed Reality solution on Mobile, and the preview quality is too low to be usable on a cardboard-type headset. Is there any way to control and improve the camera feed quality?

**Comment by inio** [comment] 2018-07-03 19:58
Duplicate of #153

**Closed by inio** 2018-07-03 19:58 UTC
Labels: duplicate, feature request
