### ISSUE TITLE
Lenovo Tango

### ISSUE THREAD

**Issue by joduffy** [google-ar/arcore-android-sdk#179] opened 2018-02-21 23:21 UTC
Hi,

I have a Lenovo Tango and I seen that everything is moving to ARCore.
But I cannot get ARCore to work for the Lenovo.

Its not in the listed supported devices which I thought was strange as ARCore seems to be based off Tango sdk. Why would the Lenovo be able to do one but not the other?

Also,
Will the Visual Positioning Service be coming to ARCore?
Or was that only available due to the depth sensor in the Tango phones?

**Comment by joduffy** [comment] 2018-02-21 23:26
I seen that my post is a duplicate of a couple of others.

Is there any information on Visual Positioning Service for ARCore or what is being kept from the Tango side of things.

**Comment by inio** [comment] 2018-02-21 23:41
ARCore will not be coming to the Phab 2 Pro, as that device has not received an android N update and ARCore is heavily dependent on Android N (it uses the NDK camera API).

The first preview of ARCore was based on the Tango SDK, but it migrated away from that situation with Developer Preview 2.

**Comment by inio** [comment] 2018-02-21 23:41
Duplicate of #102

**Closed by inio** 2018-02-21 23:41 UTC
