### ISSUE TITLE
Moto E4 plus 

### ISSUE THREAD

**Issue by rajupinnam** [google-ar/arcore-android-sdk#151] opened 2018-01-31 11:35 UTC

**Comment by rajupinnam** [comment] 2018-01-31 11:36
Is it supports in future ? If it is when?

**Comment by inio** [comment] 2018-01-31 16:58
Currently Developer Preview 2 supports only the devices listed on [this page](https://developers.google.com/ar/discover/#supported_devices).

**Comment by inio** [comment] 2018-01-31 16:58
Duplicate of #89

**Closed by inio** 2018-01-31 16:59 UTC
