### ISSUE TITLE
Zenfone AR can't find surfaces in ARCore

### ISSUE THREAD

**Issue by thnewlands** [google-ar/arcore-android-sdk#286] opened 2018-04-03 20:37 UTC
ASUS_A002A on software version VZW_V3.7.8_20170922 with ARCore version 1.1.180312063 won't find surfaces in any ARCore app. Tango SLAM works perfectly. Has anyone else encountered this?

**Comment by inio** [comment] 2018-04-03 20:45
Duplicate of #183

**Closed by inio** 2018-04-03 20:45 UTC

**Comment by inio** [comment] 2018-04-03 22:26
Short answer: Known driver issue.  Restart phone, should work for about 26 hours.  After that an internal counter rolls over.
