### ISSUE TITLE
Framerate of arcore

### ISSUE THREAD

**Issue by bell-one** [google-ar/arcore-android-sdk#234] opened 2018-03-12 04:54 UTC
Is there any variable or options for frame rate?

In my application, without arcore, it shows over 60 fps.
but after push arcore function in it, frame rate goes down almost 30 fps.

I'd like to make more smooth screen, please help!

thanks

**Comment by inio** [comment] 2018-03-12 17:25
Duplicate of #153

**Closed by inio** 2018-03-12 17:25 UTC
