### ISSUE TITLE
AnchorNode not stable and moves around when placed without surface detection 

### ISSUE THREAD

**Issue by rramprasad** [google-ar/arcore-android-sdk#394] opened 2018-05-22 16:58 UTC
I have used following code,to place 3D object infront of camera without any hittest. It places object,but the object is not stable on same place. Sometimes it moves around. It is not stay on same place like placing object after detecting surfaces. Is it nature of ARCore or it is an issue in my code.
 
```
@override
public void onUpdate(FrameTime frameTime) {
if(arSceneView.getArFrame() == null){
Log.d(TAG, "onUpdate: No frame available");
// No frame available
return;
}

    if(arSceneView.getArFrame().getCamera().getTrackingState() != TrackingState.TRACKING){
        Log.d(TAG, "onUpdate: Tracking not started yet");
        // Tracking not started yet
        return;
    }

        if (this.mAnchorNode == null && andyRenderable != null) {
            Log.d(TAG, "onUpdate: mAnchorNode is null");
            Session session = arSceneView.getSession();

            /*float[] position = {0, 0, -1};
            float[] rotation = {0, 0, 0, 1};
            Anchor anchor = session.createAnchor(new Pose(position, rotation));*/

            Vector3 cameraPos = arSceneView.getScene().getCamera().getWorldPosition();
            Vector3 cameraForward = arSceneView.getScene().getCamera().getForward();
            Vector3 position = Vector3.add(cameraPos, cameraForward.scaled(1.0f));
            
            // Create an ARCore Anchor at the position.
            Pose pose = Pose.makeTranslation(position.x, position.y, position.z);
            Anchor anchor = arSceneView.getSession().createAnchor(pose);

            mAnchorNode = new AnchorNode(anchor);
            mAnchorNode.setParent(arSceneView.getScene());


            Node node = new Node();
            node.setRenderable(andyRenderable);
            node.setParent(mAnchorNode);
            node.setOnTapListener(new Node.OnTapListener() {
                @Override
                public void onTap(HitTestResult hitTestResult, MotionEvent motionEvent) {
                    showBottomSheet();
                }
            });
        }
}
```

**Comment by inio** [comment] 2018-06-01 22:55
Duplicate of #395

**Closed by inio** 2018-06-01 22:55 UTC
