### ISSUE TITLE
Does not support samsung s8 (SM-G9500) ?

### ISSUE THREAD

**Issue by paopao-yu** [google-ar/arcore-android-sdk#39] opened 2017-09-27 07:09 UTC
When I install the sample HelloAR，it toasted “This device does not support AR”.
So not all S8 support？

**Comment by kschima** [comment] 2017-09-27 07:17
See "Supported Devices" here:

https://github.com/google-ar/arcore-android-sdk/releases

**Comment by sinojelly** [comment] 2017-09-27 08:26
SM-G950W is supported, but SM-G9500 not, this cause a huge number of developers in china can not test arcore.
Their hardware seems no critical difference. see : http://www.phonemore.com/compare/phones/samsung-galaxy-s8-sm-g950w-vs-samsung-galaxy-s8-duos-sm-g9500/5338258

Could you do me a favor to change the SupportedDevices.java a little to support SM-G9500,
build fingerprint is : 
samsung/dreamqltezc/dreamqltechn:7.0/NRD90M/G9500ZCU1AQF7:user/release-keys

and send the test software to me (sinojelly@gmail.com), i can test it.

Thanks!

**Comment by Ernie1998** [comment] 2017-09-30 16:27
@singjelly ARcore crashes on my g9500. I don't think it is caused by GMS as I have GMS on my s8 Hong Kong version. Adding to SupportedDevices.java is not going to help. I think we need an tango core update.

**Comment by inio** [comment] 2017-12-15 22:54
Duplicate of #89

**Comment by Naiqiuna** [comment] 2018-10-11 10:57
I built HelloAR with unity and the 1.5 SDK, and when it ran on the Galaxy S8 G9500, the app showed "Your hardware does not support this application,sorry!"However, version 1.2 can run normally. Is there any solution?thank you。

**Comment by inio** [comment] 2018-10-11 23:12
@Naiqiuna What's the build fingerprint of your device?  You can get it with `adb shell getprop ro.build.fingerprint`

**Comment by Naiqiuna** [comment] 2018-10-12 02:58
@inio The fingerprint is samsung/dreamqltezc/dreamqltechn:8.0.0/R16NW/G9500ZCU3CRI2:user/release-keys。

**Comment by inio** [comment] 2018-10-15 16:29
@Naiqiuna It sounds like you might be using an out of date Unity build.

Please post this issue to the [google-ar/arcore-unity-sdk issues board](https://github.com/google-ar/arcore-unity-sdk/issues) and include the version of the Unity Editor you're using..

**Closed by inio** 2018-10-15 16:29 UTC
Labels: duplicate
