### ISSUE TITLE
How to apply transparency from mtl file for particular texture in obj file in ar-core android?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#155] opened 2018-02-03 06:57 UTC
I have using ar-core sample. i have an issue in object rendering, transparency for particular texture not came in obj file.i was applying multiple textures for 3d object from mtl file.

Actual object is(This object rendered using arkit. transparency working perfectly in head of the object):
![img_0033](https://user-images.githubusercontent.com/13533279/35763944-f011b0b0-08dc-11e8-95a5-2e0e6cc0987e.jpg)

My ar-core sample object is(This object rendered using ar-core.transparency not came in head of the object) :
![screenshot_20180203-122024](https://user-images.githubusercontent.com/13533279/35763961-38ebcb72-08dd-11e8-9ade-5f6d3db39765.png)

**Comment by inio** [comment] 2018-02-04 01:54
ARCore is not a graphics engine - it is a system for providing 6DOF pose of an android device in and physically-reference danchors.

**Comment by inio** [comment] 2018-02-04 01:54
Duplicate of #52

**Closed by inio** 2018-02-04 01:54 UTC

**Comment by ArigarasuthanRepo** [comment] 2018-02-05 04:52
Do you provide scenekit like arkit ios for android in feature?.because its too hard to render object in opengl and rendering large vertices  with opengl take much time.
