### ISSUE TITLE
Support for S8 in Hong Kong

### ISSUE THREAD

**Issue by Ernie1998** [google-ar/arcore-android-sdk#319] opened 2018-04-17 19:45 UTC
Why there is no support of S8 (G9500) in Hong Kong? We can access Google here. 
Please add us to the list, don't leave us alone.
We can see ARCore apps in playstore, but can't install ARCore.
Thanks in advance.

**Comment by inio** [comment] 2018-04-18 02:25
Unfortunately, the G9500 contains restrictions on background processes that prevent ARCore from functioning properly.  Sorry.

Any ARCore apps you can see are not [declaring their ARCore requirement correctly](https://developers.google.com/ar/develop/java/enable-arcore#ar_required).

**Comment by inio** [comment] 2018-04-18 02:25
Duplicate of #255

**Closed by inio** 2018-04-18 02:25 UTC

**Comment by inio** [comment] 2018-05-08 20:55
@Ernie1998 [The just-released ARCore 1.2 APK](https://github.com/google-ar/arcore-android-sdk/releases/tag/v1.2.0) includes calibration data for the SM-G9500.  This device is not fully-supported (ARCore and apps will not be available from the Play Store), but with Hong Kong firmware it may be used for development.  Note: ARCore may not function properly with Chinese firmware.
