### ISSUE TITLE
CameraNotAvailableException in onResume

### ISSUE THREAD

**Issue by StevenOttoG** [google-ar/arcore-android-sdk#260] opened 2018-03-26 07:22 UTC
We see this exception sometimes in production and I think that's something that should be handled by ARCore directly (show a toast or something) instead of being thrown as a RuntimeException. Right now we got crashes from Galaxy S8s and Note 8s :

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity: com.google.ar.core.exceptions.CameraNotAvailableException
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3873)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3914)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3070)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6823)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

Caused by com.google.ar.core.exceptions.CameraNotAvailableException
       at com.google.ar.core.Session.throwExceptionFromArStatus(SourceFile:356)
       at com.google.ar.core.Session.nativeResume(SourceFile)
       at com.google.ar.core.Session.resume(SourceFile:165)
       at ourMainActivity.onResume
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1277)
       at android.app.Activity.performResume(Activity.java:7140)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3850)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3914)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3070)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6823)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
```

**Comment by inio** [comment] 2018-03-26 13:35
Duplicate of #261

**Comment by inio** [comment] 2018-03-26 13:37
There are cases where we fail to reopen the camera, and don't get much of a reason why.

We're working on getting better log capture into exceptions in the future to help diagnose this.

**Comment by devbridie** [comment] 2020-12-29 20:07
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.

**Closed by devbridie** 2020-12-29 20:07 UTC
Labels: known issue
