### ISSUE TITLE
Models are brocken on new ARCore 1.1 with OpenGL ES 3.0 with even simple obj

### ISSUE THREAD

**Issue by dementia2029** [google-ar/arcore-android-sdk#290] opened 2018-04-05 07:20 UTC
Hi,I open a new issue as the last one was closed without any investigation.
Your ARCore for Android Studio works only with andy.obj. I spent 2 weeks trying to render any another models.

I attached model with only 48123 vertices of "65k total supported". The rendering is broken. 

Guys fix your kit or remove it as it not working. I cant understand why you publish a product, that nobody cant to use. Your advices "go to unity" are stupid, as your work is to make work ARCore for Android Studio. Am I do something wrong? Open my model and look that model is not complicated.

[model.zip](https://github.com/google-ar/arcore-android-sdk/files/1878869/model.zip)
![image](https://user-images.githubusercontent.com/4173654/38352070-a580868a-38ba-11e8-831c-8a7f3f761c39.png)

**Comment by Marunizer** [comment] 2018-04-05 14:55
Hey, 

so I don't think ARCore is suppose to help you with rendering models, It's focus is environmental understanding/mapping, etc... 

The sample app just uses simple rendering using https://github.com/javagl/Obj.

The version used is 'de.javagl:obj:0.2.1', but I believe ever since ARCore used this library to sample rendering, they have updated to version 'de.javagl:obj:0.3.0' which supposedly fixes rendering for more complicated models. ( May or may not be your issue ). You just have to follow different steps.

I haven't really opted for this fix, instead I noticed that there was a certain pattern for models that worked.

When exporting your obj, If your file contains minimum :
   - g default
   - v # # #
   - vt # #
   - vn # # #
   - s #
   - f # # #

It should work fine with this. I think what made it or broke it for me was whether or not my model had smoothing groups (s line).

Hope this helps and I didn't feed you false information! 
If not, I would either look through prior issues regarding rendering, I think some had had your issue.
Or reach out to https://github.com/javagl/Obj since it's their stuff that's being used. (:

**Comment by dementia2029** [comment] 2018-04-05 15:33
Hi. I have used 0.3.1 snapshot.

**Comment by inio** [comment] 2018-04-05 17:00
@Marunizer wrote:
> so I don't think ARCore is suppose to help you with rendering models, It's focus is environmental understanding/mapping, etc...

Precisely.  Quoting from my response on your previous issue that I closed:

> ARCore's sample code is intended to demonstrate the capabilities of ARCore's motion tracking and scene understanding. It is not intended as a full engine.

Also, creases and texture seams can result in a model having many more vertices when exported as OBJ than is shown in a 3D modeling package.

**Comment by inio** [comment] 2018-04-05 17:00
Duplicate of #287

**Closed by inio** 2018-04-05 17:00 UTC

**Comment by dementia2029** [comment] 2018-04-05 17:33
Brilliant.

**Comment by inio** [comment] 2018-04-05 17:54
Also, your "48123" vertex model has 80782 unique position/normal/texcoord combinations, which is what matters.
