### ISSUE TITLE
why Does not support samsung s8 (SM-G9500) ?

### ISSUE THREAD

**Issue by zansbang** [google-ar/arcore-android-sdk#255] opened 2018-03-22 12:13 UTC
please add support!

**Comment by inio** [comment] 2018-03-22 14:16
Two reasons really:

1. We don't have a method for distributing ARCore in China right now (where the G950O is sold)
2. We were unable to acquire enough of these devices to build a calibration

**Comment by inio** [comment] 2018-03-22 14:17
Duplicate of #89

**Comment by inio** [comment] 2018-04-05 20:34
@geverk Would you mind checking the build fingerprint of the Hong Kong-purchased g9500?  `adb shell getprop ro.build.fingerprint`?

**Comment by geverk** [comment] 2018-04-09 00:52
@inio this is the result of the fingerprint check: samsung/dreamqltezh/dreamqltechn:7.0/NRD90M/G9500ZHU2AQL2:user/release-keys

hope its useful

**Comment by geverk** [comment] 2018-04-09 16:04
Sad to read that my Hon Kong phone is limited by China... but thanks for the information

**Comment by inio** [comment] 2018-04-09 18:25
@geverk That is odd!  I'll ask why we have that as listed, as it almost certainly doesn't work well (you likely need to restart the phone or reinstall ARCore after each use).

**Comment by geverk** [comment] 2018-04-09 18:39
Good to know! I was about to buy it...

**Comment by inio** [comment] 2018-04-09 18:57
I'll update this issue once I have a conclusive answer on the SM-G9508.  Working on acquiring one to double check my suspicions.

**Comment by inio** [comment] 2018-04-09 22:08
Sorry - bad news:  The listing of SM-G9508 was an error.  It has been fixed.

**Comment by fahad86** [comment] 2018-04-18 02:25
Is it the same case for S8 Plus SM-G9550 Hong Kong Variant. Running Oreo 8.0.0
Fingerprint: samsung/dream2qltezh/dream2qltechn:8.0.0/R16NW/G9550ZHU2CRD4:user/release-keys

**Comment by fahad86** [comment] 2018-04-18 02:50
FYI, though HK maybe small a lot of mobile gaming revenue comes from HK. And a lot of users use Samsung devices. So it's better that at least the HK variants are included :D 
https://newzoo.com/insights/rankings/top-100-countries-by-game-revenues/

**Comment by inio** [comment] 2018-04-18 02:56
@fahad86  We would love to support these devices (no extra calibration work needed), but unfortunately the operating system on Samsung *0 and *8 SKUs has a restriction on background processes that breaks ARCore.  It will work the first time, but after the background process is killed by the OS for inactivity it cannot be re-launched and new ARCore sessions cannot be created until the device is restarted or ARCore is reinstalled.

**Comment by fahad86** [comment] 2018-04-18 03:00
@inio I hate samsung for having such a fragmented ecosystem. Thanks for the info!

**Comment by inio** [comment] 2018-04-18 03:01
@fahad86 I will double check and see if I can get one of the HK roms flashed onto our G9500 and see if it has the background process rule, but I don't have high hopes.

**Comment by fahad86** [comment] 2018-04-18 03:09
@inio Thanks! That would be great.
FYI, hope this helps: https://www.sammobile.com/forum/threads/31245-S7-edge-G9350-china-to-hongkong/page3

**Comment by inio** [comment] 2018-04-18 03:10
@fahad86 Maybe.  One thing that would definitely help is knowing the exact build fingerprint of a HK rom.  `adb shell getprop ro.build.fingerprint` should display it.

**Comment by fahad86** [comment] 2018-04-18 03:13
@inio already in my previous comment but again here:
**samsung/dream2qltezh/dream2qltechn:8.0.0/R16NW/G9550ZHU2CRD4:user/release-keys**

**Comment by geverk** [comment] 2018-04-19 05:32
@fahad86 the most interesting about that is that in fact there is sm-g9500 for china and a different version for HK, my Hk testing phone seems to have the Chinese version of the firmware

**Comment by fahad86** [comment] 2018-04-19 06:29
@geverk from your fingerprint, looks like you are running the HK version of the firmware as it has the letters **ZH** in it (G9500**ZH**U2AQL2)
https://www.sammobile.com/firmwares/galaxy-s8-plus/SM-G9500/

**Comment by geverk** [comment] 2018-04-19 06:46
yes, that is right, the build number use the HK version but the phone baseband version use the G9500ZCU2AQL2, china version...

**Comment by inio** [comment] 2018-04-19 15:52
@geverk I'm now doubting my quick assessment that your device had China firmware.  I'm working with Samsung to figure out how to identify China vs. Hong Kong firmware for the G9500 and test ARCore with firmware that is definitely Hong Kong firmware.

**Comment by geverk** [comment] 2018-04-19 17:02
@inio thanks a lot for that! (I can't imagine what a pain should be working with all that fragmentation) I have already test our project in a friends corean phone and arcore is really great! I love the light estimation!

**Comment by inio** [comment] 2018-05-08 20:55
@geverk @fahad86 [The just-released ARCore 1.2 APK](https://github.com/google-ar/arcore-android-sdk/releases/tag/v1.2.0) includes calibration data for the SM-G9500.  This device is not fully-supported (ARCore and apps will not be available from the Play Store), but with Hong Kong firmware it may be used for development.  Note: ARCore may not function properly with Chinese firmware.

**Comment by inio** [comment] 2018-05-08 22:11
(whoops, hit the wrong button earlier)

**Closed** 2018-05-08 22:11 UTC
Labels: device support, duplicate, feature request

**Comment by inio** [comment] 2018-05-09 14:18
@fahad86 Maybe.  Being able to even turn on the S8 G9500 showed up VERY late in the release cycle and was a last-minute change.  I'm not sure if we did the S8+ G9550 at the same time.

**Comment by geverk** [comment] 2018-05-14 02:35
@inio seems that the progression of sported devices is growing fast! I have seen also that some Chinese devices have support now for all the models, like Xiaomi Mi Mix 2S or Huawei P20 Pro. So that mean that the problem with Samsung firmware block in China is not a legal limitation that will block arcore to come China? and as consequence of that we will see more devices in the future compatibles for China mainland?    Thanks again for your help!

**Comment by inio** [comment] 2018-05-14 19:57
@geverk There is a small technical issue that prevents ARCore from working on many devices distributed in China.  This is not a restriction on ARCore itself, just a side effect of the way ARCore works.

**Comment by kkirov00** [comment] 2018-06-11 00:47
I am with the HK Note 8 (SM -N9500). Have absolutely the same issue. First of all the ARCore is not available on Play Store, then many apps as well. So what I did was downloaded the ARCore from 3rd party app store and installed it. The available apps in Play Store worked perfectly fine. The ones that were not available I used the same procedure as with ARCore itself --> 3rd party app store and install. They also work. First I was on ARCore 1.1, now updated on 1.2.
Never had problems with the need to restart the device or reinstall the ARCore app.
Don't know what the real issue is, but it is definitely not hardware based.

**Comment by inio** [comment] 2018-06-11 21:07
We may be able to fix this at least in some cases with 1.3.  Stay tuned.

**Comment by fahad86** [comment] 2018-06-12 01:57
@inio would be good if 1.3 would be made available for us in the Play Store

**Comment by inio** [comment] 2018-06-12 18:17
@fahad86 That's the hope.  Right not we're just making sure there's no issues this could cause, since we can't enable it for just the non-China devices.

**Comment by hy-l** [comment] 2018-06-22 20:40
@inio
Hello,
You mentioned that the Chinese S8 has auto-killing feature, but I think it can be turned off easily by turning on 'auto run' in the Smart Manager for the specific apps. Doing so the system won't terminate any process of the app. At least this made 'Termux:API' work for me, which would be killed just like you said. But after enabled auto run, there are no any problems at all. 
So could you please do some confirmations on this? Thank you.

**Comment by inio** [comment] 2018-06-22 20:41
ARCore 1.3 (released yesterday) May now work on some Chinese variants of supported devices.

**Comment by hy-l** [comment] 2018-06-22 22:12
Yeah, I just saw it after posting the message. :)
I've installed it as a side-load app, then downloaded and installed Google Measure (apk) from a third-party source. Measure is now working without a single issue, even without turning on auto-run for ARCore. So I can confirm that it does work on my SM-G9500 (china mainland variant, nougat system), and the system hasn't killed it yet so far.
