### ISSUE TITLE
huawei nova3 

### ISSUE THREAD

**Issue by 544531645** [google-ar/arcore-android-sdk#555] opened 2018-09-07 07:35 UTC
![image](https://user-images.githubusercontent.com/15622364/45205032-97c59a80-b2b3-11e8-9452-fd07c3cceae5.png)

huawei nova3 chinese version phone if support arcore ?

**Comment by inio** [comment] 2018-09-07 18:44
ARCore support in China is a bit more involved than for the rest of the world.  For now Chinese variants of the the nova 3 and nova 3i are not supported.

**Comment by inio** [comment] 2018-09-07 18:45
Duplicate of #89

**Closed by inio** 2018-09-07 18:45 UTC
