### ISSUE TITLE
How to draw an object center position of the camera in ar-core in android?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#105] opened 2018-01-02 06:01 UTC
How can i draw the object center position of the camera instead of anchor position in android?

**Comment by robertjuh** [comment] 2018-01-02 09:00
Possible duplicate of: 
https://github.com/google-ar/arcore-android-sdk/issues/103

**Comment by hannesa2** [comment] 2018-01-02 12:45
@ArigarasuthanRepo you have a lot of common interesting questions. Please provide a example/fork when you are able to fulfill one of your question

**Comment by ArigarasuthanRepo** [comment] 2018-01-02 13:09
Ok Definitely.

**Comment by inio** [comment] 2018-01-02 20:29
I believe my response to #103 should cover this with a modified camera-relative pose.

**Closed by inio** 2018-01-02 20:29 UTC
