### ISSUE TITLE
ARCore with VR gradle integration issues

### ISSUE THREAD

**Issue by erikist** [google-ar/arcore-android-sdk#306] opened 2018-04-12 16:04 UTC
This is a continuation of #300 

...

Last comment I put in there provides a repo for reliable reproduction: 

I have this [repo](https://github.com/erikist/ar-core-with-vr-example-gradle-fault ) for reproducing the problem reliably. I have removed my old project and cloned this one down afresh and the exception is produced. Let me know if you have any problems with reproducing this. In case it matters for reproduction, I am using this version of AS:
```
Android Studio 3.1.1
Build #AI-173.4697961, built on April 3, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
```

**Comment by inio** [comment] 2018-04-12 17:02
Lets keep this on the original issue

**Comment by inio** [comment] 2018-04-12 17:02
Duplicate of #300

**Closed by inio** 2018-04-12 17:02 UTC
