### ISSUE TITLE
Why Pose supports only rigid transformation?

### ISSUE THREAD

**Issue by itanbp** [google-ar/arcore-android-sdk#342] opened 2018-04-29 10:55 UTC
Hi,
The documentation states that 
> public class Pose
Represents an immutable **rigid** transformation from one coordinate space to another.

Why the API supports only rigid transformation? Is it possible to add also `makeScale()` method, similar to `makeRotation()` and `makeTranslation()`?

In the sample app, there is a demonstration of how scale transformation can be achieved using Matrix multiplication... So can't this be an API method?

Thanks!

**Comment by inio** [comment] 2018-04-29 13:32
Our `Pose` type is designed for representing the position of real-world things, which in general do not scale or otherwise deform.  To allow applications to reason about these positions more easily it is represented as a structured transformation (separated translation and rotation) instead of a free-form matrix.

ARCore's sample code is intended to demonstrate the capabilities of ARCore's **motion tracking and scene understanding**. It is not intended as a full engine.

Consider using Unity or Unreal if you're looking for more engine-level capabilities, and keep an eye on #52.

**Comment by inio** [comment] 2018-04-29 13:33
Duplicate of #52

**Closed by inio** 2018-04-29 13:33 UTC
Labels: duplicate, feature request
