### ISSUE TITLE
"Tango Core Stopped" on Note 8

### ISSUE THREAD

**Issue by gak2** [google-ar/arcore-android-sdk#81] opened 2017-12-07 09:15 UTC
Getting this ARCore error on Samsung Galaxy Note 8 SM-N950FZKDBTU (Dual-SIM).

Any info on ARCore compatibility greatly appreciated!

Thanks

**Comment by Shad0X** [comment] 2017-12-11 22:34
same here :/

**Comment by syberpuppy** [comment] 2017-12-13 15:28
Same. Bought the note8 especially for ar. Very disappointing.

**Comment by inio** [comment] 2017-12-15 22:33
ARCore Developer Preview 2 is only *officially* supported on the Pixel phones and most models of the Samsung S8.  We're hard at work to support 100M devices with the launch of ARCore 1.0 (coming out of preview) in the coming months.

**Comment by inio** [comment] 2017-12-15 22:33
Duplicate of #89

**Closed by inio** 2017-12-15 22:33 UTC

**Comment by briwil** [comment] 2017-12-16 21:58
The Note 8 hasn't been supported on either preview of ArCore, why would you buy it for AR and then claim disappointment? Do your research ahead of time.

**Comment by gak2** [comment] 2017-12-17 15:41
Thank you for the response Ian!


Looking forward to 1.0 release.


________________________________
