### ISSUE TITLE
"This device does not support AR" - Samsung Galaxy S8+, ARCore 1.0

### ISSUE THREAD

**Issue by krzys-h** [google-ar/arcore-android-sdk#191] opened 2018-02-24 17:08 UTC
Hi!

I wanted to test the 1.0 release of ARCore but sadly it just displays "This device does not support AR". The previous beta preview worked fine. I installed ARCore from Google Play (it did show as compatible there). My device is on the [supported devices list](https://developers.google.com/ar/discover/#supported_devices).

Here is more exact specification of device params:
```
[ro.product.board]: [universal8895]
[ro.product.brand]: [samsung]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [dream2lte]
[ro.product.first_api_level]: [24]
[ro.product.locale]: [en-GB]
[ro.product.manufacturer]: [samsung]
[ro.product.model]: [SM-G955F]
[ro.product.name]: [dream2ltexx]
[ro.product_ship]: [true]

[ro.build.PDA]: [G955FXXU1ZQL8]
[ro.build.changelist]: [12690913]
[ro.build.characteristics]: [phone,emulator]
[ro.build.date]: [Wed Dec 13 19:16:30 KST 2017]
[ro.build.date.utc]: [1513160190]
[ro.build.description]: [dream2ltexx-user 8.0.0 OPR6 G955FXXU1ZQL8 release-keys]
[ro.build.display.id]: [OPR6.G955FXXU1ZQL8]
[ro.build.fingerprint]: [samsung/dream2ltexx/dream2lte:8.0.0/OPR6/G955FXXU1ZQL8:user/release-keys]
[ro.build.flavor]: [dream2ltexx-user]
[ro.build.host]: [SWDD6204]
[ro.build.id]: [OPR6]
[ro.build.official.release]: [true]
[ro.build.product]: [dream2lte]
[ro.build.scafe.version]: [2018A]
[ro.build.selinux]: [1]
[ro.build.selinux.enforce]: [1]
[ro.build.tags]: [release-keys]
[ro.build.type]: [user]
[ro.build.user]: [dpi]
[ro.build.version.all_codenames]: [REL]
[ro.build.version.base_os]: []
[ro.build.version.codename]: [REL]
[ro.build.version.incremental]: [G955FXXU1ZQL8]
[ro.build.version.preview_sdk]: [0]
[ro.build.version.release]: [8.0.0]
[ro.build.version.sdk]: [26]
[ro.build.version.security_patch]: [2017-12-01]
[ro.build.version.sem]: [2601]
[ro.build.version.sep]: [90000]
```

And here is a logcat output from trying to run the Java HelloAR sample:
```
02-24 17:54:26.127  5122  5884 I ActivityManager: START u0 {act=android.intent.action.MAIN typ=null flg=0x10200000 cmp=ComponentInfo{com.google.ar.core.examples.java.helloar/com.google.ar.core.examples.java.helloar.HelloArActivity}} from uid 10081
02-24 17:54:26.215  5531  5531 I native  : session_create.cc:71 ArSession_create with info: Entering
02-24 17:54:26.223  5531  5531 I native  : version_check.cc:23 ARCore APK version:1.0.180129103, SDK version: 1.0.0
02-24 17:54:26.223  5531  5531 I native  : session_create.cc:37 LoadDynamite with info: Dynamite load ok.
02-24 17:54:26.223  5531  5531 I native  : session_create_implementation.cc:467 Entering ArSession_createImplementation. ARCore SDK version: [1.0.0].
02-24 17:54:26.228  4225  4237 W native  : helpers.cc:913 Defaulting to persistent calibration file.
02-24 17:54:26.228  4225  4237 W native  : helpers.cc:890 Property calibration_cad is not defined.
02-24 17:54:26.231  4225  4237 E native  : device_profile_database_helpers.cc:134 Device profile for samsung/dream2ltexx/dream2lte:8.0.0/OPR6/G955FXXU1ZQL8:user/release-keys does not exist in /data/user/0/com.google.ar.core/files/device_profile_database
02-24 17:54:26.231  4225  4237 E native  : calibration_jni.cc:74 No device profile available for build fingerprint samsung/dream2ltexx/dream2lte:8.0.0/OPR6/G955FXXU1ZQL8:user/release-keys
02-24 17:54:26.235  5531  5531 E native  : session_create_implementation.cc:190 Device is not supported.
02-24 17:54:26.235  5531  5531 E native  : session_create_implementation.cc:486 Failed to create calibration provider
02-24 17:54:26.235  5531  5531 W native  : session_create_implementation.cc:487 ArSession_createImplementation returning ArStatusErrorSpace::AR_UNAVAILABLE_DEVICE_NOT_COMPATIBLE: .
02-24 17:54:26.247  5531  5531 E HelloArActivity: Exception creating session
02-24 17:54:26.247  5531  5531 E HelloArActivity: com.google.ar.core.exceptions.UnavailableDeviceNotCompatibleException
02-24 17:54:26.247  5531  5531 E HelloArActivity: 	at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:361)
02-24 17:54:26.247  5531  5531 E HelloArActivity: 	at com.google.ar.core.Session.nativeCreateSession(Native Method)
02-24 17:54:26.247  5531  5531 E HelloArActivity: 	at com.google.ar.core.Session.<init>(Session.java:100)
02-24 17:54:26.247  5531  5531 E HelloArActivity: 	at com.google.ar.core.examples.java.helloar.HelloArActivity.onResume(HelloArActivity.java:155)
02-24 17:54:26.247  5531  5531 E HelloArActivity: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1361)
02-24 17:54:26.247  5531  5531 E HelloArActivity: 	at android.app.Activity.performResume(Activity.java:7360)
02-24 17:54:26.247  5531  5531 E HelloArActivity: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3762)
02-24 17:54:26.247  5531  5531 E HelloArActivity: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3827)
02-24 17:54:26.247  5531  5531 E HelloArActivity: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3036)
02-24 17:54:26.247  5531  5531 E HelloArActivity: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
02-24 17:54:26.247  5531  5531 E HelloArActivity: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
02-24 17:54:26.247  5531  5531 E HelloArActivity: 	at android.os.Handler.dispatchMessage(Handler.java:105)
02-24 17:54:26.247  5531  5531 E HelloArActivity: 	at android.os.Looper.loop(Looper.java:164)
02-24 17:54:26.247  5531  5531 E HelloArActivity: 	at android.app.ActivityThread.main(ActivityThread.java:6972)
02-24 17:54:26.247  5531  5531 E HelloArActivity: 	at java.lang.reflect.Method.invoke(Native Method)
02-24 17:54:26.247  5531  5531 E HelloArActivity: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
02-24 17:54:26.247  5531  5531 E HelloArActivity: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by inio** [comment] 2018-02-26 19:12
Duplicate of #198

**Closed** 2018-02-26 19:12 UTC
Labels: bug, device support, fixed in upcoming release
