### ISSUE TITLE
How to add bump map to 3d object in ar-core sample android?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#266] opened 2018-03-27 12:07 UTC
Iam using ar-core android sample.I want to add bump mapping to the 3d object how can i do that in the android sample?

**Comment by inio** [comment] 2018-03-27 16:59
ARCore's sample code is intended to demonstrate the capabilities of ARCore's motion tracking and scene understanding. It is not intended as a full engine.

**Comment by inio** [comment] 2018-03-27 16:59
Duplicate of #52

**Closed by inio** 2018-03-27 16:59 UTC
Labels: feature request
