### ISSUE TITLE
Camera focus with arcore camera

### ISSUE THREAD

**Issue by deeppandya** [google-ar/arcore-android-sdk#200] opened 2018-02-27 20:20 UTC
Is there a way to focus camera using arcore camera ? I am working on an application where i need to put object using ARCore. and then i need to save the frames as an image.

**Comment by inio** [comment] 2018-02-27 21:36
Currently ARCore uses a fixed focus to ensure stable camera intrinsics.  We may introduce autofocus or focus control in the future.

**Comment by inio** [comment] 2018-02-27 21:36
Duplicate of #153

**Closed by inio** 2018-02-27 21:36 UTC

**Comment by fredsa** [comment] 2018-08-17 23:26
Autofocus was added in the 1.4.0 release.

**Comment by Attaullah123** [comment] 2018-09-04 06:57
Hi @fredsa,
I use 1.4.0 release of arcore but still auto focus is not working. Can you please suggest me class or method i need to call foe auto focusing
Thanks

**Comment by inio** [comment] 2018-09-05 00:05
@Attaullah123 are you turning on auto focus?  It needs to be enabled using `Config.setFocusMode()` and then reconfiguring the session.
