### ISSUE TITLE
A wacky crash while calling ArSession_create

### ISSUE THREAD

**Issue by wuzeqin** [google-ar/arcore-android-sdk#586] opened 2018-09-29 03:27 UTC
A wacky crash while calling ArSession_create. Here is a crash stack call trace snapshot 
![15381443739558](https://user-images.githubusercontent.com/9404871/46240284-929dcc00-c3d7-11e8-8471-b890e7ea0e50.jpg)
This crash suddenly occur to me in my Samsung SM-G9600 every time , I have no idea to deal with it. Please give me some advice to solve it. Thank you.

**Comment by inio** [comment] 2018-09-29 18:42
The fact that this suddenly started happening probably means it's related to the 1.5 update that released a few days ago.

Is there a logcat message generated by this crash?  Since it's entering an abort path I would suspect there is.

One thing that's suspicious is that this is coming from CheckThread.  Is it possible that you're not calling ArSession_create from the JNI thread?  If you have a vm object you can use AttachCurrentThread to get an env for another thread.

**Comment by inio** [comment] 2018-09-29 18:56
One thought: in particular check your logcat for the message "AssetManager has been finalized!".  This would indicate that this is actually #563 surfacing in a different way.

**Comment by inio** [comment] 2018-09-29 18:58
Actually, I'm going to assume that this is #563.  #584 has a crash with`art::ScopedCheck::CheckThread(_JNIEnv*)` on the stack and and "AssetManager has been finalized!".  Deduping both these issues into #563 and bumping internal priority,

**Comment by inio** [comment] 2018-09-29 18:59
Duplicate of #563

**Closed by inio** 2018-09-29 18:59 UTC
Labels: bug, documentation bug, question

**Comment by wuzeqin** [comment] 2018-09-30 07:52
Thank you for your advice inio.  I'm sure that calling ArSession_create from the JNI thread. And your assumption is correct, there really is a message “AssetManager has been finalized!” in logcat.  
 #588 find a certainly path lead to this crash in  the domestic edition(CN) Samsung S9 While running arcore official sample.
