### ISSUE TITLE
Rajawali Engine integration

### ISSUE THREAD

**Issue by Ketsuko** [google-ar/arcore-android-sdk#64] opened 2017-11-02 14:31 UTC
Hello everyone,

I've been working a little bit with the OpenGL SDK of Google ARCore, and was wondering, do you have any examples of integration of ARCore with the Rajawali engine? I've seen there are many example of Google Tango + ARcore, but not for Rajawali...

Thank you for your help!

**Comment by nathanmartz** [comment] 2017-11-14 16:32
We don't have any public examples yet, but it's not particularly difficult to do. Have you tried yet? If so, what issue did you run into?

**Comment by Ketsuko** [comment] 2017-11-20 12:47
Thank you for your answer. 

So basically, what I've done is : 
 - I have one GL Surface view with the ARCore OpenGL Renderer,
 - Above it, I've placed a Rajawali Texture view running the Rajawali renderer.

The camera in the Rajawali renderer get its position and orientation from the view matrix from the current frame of the AR session in the arcore example (I had to compute quaternions to do the orientation because there is no matrix input for rajawali).

My main problem is, I don't think this is a "clean" way to do it, because:
 - I have two renderer running on the same time... 
 - Besides, I have no clue for integrating the result of the hit test from arcore renderer to the rajawalie one

**Comment by hannesa2** [comment] 2018-01-02 12:44
@Ketsuko did you manged it. If yes, please can you provide a example/fork doing so ?

**Comment by niusounds** [comment] 2018-04-02 12:48
I created sample project!
https://github.com/ejeinc/HelloAR_Rajawali/tree/master

**Comment by inio** [comment] 2018-05-08 21:09
Duplicate of #52

**Closed by inio** 2018-05-08 21:09 UTC
Labels: feature request
