### ISSUE TITLE
Feature Request: Area Mapping and Area Map File Export

### ISSUE THREAD

**Issue by weinandt** [google-ar/arcore-android-sdk#156] opened 2018-02-04 01:50 UTC

**Comment by inio** [comment] 2018-02-04 01:52
I think it's unlikely we'll see direct equivalent of Tango-like mapping (with the map as an well-defined data structure that can be exported), but the desire for similar capabilities are definitely on our radar.

**Comment by inio** [comment] 2018-02-04 01:52
Duplicate of #94

**Closed by inio** 2018-02-04 01:52 UTC
