### ISSUE TITLE
How to take 3D image by TOF camera using ARCore?

### ISSUE THREAD

**Issue by mistrydarshan99** [google-ar/arcore-android-sdk#612] opened 2018-10-18 07:33 UTC
I have  Asus ZenFone AR (ZS571KL) which is tango supported. I have to capture 3D image using depth sensor of TOF camera. So how to achieve this kind of functionality using ARCore?

**Comment by inio** [comment] 2018-10-18 17:54
Duplicate of #120

**Closed by inio** 2018-10-18 17:54 UTC
