### ISSUE TITLE
Official Honk Kong Note 8 support (SM - N9500)

### ISSUE THREAD

**Issue by kkirov00** [google-ar/arcore-android-sdk#426] opened 2018-06-11 00:51 UTC
Please add official support. 
I am with the HK Note 8 (SM -N9500). Have absolutely the same issue as a guy with HK S9 has submitted few months ago. First of all the ARCore is not available on Play Store, then many apps as well. So what I did was downloaded the ARCore from 3rd party app store and installed it. The available apps in Play Store worked perfectly fine. The ones that were not available I used the same procedure as with ARCore itself --> 3rd party app store and install. They also work. First I was on ARCore 1.1, now updated on 1.2.
Never had problems with the need to restart the device or reinstall the ARCore app.
Don't know what the real issue is, but it is definitely not hardware based.

**Comment by inio** [comment] 2018-06-11 21:18
Duplicate of #89

**Closed by inio** 2018-06-11 21:18 UTC
