### ISSUE TITLE
Is it possible to add focus square marker like ARKit focus square marker in ar-core android ?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#142] opened 2018-01-24 12:26 UTC
i have working sample ar-core app.i want to add a focus square marker like ARkit focus square marker. inside of focus square marker i want to add object. is it possible to create a foucs square marker in ar-core android?

**Comment by inio** [comment] 2018-01-31 17:28
This is a higher level capability than we intend to provide with the core AR engine.  Engine integrations our our sample code may provide this sort of thing in the future.

**Comment by inio** [comment] 2018-01-31 17:31
Duplicate of #154

**Closed by inio** 2018-01-31 17:32 UTC
Labels: feature request

**Comment by ArigarasuthanRepo** [comment] 2018-02-01 05:29
Ok thank you.

**Comment by jayesh8585** [comment] 2019-10-07 12:24
Hello There,
We want the same kind of functionality but didn't get anywhere the proper solution and finally, we did it our custom focus square 
Please check below Link :

https://youtu.be/SbyB220KJqo

I hope you like it , It is done using ARcore

**Comment by ivstka95** [comment] 2019-10-07 12:29
> Hello There,
> We want the same kind of functionality but didn't get anywhere the proper solution and finally, we did it our custom focus square
> Please check below Link :
> 
> https://youtu.be/SbyB220KJqo
> 
> I hope you like it , It is done using ARcore

looks very cool, good job!
can you share your solution please?
also i noticed that you customized rendering of shadow under the object - how did you do this?

**Comment by chnouman** [comment] 2019-10-07 13:16
@jayesh8585 buddy you did a great thing can you share us some knowledge?

**Comment by jayesh8585** [comment] 2019-10-08 06:51
Thank you Guys 
I'm going to upload the package on the asset store within a few days 
will inform you
