### ISSUE TITLE
SharedCamera CameraCaptureSession.CaptureCallback.onCaptureStarted(...) callback is being called only once, instead of being called every frame

### ISSUE THREAD

**Issue by development-1000realities** [google-ar/arcore-android-sdk#1263] opened 2021-07-03 17:19 UTC
### SPECIFIC ISSUE ENCOUNTERED

When using SharedCamera, the CameraCaptureSession.CaptureCallback.onCaptureStarted(...) callback is being called only once, instead of being called every frame.

### VERSIONS USED
- Android Studio: 4.2.1
- ARCore SDK for Android: 1.24.0
- Device manufacturer, model, and O/S: Samsung S10, Samsung S20, Samsung S8
- Google Play Services for AR (ARCore):  1.25.211460203
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: samsung/beyond1lteeea/beyond1:11/RP1A.200720.012/G973FXXSBFUE6:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Start a shared camera session with TEMPLATE_RECORD and a repeating capture request while logging a message each time the onCaptureStarted callback is called.
 1. Filter logcat by said message.
 
Expected behavior:
 1. Message is printed when capturing of each video frame starts.

Actual behavior:
1. Message is printed only once, on the first frame.

**Comment by devbridie** [comment] 2021-07-09 09:33
I think this is intended behavior for `onCaptureStarted` when using the `TEMPLATE_RECORD` mode; see Android docs: ["a video recording start/stop sound"](https://developer.android.com/reference/android/hardware/camera2/CameraCaptureSession.CaptureCallback#onCaptureStarted(android.hardware.camera2.CameraCaptureSession,%20android.hardware.camera2.CaptureRequest,%20long,%20long)). This implies that for video recording, `onCaptureStarted` is called once (which is when the recording start sound should play).

**Comment by development-1000realities** [comment] 2021-07-11 19:26
Hi Dereck :)
Thanks for the reply but I dare to disagree, for 2 reasons:
1. The documentation of onCaptureStarted you have mentioned states "This method is called when the camera device has started capturing the output image for the request, at the beginning of image exposure". So this implies that when shooting video it will be called at the beginning of each video frame's exposure. Note that the method returns the frame's timestamps and frameNumber, which further reinforce this implication. I do agree that the documentation is not explicit enough re. behavior with repeating requests, however 
2. We are using this callback a lot with the regular android camera 2 API as well. So far when using TEMPLATE_RECORD, the onCaptureStarted callback is consistently called on each video frame across all devices we have had a chance to test with. Among others this includes: Samsung Galaxy S5, S7, S8, S9, S10, S20, Note 20, A31, LG Velvet, Google Pixel 1, Google Pixel 4, OnePlus 7, OnePlus 8, PocoPhone F1

**Comment by devbridie** [comment] 2021-07-12 15:27
Got it-- if that's the behavior camera2 supplies, I think ARCore's wrapped callback should do the same. Let me contact the responsible team here.

**Comment by devbridie** [comment] 2021-07-28 14:55
I think this should have been fixed in a server rollout; please let me know if that's not the case!

**Closed by devbridie** 2021-07-28 14:55 UTC
Labels: bug, fixed in upcoming release

**Comment by piotr-wojcik-1000realities** [comment] 2021-07-30 12:53
@devbridie Latest version of Google Play Services for AR is still 1.25.211460203 at the moment. We will let you know once it's updated.
Peter

**Comment by devbridie** [comment] 2021-07-30 13:07
Sorry, I wasn't completely clear-- the behavior may have been changed due to a server bit flip, as opposed to an update to Google Play Services for AR.
