### ISSUE TITLE
No ARcore support in Play Store after Samsung Galaxy A6+ (2018)

### ISSUE THREAD

**Issue by thangtmc73** [google-ar/arcore-android-sdk#557] opened 2018-09-08 03:37 UTC
Hi everyone,

My model number is Samsung Galaxy A6+ (2018) SM-A605G/DS. From this article, https://developers.google.com/ar/discover/supported-devices, why couldn't I download it from CHPlay? I got the message "Your device isn't compatible with this version"

Kindly regards,

**Comment by thangtmc73** [comment] 2018-09-08 03:50
Phone build fingerprint:
samsung/a6pltedx/a6plte:8.0.0/R16NW/A605GDXU2ARG2:user/release-keys

**Comment by inio** [comment] 2018-09-10 19:29
I don't see the A6+ on our supported device list, just the basic A6.  For other models where the + version is supported we seem to call it out.

**Comment by inio** [comment] 2018-09-10 19:29
Duplicate of #89

**Closed by inio** 2018-09-10 19:29 UTC
Labels: device support, duplicate, feature request

**Comment by RakeshRV1317** [comment] 2018-09-19 17:58
ARCORE is not supported on Samsung A6+...
Please add support..

**Comment by muntakim1** [comment] 2019-09-11 14:00
Why ARCORE is not supported on Samsung A6+??? 

please Add arcore support
