### ISSUE TITLE
ARcore support devices with Samsung note 8.

### ISSUE THREAD

**Issue by hvmien** [google-ar/arcore-android-sdk#126] opened 2018-01-12 03:26 UTC
Hello everyone.
I have problem about devices support with ARcore of google. 
Does arcore support on "Samsung Note8" device?
i'm sory about with my english.
Thanks you and best regard.

**Comment by inio** [comment] 2018-01-12 03:28
ARCore Developer Preview 2 is only supported on Google Pixel phones and select models of the Samsung S8.

Duplicate of #89

**Comment by inio** [comment] 2018-01-12 03:28
Duplicate of #89

**Closed by inio** 2018-01-12 03:28 UTC
