### ISSUE TITLE
How to find touch event of VirtualObject added

### ISSUE THREAD

**Issue by rramprasad** [google-ar/arcore-android-sdk#205] opened 2018-02-28 11:48 UTC
How to find touch event of VirtualObject added. I tried to use HitResult inside onDraw,but it detects only plane. What are the steps I need to do find click event on my 3D object? Is it any plan to add this functionality by default.Because most developers,repeat to raycast in their own way.But there is no proper document to do for this.

**Comment by inio** [comment] 2018-02-28 18:16
Developers looking for higher level capabilities like this and uncomfortable doing the math themselves should probably use the Unity or Unreal for now.

**Comment by inio** [comment] 2018-02-28 18:17
Duplicate of #52

**Closed by inio** 2018-02-28 18:17 UTC
