### ISSUE TITLE
[ARCore Samsung Galaxy A6+] not supported

### ISSUE THREAD

**Issue by MaxLovesAR** [google-ar/arcore-android-sdk#650] opened 2018-11-22 17:37 UTC
I would really like it if you released the ARCore for Samsung Galaxy A6+ (2018). I saw it was available for normal A6 but not A6+?... Please add A6+ to the supported list.

**Comment by Canato** [comment] 2018-11-29 13:04
They cannot "add" a cellphone. For the device be able to use ARCore it needs to come with many tests and mesures from manufactures. It include odometers, gyroscope, calibration etc. So is close to impossible for a mobile which is already out to became supported. Sorry =/

**Comment by inio** [comment] 2018-12-01 00:40
Duplicate of #89

**Closed by inio** 2018-12-01 00:40 UTC
