### ISSUE TITLE
HelloAR doesn't work on Zenfone AR

### ISSUE THREAD

**Issue by thcomp** [google-ar/arcore-android-sdk#298] opened 2018-04-09 06:42 UTC
I try to work HelloAR in ARCore SDK for Unity on Zenfone AR, but after this app is launched, "Searching for surfaces..." doesn't never hide and anything doesn't occurred.

My environment is followings.
Unity: 2017.4.0f1
ARCore SDK for Unity: v1.1.0
Have permissions for HelloAR: Camera and location

I notice following log is outputted, so it seems device cannot get pose.
native  : pose_manager.cc:56 GetRecentDevicePose failed. redwood::INVALID_ARGUMENT: Passed timestamp is too old. Latest VIO t:nan, latest IMU t:598365.123986, query t:575436.754061

Please help.

**Comment by inio** [comment] 2018-04-09 13:48
Duplicate of #183

**Comment by inio** [comment] 2018-04-09 13:49
Short version: There's a driver bug.  A counter rolls over and the camera start reporting bogus timestamps.  Restart the phone to fix.

**Closed by inio** 2018-04-09 13:49 UTC
Labels: bug, device support, known issue
