### ISSUE TITLE
Samsung Tab A 10.1 (2019) Support #912

### ISSUE THREAD

**Issue by sismoon2013** [google-ar/arcore-android-sdk#1061] opened 2020-06-04 07:07 UTC
### VERSIONS USED
- Android Studio: 
- ARCore SDK for Android: 
- Device manufacturer, model, and O/S: 
- ARCore: 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1.
 1.
 1.

**Comment by sismoon2013** [comment] 2020-06-04 07:07
Please send us some feedback about this issue.

**Comment by donalhunt** [comment] 2020-07-04 08:25
This is duplicate of Issue #912 I believe.

**Comment by donalhunt** [comment] 2020-07-04 08:36
Added to Issue #89. Please upvote comment there.

Repository owners: you can de-dupe this now.

**Closed** 2021-02-04 16:21 UTC
