### ISSUE TITLE
how to pick obj in arcore?

### ISSUE THREAD

**Issue by scolar** [google-ar/arcore-android-sdk#330] opened 2018-04-24 06:32 UTC
is frame.hitTest can pick obj in the scene?

**Comment by inio** [comment] 2018-04-24 17:59
ARCore's sample code is intended to demonstrate the capabilities of ARCore's motion tracking and scene understanding. It is not intended as a full engine, and things such as hit testing virtual objects are not included.

Consider using Unity or Unreal if you're looking for more engine-level capabilities, and keep an eye on #52.

**Comment by inio** [comment] 2018-04-24 17:59
Duplicate of #52

**Closed by inio** 2018-04-24 17:59 UTC
