### ISSUE TITLE
Will support more devices?

### ISSUE THREAD

**Issue by jonathan-bibas** [google-ar/arcore-android-sdk#93] opened 2017-12-19 12:55 UTC
I want to start learning ARCore but I need to know if it will work with other devices, even older devices

**Comment by kharalsuman007** [comment] 2017-12-19 15:23
ARCore currently built in sensors to track the planes and tracking the position of the mobile device as it moves, and building its own understanding of the real world. Unfortunately the older devices don't have this sensors . According to website ARCore is designed to work on a wide variety of qualified Android phones running N (Nougat) and later.

**Comment by inio** [comment] 2017-12-19 17:41
With the 1.0 launch in the coming months, support for enough models will be added to cover 100M devices in the field.  However, we can't talk about what specific devices will be added for 1.0 yet.

**Comment by inio** [comment] 2017-12-19 17:41
Duplicate of #89

**Closed by inio** 2017-12-19 17:41 UTC
