### ISSUE TITLE
How to Select a AR Object in ARCore  like as ARCamera in Google Pixel.

### ISSUE THREAD

**Issue by RajkumarRepo** [google-ar/arcore-android-sdk#135] opened 2018-01-19 04:57 UTC
I need to Select a AR Object  like as the ARCamera in Google Pixel phone to select the object that object only Scaling, Rotating etc...(I have handle the Scaling Rotation Functionality but i need to re-select a single object in ARCore)

Some More Brief  explanation I'm place Some of the AR Object in Real World (Like as Place the Bat and Ball on the Table . Bat size is ok but Ball size is Very Larger than Bat So I need to Select a Single Ball Object). How can i select a single object from already placed Object.

**Comment by inio** [comment] 2018-01-19 19:58
The ARCore API provides sufficient scene understanding data to implement these behaviors, but the actual implementation is up to developers.

**Comment by inio** [comment] 2018-01-19 19:59
Duplicate of #121

**Closed by inio** 2018-01-19 19:59 UTC

**Comment by inio** [comment] 2018-01-31 17:33
Duplicate of #154
