### ISSUE TITLE
wacky crash ArSession_Create on SM-G9600/DS

### ISSUE THREAD

**Issue by hello-david** [google-ar/arcore-android-sdk#588] opened 2018-09-30 06:45 UTC
We find a way :
Run demo->Install ARCore APK(1.5.1 Google Play)->Lock screen->Crash->Unintall ARCore.
Loop it always reproduce .

[democrash.txt](https://github.com/google-ar/arcore-android-sdk/files/2431313/democrash.txt)

**Comment by hello-david** [comment] 2018-09-30 06:50
we use this demo:  [](https://github.com/google-ar/arcore-android-sdk/tree/master/samples/hello_ar_java)

**Comment by hello-david** [comment] 2018-09-30 07:16
the fingerprint of this crash device is samsung/starqltezc/starqltechn:8.0.0/R16NW/G9600ZCU2ARF4:user/release-keys

**Comment by inio** [comment] 2018-09-30 23:36
This is a direct duplicate of #586 (with an amusingly similar title!) which is a new form of #563.  We're currently investigating this issue and if you can reproduce it reliably there's a code change mentioned on that thread I'd like tested.

**Comment by inio** [comment] 2018-09-30 23:36
Duplicate of #563

**Closed by inio** 2018-09-30 23:36 UTC

**Comment by inio** [comment] 2018-10-18 17:48
We've just released an update (1.5.1) with a minor improvement on this:  The crash some users started seeing in 1.5 should now be back to a FatalException during session create.  This update is available through the Play Store and can be downloaded on our [releases page](https://github.com/google-ar/arcore-android-sdk/releases).
