### ISSUE TITLE
Drift of anchored object

### ISSUE THREAD

**Issue by michaelvogt** [google-ar/arcore-android-sdk#492] opened 2018-07-18 05:15 UTC
Here is a walkaround of an object (of a house when finished) I want to place on the ground. When returning to the starting point, there is a drift of several meters. What would be your recommendation to reduce this drift?

https://photos.app.goo.gl/ykDvzZfrHCSHcmPz8

Not complaining here. Just want to get a feeling if ARCore should generally be able to handle such a usage, or if the ground just doesn't provide enough features for ARCore to work with.

I know the placement as such of the object needs correction. That is a completely different problem.

**Comment by inio** [comment] 2018-07-23 21:04
It seems like ARCore never was able to reference the tracked features at the end of the path back to what it was seeing at the beginning.  I believe if you moved back to the original location by the sign, the loop closure logic would have kicked in and it would have snapped back to the original location.  At that point, walking around the same path again should have produced pretty much zero drift.

**Comment by michaelvogt** [comment] 2018-08-02 05:01
Problem is, I can't demand the tourists to walk at a specific path. So, I need to manage to prevent the drift in the first place. 

Looking through the video, I don't think that I moved the phone too fast during the walk around to cause drift. So is the problem that the ground looks too much the same most of the time? 

Is there a possibility, or would it make sense, to have a diagnose tool like arcoreimg but for video, that outputs when there aren't enough unique feature points to understand how ARCore handles certain areas in terms of motion tracking quality?

**Comment by inio** [comment] 2018-08-03 21:33
Cloud anchors would be a better solution for this type of application, but the 24-hour limitation probably prevents them from working here (you'd need to either have an operator walk around and collect each morning or rely on people using your app often enough to keep a fresh set of cloud anchors).

**Comment by michaelvogt** [comment] 2018-08-05 03:56
Yes, having a usable cloud solution for this would be very welcome. The current 24h limit makes it completely unusable for usages like these.

From my point of view, cloud anchors (or an AR cloud in general) would be welcome because I could place objects around the user without any interaction from his side (after his position was recognized).

Does your suggestion mean, that cloud anchors are also potentially more stable for usages like this? What is the difference? The fact that the area exists already as a point cloud?

**Comment by inio** [comment] 2018-08-06 18:51
Cloud anchors have two advantages here:

1. They are based on visual features over a much larger area than just a sign, and thus provide better constraints on orientation and (to a lesser degree) position.
2. They can exist in unstructured contexts.  You could create cloud anchors continuously as an operator walks around the area, and then localize to all of those cloud anchors in the user experience.

**Comment by michaelvogt** [comment] 2018-08-09 06:30
Thanks for you explanation. 
As I already said, point 2 is very much impossible to accomplish. I definitely don't see any possibility to get this accepted by any tourist organisation I am in contact with. For my case, cloud anchors are a non feature with the current conditions.

Just in case you'd like some numbers: mountainous area (500ha), transport routes (about 26km), walking routes in main area (several km). All at one world heritage registered site.

I know and accept (in a way) that ARCore isn't meant for this kind of usage right now. As it seems anchors can't provide the kind of location stability I need, so I hope there will be a feasible usage model for my usecase soon.

**Comment by michaelvogt** [comment] 2018-08-17 05:49
Also watching #523

**Comment by camilorodriguezapriorins** [comment] 2018-08-22 14:26
Hi guys

Our team has been having the same issue. We have been working during the last months in an ARcore application with Unity. We have had the drift problem during all this time. We tried to fixed it with some kind of recalibration using augmented images but it is not enough for our purposes yet. We would really appreciate to know if google is planning to fix this in a near future or if definitely it is something the developers will have to deal with because in that case it is possible that we have to stop our development because the clients needs are really critical.

**Comment by csp54321** [comment] 2018-08-22 15:53
We are having the same "object drift" issues. Is this a feature of ARCore or are we doing something wrong, or is Google planning to fix this? Or better yet, can someone tell us how to guarantee that our objects won't drift. 

Our app places "node markers" on pieces of equipment in a room. The node info comes from a backend DB vis WS call.

The nodes markers are essentially labels that contain data about each piece of equipment and display the data when tapped. The markers/labels must not drift around, as you can imagine, that could cause some real confusion to miss-label a piece of equipment.

Any insight would be appreciated. Is there anyway to get ahold of someone at Google to discuss?

**Comment by inio** [comment] 2018-09-05 23:26
Regarding the original request, I think this really falls under #94, to which #523 would be a partial solution.  The other cases of drift discussed here seem to more be a case of #528.

**Comment by inio** [comment] 2018-09-05 23:26
Duplicate of #94

**Closed** 2018-09-05 23:26 UTC
Labels: question
