### ISSUE TITLE
Larger size obj files were rendering slowly how can i render large size obj fast like arkit?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#252] opened 2018-03-21 07:48 UTC
Iam using android ar-core samples.Rendering large size obj's slowly, any solution to  render large size obj's fast.i have 90 mb obj file its rendered perfectly but it can take so much time to render.

**Comment by inio** [comment] 2018-03-21 15:15
ARCore's sample code is intended to demonstrate the capabilities of ARCore's motion tracking and scene understanding.  It is not intended as a full engine.

**Comment by inio** [comment] 2018-03-21 15:15
Duplicate of #52

**Closed by inio** 2018-03-21 15:15 UTC

**Comment by ArigarasuthanRepo** [comment] 2018-03-22 04:43
when will be intended to full engine like scenekit?

**Comment by ArigarasuthanRepo** [comment] 2018-03-22 05:09
Then how can i render large size obj's (50mb) fastly.Any idea to render obj fastly?

**Comment by inio** [comment] 2018-03-22 13:59
For now, I suggest using Unity.  Watch for updates on #52 for details on a possible google engine.
