### ISSUE TITLE
please add support for xiaomi note 8 pro please

### ISSUE THREAD

**Issue by dulajdanu** [google-ar/arcore-android-sdk#953] opened 2019-11-28 15:55 UTC
please add ar core support for xiaomi note 8 pro please

**Comment by harowosegbe** [comment] 2019-12-24 16:41
Please Add Xiaomi Note 8 pro

**Comment by sandyfriend** [comment] 2020-02-14 07:49
#89

**Comment by sandyfriend** [comment] 2020-02-14 07:49
Duplicate of #89

**Closed by sandyfriend** 2020-02-14 07:49 UTC

**Comment by call0fcode** [comment] 2020-03-30 11:06
It works now. This version in APKMirror did the trick:

[Google Play Services for AR 1.16.200302046 (arm64-v8a + arm-v7a) (Android 7.0+)](https://www.apkmirror.com/apk/google-inc/arcore/arcore-1-16-20030204-release/google-play-services-for-ar-1-16-200302046-android-apk-download/)

Don't forget to uninstall any installed previous version of the app (also delete its data).

**Comment by harowosegbe** [comment] 2020-03-30 12:45
Finally, it works! Thank you @call0fcode
