### ISSUE TITLE
Moto G6 play not supporting AR Core		

### ISSUE THREAD

**Issue by vishugrover** [google-ar/arcore-android-sdk#534] opened 2018-08-20 10:53 UTC
![screenshot_20180820-153428](https://user-images.githubusercontent.com/29191800/44336512-4df84a00-a495-11e8-95af-42b6d745a303.png)

I am trying to run ar core sample project "hello_ar_java" and it is giving me "this device is not supported". Whereas Moto G6 play is present in the list of supported devides for AR Core and when I try to install ar core from play store, It says "device is not compatible with this version". Below are the logs from the sample app

`08-20 15:40:01.487 16325-16325/? I/zygote: Late-enabling -Xcheck:jni
08-20 15:40:01.774 16325-16343/com.google.ar.core.examples.java.helloar D/OpenGLRenderer: HWUI GL Pipeline
08-20 15:40:01.818 16325-16343/com.google.ar.core.examples.java.helloar I/Adreno: QUALCOMM build                   : 3273d9c, I0b59f3a7cf
    Build Date                       : 02/27/18
    OpenGL ES Shader Compiler Version: EV031.22.00.01
    Local Branch                     : 
    Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.6.5.R1.08.00.00.312.044
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
08-20 15:40:01.828 16325-16343/com.google.ar.core.examples.java.helloar I/Adreno: PFP: 0x005ff087, ME: 0x005ff063
08-20 15:40:01.832 16325-16343/com.google.ar.core.examples.java.helloar I/OpenGLRenderer: Initialized EGL, version 1.4
08-20 15:40:01.832 16325-16343/com.google.ar.core.examples.java.helloar D/OpenGLRenderer: Swap behavior 2
08-20 15:40:02.017 16325-16325/com.google.ar.core.examples.java.helloar I/ARCore-InstallService: Install service connected
08-20 15:40:02.030 16325-16339/com.google.ar.core.examples.java.helloar E/ARCore-InstallService: The device is not supported.
08-20 15:40:02.624 16325-16330/com.google.ar.core.examples.java.helloar I/zygote: Do partial code cache collection, code=31KB, data=21KB
08-20 15:40:02.626 16325-16330/com.google.ar.core.examples.java.helloar I/zygote: After code cache collection, code=31KB, data=21KB
    Increasing code cache capacity to 128KB
08-20 15:40:09.189 16325-16339/com.google.ar.core.examples.java.helloar W/ARCore-InstallService: requestInstall = -5, launching fullscreen.
08-20 15:40:17.193 16325-16342/com.google.ar.core.examples.java.helloar E/BpSurfaceComposerClient: Failed to transact (-1)
08-20 15:40:17.194 16325-16342/com.google.ar.core.examples.java.helloar E/BpSurfaceComposerClient: Failed to transact (-1)
08-20 15:40:17.250 16325-16330/com.google.ar.core.examples.java.helloar I/zygote: Do partial code cache collection, code=62KB, data=56KB
08-20 15:40:17.252 16325-16330/com.google.ar.core.examples.java.helloar I/zygote: After code cache collection, code=60KB, data=55KB
    Increasing code cache capacity to 256KB
08-20 15:40:17.275 16325-16325/com.google.ar.core.examples.java.helloar E/HelloArActivity: Exception creating session
    com.google.ar.core.exceptions.UnavailableUserDeclinedInstallationException
        at com.google.ar.core.InstallActivity.finish(Unknown Source:2)
        at com.google.ar.core.InstallActivity.onResume(Unknown Source:28)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1376)
        at android.app.Activity.performResume(Activity.java:7088)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3711)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3776)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1684)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6673)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)`

`08-20 17:17:08.993 4487-4487/com.google.ar.core.examples.java.helloar E/HelloArActivity: Exception creating session
    com.google.ar.core.exceptions.UnavailableDeviceNotCompatibleException
        at com.google.ar.core.Session.throwExceptionFromArStatus(Unknown Source:144)
        at com.google.ar.core.Session.nativeCreateSession(Native Method)
        at com.google.ar.core.Session.<init>(Unknown Source:22)
        at com.google.ar.core.examples.java.helloar.HelloArActivity.onResume(HelloArActivity.java:134)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1376)
        at android.app.Activity.performResume(Activity.java:7088)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3711)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3776)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1634)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6673)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)`

**Comment by inio** [comment] 2018-08-23 15:37
Could you please provide a build fingerprint?  Run `adb shell getprop ro.build.fingerprint` to get it.

**Comment by cesarGimenez** [comment] 2018-09-12 22:14
Same problem here, I'm afraid the device is not listed!

https://developers.google.com/ar/discover/supported-devices

**Comment by inio** [comment] 2018-09-12 22:31
@cesarGimenez Thanks for catching that.  The "moto g⁶ **play**" is not a supported device.

**Comment by inio** [comment] 2018-09-12 22:31
Duplicate of #89

**Closed by inio** 2018-09-12 22:31 UTC
Labels: device support, feature request
