### ISSUE TITLE
Will galaxy s9 sm-g9600/ds get arcore support?

### ISSUE THREAD

**Issue by flankechen** [google-ar/arcore-android-sdk#380] opened 2018-05-15 13:02 UTC
Will galaxy s9 sm-g9600/ds(Hong kong version), which holds a 845 soc, get arcore support?
Thanks!

**Comment by inio** [comment] 2018-05-15 22:45
Duplicate of #89

**Closed by inio** 2018-05-15 22:45 UTC
Labels: device support

**Comment by flankechen** [comment] 2018-05-16 01:49
Thanks, 
but will there be a ARcore app from play store available update for hong kong version?

**Comment by flankechen** [comment] 2018-05-16 02:08
just check that hello_ar_c sample build and install success, but running requiring arcore and redirect me to play store, which says device not supported.
what does "side-loading for development only" mean?

**Comment by ocedalv** [comment] 2018-05-17 14:11
It is worth noting that these variants (SM-G9600 and SM-G9650) are also sold in Latin America, including Mexico. It is no longer exclusive to Hong Kong and China.

S9+ build.prop:
`
# begin build properties
# autogenerated by buildinfo.sh
ro.build.id=R16NW
ro.build.display.id=R16NW.G9650ZHU2ARC6
ro.build.version.incremental=G9650ZHU2ARC6
ro.build.version.sdk=26
ro.build.version.preview_sdk=0
ro.build.version.codename=REL
ro.build.version.all_codenames=REL
ro.build.version.release=8.0.0
ro.build.version.security_patch=2018-03-01
ro.build.version.base_os=
ro.build.version.security_index=1
ro.build.date=Fri Mar 23 21:24:31 KST 2018
ro.build.date.utc=1521807871
ro.build.type=user
ro.build.user=dpi
ro.build.host=SWDD5708
ro.build.tags=release-keys
ro.build.flavor=star2qltezh-user
ro.build.ab_update=false
ro.product.model=SM-G9650
ro.product.brand=samsung
# ro.build.product is obsolete; use ro.product.device
ro.build.product=star2qltechn
ro.product.name=star2qltezh
ro.product.device=star2qltechn
# ro.product.cpu.abi and ro.product.cpu.abi2 are obsolete,
# use ro.product.cpu.abilist instead.
ro.product.cpu.abi=arm64-v8a
ro.product.cpu.abilist=arm64-v8a,armeabi-v7a,armeabi
ro.product.cpu.abilist32=armeabi-v7a,armeabi
ro.product.cpu.abilist64=arm64-v8a
ro.product.manufacturer=samsung
ro.product.locale=en-GB
ro.wifi.channels=
# Do not try to parse description, fingerprint, or thumbprint
ro.build.description=star2qltezh-user 8.0.0 R16NW G9650ZHU2ARC6 release-keys
ro.build.fingerprint=samsung/star2qltezh/star2qltechn:8.0.0/R16NW/G9650ZHU2ARC6:user/release-keys
ro.build.characteristics=default
# Samsung Specific Properties
ro.build.PDA=G9650ZHU2ARC6
ro.build.official.release=true
ro.config.rm_preload_enabled=1
ro.build.changelist=13087568
ro.product_ship=true
ro.chipname=SDM845
# end build properties

#
# HWUI_BUILD_PROPERTIES
#
ro.hwui.texture_cache_size=88
ro.hwui.layer_cache_size=58
ro.hwui.path_cache_size=16
ro.hwui.texture_cache_flushrate=0.4
ro.hwui.shape_cache_size=4
ro.hwui.gradient_cache_size=2
ro.hwui.drop_shadow_cache_size=6
ro.hwui.r_buffer_cache_size=8
ro.hwui.text_small_cache_width=1024
ro.hwui.text_small_cache_height=1024
ro.hwui.text_large_cache_width=4096
ro.hwui.text_large_cache_height=2048
#
# from device/samsung/star2qltechn/system.prop
#
#
# system.prop for sdm845
#

DEVICE_PROVISIONED=1

debug.sf.hw=0
debug.egl.hw=0
debug.sf.latch_unsignaled=1

#debug.composition.type=c2d
#persist.hwc.mdpcomp.enable=true
debug.mdpcomp.logs=0
debug.sf.enable_hwc_vds=1
dalvik.vm.heapsize=36m
dev.pm.dyn_samplingrate=1
persist.demo.hdmirotationlock=false

#ro.hdmi.enable=true
#persist.speaker.prot.enable=false
qcom.hw.aac.encoder=true
#
# system props for the cne module
#
persist.cne.feature=1

#system props for the MM modules
media.stagefright.enable-player=true
media.stagefright.enable-http=true
media.stagefright.enable-aac=true
media.stagefright.enable-qcp=true
media.stagefright.enable-fma2dp=true
media.stagefright.enable-scan=true
mmp.enable.3g2=true
media.aac_51_output_enabled=true
mm.enable.smoothstreaming=true
#13631487 is decimal sum of supported codecs in AAL
#codecs:(PARSER_)AAC AC3 AMR_NB AMR_WB ASF AVI DTS FLV 3GP 3G2 MKV MP2PS MP2TS MP3 OGG QCP WAV FLAC AIFF APE DSD
mm.enable.qcom_parser=13631487
persist.mm.enable.prefetch=true

#
# system props for the data modules
#
# [SDM845] SECRIL Support DPM and QOS - Do not use Qcom Netmgrd
#ro.use_data_netmgrd=true
#persist.data.netmgrd.qos.enable=true
persist.data.mode=concurrent

#system props for time-services
persist.timed.enable=true

#
# system prop for opengles version
#
# 196610 is decimal for 0x30002 to report version 3.2
ro.opengles.version=196610

# disable updatableopengl
ro.gfx.driver.0=
ro.zygote.disable_gl_preload=false

# system property for maximum number of HFP client connections
bt.max.hfpclient.connections=1

# System property for cabl
ro.qualcomm.cabl=1

#Simulate sdcard on /data/media
#
persist.fuse_sdcard=true

#system prop for Bluetooth SOC type
qcom.bluetooth.soc=cherokee

#system prop for wipower support
ro.bluetooth.emb_wp_mode=true
ro.bluetooth.wipower=true

#
#snapdragon value add features
#
ro.qc.sdk.audio.ssr=false

##fluencetype can be "fluence" or "fluencepro" or "none"
ro.qc.sdk.audio.fluencetype=none
persist.audio.fluence.voicecall=true
persist.audio.fluence.voicerec=false
persist.audio.fluence.speaker=true

#system prop for RmNet Data
persist.rmnet.data.enable=true
persist.data.wda.enable=true
persist.data.df.dl_mode=5
persist.data.df.ul_mode=5
persist.data.df.agg.dl_pkt=10
persist.data.df.agg.dl_size=4096
persist.data.df.mux_count=8
persist.data.df.iwlan_mux=9
persist.data.df.dev_name=rmnet_usb0

#property to enable user to access Google WFD settings
persist.debug.wfd.enable=1
##property to choose between virtual/external wfd display
persist.sys.wfd.virtual=0

# enable tunnel encoding for amrwb
tunnel.audio.encode = true

#Buffer size in kbytes for compress offload playback
audio.offload.buffer.size.kb=32

#Enable offload audio video playback by default
av.offload.enable=true

#enable voice path for PCM VoIP by default
use.voice.path.for.pcm.voip=true

# system prop for NFC DT
ro.nfc.port=I2C

#enable dsp gapless mode by default
audio.offload.gapless.enabled=true

#initialize QCA1530 detection
sys.qca1530=detect

#hwui properties
ro.hwui.texture_cache_size=72
ro.hwui.layer_cache_size=48
ro.hwui.r_buffer_cache_size=8
ro.hwui.path_cache_size=32
ro.hwui.gradient_cache_size=1
ro.hwui.drop_shadow_cache_size=6
ro.hwui.texture_cache_flushrate=0.4
ro.hwui.text_small_cache_width=1024
ro.hwui.text_small_cache_height=1024
ro.hwui.text_large_cache_width=2048
ro.hwui.text_large_cache_height=1024

config.disable_rtt=true

#Bringup properties
debug.gralloc.gfx_ubwc_disable=0
persist.sys.force_sw_gles=1
persist.radio.atfwd.start=false
ro.kernel.qemu.gles=0
sdm.debug.disable_scalar=0
qemu.hw.mainkeys=0
sdm.debug.disable_inline_rotator=1
sdm.debug.disable_display_ubwc_ff_voting=1
sdm.debug.prefersplit=1
sdm.debug.disable_dest_scalar=1
sys.disable_ext_animation=1

# Disable ConsumerIR
config.disable_consumerir=true

# read DS/SS property
import /efs/factory.prop
ro.multisim.simslotcount=2

#Status of softsim
persist.sys.softsim.status=default,default
persist.sys.softsim.netmode=3g

# IOP memory leak fix
iop.enable_prefetch_ofr=1

#min/max cpu in core control
ro.vendor.qti.core_ctl_min_cpu=2
ro.vendor.qti.core_ctl_max_cpu=4

#verified samsung camera vendor key by sep cts
ro.vendor.camera.sep_cts.verified=false

#
# ADDITIONAL_BUILD_PROPERTIES
#
ro.product.first_api_level=26
ro.build.version.sem=2601
ro.build.version.sep=90000
ro.treble.enabled=true
ro.build.selinux=1
persist.sys.dalvik.vm.lib.2=libart.so
dalvik.vm.isa.arm64.variant=kryo300
dalvik.vm.isa.arm64.features=default
dalvik.vm.isa.arm.variant=cortex-a9
dalvik.vm.isa.arm.features=default
ro.config.knox=v30
ro.config.tima=1
ro.config.timaversion=3.0
ro.config.iccc_version=3.0
ro.config.dmverity=true
ro.config.kap_default_on=true
ro.config.kap=true
ro.config.ifaaversion=2
ro.kernel.qemu=0
net.bt.name=Android
dalvik.vm.stack-trace-file=/data/anr/traces.txt
ro.expect.recovery_id=0xe1b548eb344af1507b5646bf40c2c0527b0b4ce5000000000000000000000000

`
