### ISSUE TITLE
The project progress so slowly

### ISSUE THREAD

**Issue by hanhailong** [google-ar/arcore-android-sdk#37] opened 2017-09-21 15:27 UTC
The project progress so slowly？It's almost one month no update maintenance

**Comment by lvonasek** [comment] 2017-09-21 17:03
There will be probably update of ARcore together with new Pixel device. So expect it on 4.10.

**Comment by Ernie1998** [comment] 2017-10-05 05:30
@Ivonasek AR stickers… no words on supporting new devices.

**Comment by lvonasek** [comment] 2017-10-05 06:36
Yep, I think that ARcore team has some serious problem they cannot handle. I feel kidded by Google (again)

**Comment by MTRNord** [comment] 2017-10-05 10:04
Uhm this is still just a Demo it isn't yet full public. This repo propablly is just a mirror and will not see any Updates in Realtime (ps I am not related to the Google Team or Google)

**Comment by janerivi** [comment] 2017-10-12 12:45
Please be slightly more incremental! 1.0 launch date is not provided so we have massive uncertainty regarding adressable devices. This could be reduced and developer investment could go up if Google incrementally added support for devices that ought to be able to support ARCore (like S8+).

**Comment by drewpts** [comment] 2017-10-15 19:39
Will ARCore team provide support for older devices? What about 2015-2016' Samsung S series?

**Comment by inio** [comment] 2017-12-15 22:26
With the release of Developer Preview 2, we've gotten much closer to what we hope to ship as ARCore 1.0. We're hard at work to support 100M devices with the launch of ARCore (coming out of preview) in the coming months.

We can't promise any specific features for 1.0 or beyond at this time, but we're hard at work on exciting stuff, so keep your eyes out for announcements throughout 2018.

**Comment by inio** [comment] 2017-12-15 22:27
Duplicate of #27

**Closed by inio** 2017-12-15 22:27 UTC
