### ISSUE TITLE
Add support for Razer Phone 2 (coming minecraft earth)

### ISSUE THREAD

**Issue by enux85** [google-ar/arcore-android-sdk#932] opened 2019-10-30 15:11 UTC
add ARcore for razer phone 2 support, RP2 is really fast app and great grapichs

**Comment by BPMOmega** [comment] 2019-11-26 00:29
Seconded.

**Comment by popit42** [comment] 2019-12-10 21:30
Thirded.  I love my Razer phone, it's clear the hardware is there and Minecraft Earth and FNAF:AR look fantastic, so I would love to be able to play them on my favourite phone.

**Comment by Sliicy** [comment] 2019-12-17 07:18
4th, add Razer Phone 2.

**Comment by Thebombuknow** [comment] 2020-02-06 01:13
5th, Razer Phone 2 is faster than the Pixel 3a, yet the 3a supports ARCore and the Razer Phone 2 doesn't.

**Comment by sandyfriend** [comment] 2020-02-14 07:57
Duplicate of #89

**Closed by sandyfriend** 2020-02-14 07:57 UTC
