### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by 544531645** [google-ar/arcore-android-sdk#71] opened 2017-11-17 06:07 UTC
before you answer "You can already get the camera image data via Session.getCameraTextureName(). We will not be able to expose full control of the camera while ARCore is running as that would lead to poor tracking quality in many cases"  but I not find this , only have setCameraTextureName

**Comment by nathanmartz** [comment] 2017-11-17 06:10
Closing as this is a dupe of #70 and I already replied there.

**Closed by nathanmartz** 2017-11-17 06:10 UTC
