### ISSUE TITLE
is it possible to create marker at air like a plan in a surface in ar-core android sdk? 

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#133] opened 2018-01-18 14:25 UTC
Iam using ar-core android sample i want to create marker in air like a plane in surface,when i touch the marker the object should be create inside marker.how can i do that?

**Comment by inio** [comment] 2018-01-18 15:17
Duplicate of #110

**Closed by inio** 2018-01-18 15:17 UTC
