### ISSUE TITLE
Crash on initialization(LG G6)

### ISSUE THREAD

**Issue by randrievskiy** [google-ar/arcore-android-sdk#601] opened 2018-10-11 13:44 UTC
It's a duplicate of https://github.com/google-ar/arcore-android-sdk/issues/542 but I can't re-open 542 issue.
 I have following fingerprint
lge/lucye_global_com/lucye:8.0.0/OPR1.170623.032/18222140635ac:user/release-keys
and exact the same error is reproducible from time to time(it can happens 3-4 times in a row). And it always happens on startup
I use ArFragment from Sceneform SDK with some minor changes(without them error is present too)

 ```
override fun getSessionConfiguration(session: Session?): Config {
    val config = Config(session)
    config.focusMode = Config.FocusMode.AUTO
    config.cloudAnchorMode = Config.CloudAnchorMode.ENABLED
    return config
  }

  override fun onWindowFocusChanged(hasFocus: Boolean) {
    //workaround to avoid fullscreen mode
  }
```
Failed to calculate clock offset: generic::deadline_exceeded: Clock check duration [5.313us] out of bounds

**Comment by inio** [comment] 2018-10-11 22:54
Duplicate of #542

**Closed by inio** 2018-10-11 22:54 UTC
