### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libarcore_sdk_c.so" not found

### ISSUE THREAD

**Issue by candyman15** [google-ar/arcore-android-sdk#851] opened 2019-08-30 02:32 UTC
### VERSIONS USED
- Android Studio: 3.5.1
- ARCore SDK for Android: 1.10.0
- Device manufacturer, model, and O/S: Galaxy S8
- ARCore: 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1. Sometimes, arcore make crash because "Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libarcore_sdk_c.so" not found" . But it's not always. 

it occur that arcore make 'session' 
But as 'Try - catch'  it can't block.

I use arcore sdk for java.
 

please help me.

**Comment by c4software** [comment] 2019-11-29 20:13
Hi,

I have the same issue, I download the AR part of my app with « Dynamic Delivery », and the first time I start the application my application crash with `dlopen failed: library "libarcore_sdk_c.so"` when I restart the application it's working as intended. 

Someone has fixed this problem ?

**Comment by maltezc** [comment] 2020-04-23 21:44
Has anyone fixed this problem yet? It is occurring on every ARCode project I try.

**Comment by marclus49049** [comment] 2020-11-20 12:43
Has anyone found a solution for this. I found out when I'm creating a session in my app bundle app it crashes cause of this error. I even tried passing a newContext with info about the newly installed module and ApplicationContext but dint work.

**Comment by jinglebiscuitsHL** [comment] 2021-01-19 22:07
Same issue happening to me with version 1.22.0 and 1.16.0.

**Comment by devbridie** [comment] 2021-02-04 16:53
Here's some troubleshootings steps:

1. Determine your device's abi architecture: `adb shell getprop ro.product.cpu.abi`
2. Figure out which native ABIs your APK is shipping using [the APK analyzer](https://developer.android.com/studio/build/apk-analyzer). The ABIs your APK ships are listed in `libs`.

![image](https://user-images.githubusercontent.com/442644/106926615-8e092100-6711-11eb-8df3-8203f7875190.png)

If the native library for your ABI is missing in your APK, you'll get the `UnsatisfiedLinkError`. If you're using ABI splits, ensure that the correct ABI is being bundled in your split.

I'm closing this one due to age, but if this is still a problem, please open a new issue with the relevant information.

**Closed by devbridie** 2021-02-04 16:53 UTC

**Comment by jinglebiscuitsHL** [comment] 2021-02-04 18:59
I found that whenever this crash happened in ARCore, there was also another dependencies that was seeing the same error first.
The suggestion to check the apk is good, but I always experience this from building and running from Android Studio. Also, the app can restart and work successfully with ARCore after the first crash without redeploying.

I haven't seen the crash in any production environments, so it might just be some weird behavior with Android Studio and debuggable builds.
