### ISSUE TITLE
Why larger size obj files not rendering properly in ar-core sample android?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#136] opened 2018-01-22 08:24 UTC
Iam working ar-core sample in android.in this sample large size obj files not rendered properly,i have 49MB obj file with mtl file and textures its not rendered properly.only smaller size obj files were rendered.

**Comment by inio** [comment] 2018-01-22 11:26
Duplicate of #73

**Closed by inio** 2018-01-22 11:26 UTC

**Comment by javagl** [comment] 2018-02-10 13:31
@inio This seems to be a recurring issue. I sketched a `ComplexObjectRenderer` class in https://github.com/javagl/Obj/issues/4#issuecomment-356424533 that could resolve this. It is structurally *very* similar to the `ObjectRenderer` class. It basically creates multiple `ObjectRenderer` instances internally, one for each part. It is only a first shot, and I cannot properly test it, because I don't have an AR-capable device, but maybe someone wants to add something like this to the ARCore demo. 

("Off-Topic": As an alternative to OBJ, you could consider https://github.com/KhronosGroup/glTF - but I'm still working on an Android renderer for that, and the PBR is not so trivial to implement, so this might still take some time...)

**Comment by ArigarasuthanRepo** [comment] 2018-02-12 08:37
Thank you for the response. i have already saw your solution and i have fixed large obj file rendering issue @javagl
