### ISSUE TITLE
Asus Zenfone AR support

### ISSUE THREAD

**Issue by lvonasek** [google-ar/arcore-android-sdk#58] opened 2017-10-26 15:15 UTC
1) Will be Asus Zenfone AR supported this year?
2) Will the device keep Tango functionality?

**Comment by lvonasek** [comment] 2017-11-29 21:31
Thank you for ignoration ARcore team!!!

To sum up answers I collected:
1) it won't be ready this year
2) it will work side-by-side with Tango
3) it won't have depth sensor support
4) Asus and Google will meet at court
5) if you need depth sensor then switch to iOS (and wait more than one year)

**Comment by inio** [comment] 2017-12-15 22:37
ARCore Developer Preview 2 is only officially supported on the Pixel phones and most models of the Samsung S8.  We're hard at work to support 100M devices with the launch of ARCore 1.0 (coming out of preview) in the coming months.

With the announcement of ARCore Developer Preview 2, we've also announced that we’re turning down support of Tango.

**Comment by inio** [comment] 2017-12-15 22:37
Duplicate of #89

**Closed by inio** 2017-12-15 22:37 UTC

**Comment by PersonalAR** [comment] 2018-01-01 14:36
Damn Google and damn Asus. They have to do arcore support for tango devices, albeit if without the ability to work with these two technologies. Let there be at least just an arcore

**Comment by inio** [comment] 2018-01-31 17:45
@lvonasek @PersonalAR [Good news!](https://developers.google.com/tango/) We've announced that "ZenFone AR will work with ARCore".

**Comment by lvonasek** [comment] 2018-02-01 08:05
Great, @inio can you please update your answer here: https://github.com/google-ar/arcore-android-sdk/issues/120 ? Thank you

**Comment by unityIDlilia** [comment] 2018-02-06 12:28
Will work or working already? Can i try ARCore apps on  ZenFone AR or not? if not then when?

**Comment by inio** [comment] 2018-02-08 00:24
Will work with the next release.

**Comment by jonomacd** [comment] 2018-02-23 17:00
Will it include support for the depth sensor?

**Comment by sniejadlik** [comment] 2018-02-28 13:24
It is not working.  It publishes and runs, but there is no surface detection our point cloud

**Comment by sniejadlik** [comment] 2018-02-28 13:28
@jonomacd it's not looking like it.  Looks like standard hardcore.  Ie tango API with a name change and depth removed

**Comment by sniejadlik** [comment] 2018-02-28 13:28
Arcore

**Comment by inio** [comment] 2018-02-28 13:31
@sniejadlik That sounds a lot like #183.  You'll probably see logcat messages like

> Received image measurement before corresponding IMU measurement [*two very different numbers*]

If so, restarting the phone should fix it for now.  We're working on a permanent fix.

**Comment by sniejadlik** [comment] 2018-02-28 13:37
https://i.imgur.com/fhBbRTy.jpg

Doesn't matter how long I scan for.  No points detected and no surfaces showing up

**Comment by inio** [comment] 2018-02-28 13:41
@sniejadlik If it's the same issue as #183, you'll need to restart the phone for it to work.  The timestamps for either the camera or IMU data have rolled over and don't match up with the other.

**Comment by sniejadlik** [comment] 2018-02-28 15:10
That works thanks.  

Sadly the frame rate is choppy and no where as smooth compared to the pixel or to any of my tango apps on this device.

**Comment by inio** [comment] 2018-02-28 18:21
@sniejadlik Do any of the sample apps (Hello AR) have a disappointing frame rate?    We'll try to repro here if you let us know which one.

**Comment by sniejadlik** [comment] 2018-02-28 18:29
Yes the HelloAR app is much choppier on the ASUS vs the Pixel XL.

**Comment by inio** [comment] 2018-02-28 18:33
Which flavor?

**Comment by sniejadlik** [comment] 2018-02-28 18:46
Unity package
