### ISSUE TITLE
[device support]Huawei P20 Pro HWCLT Compatibility

### ISSUE THREAD

**Issue by littleylv** [google-ar/arcore-android-sdk#664] opened 2018-12-06 03:57 UTC
Hi.

I see that `P20 Pro` is on the [supported-devices](https://developers.google.com/ar/discover/supported-devices) list. Several weeks ago some of my users said that `P20 Pro` with model `HWCLT` can not download app from google play which said `not compatibility`. Then I go to my Google Play -> Device Catalog and go into `P20 Pro` and see `HWCLT` is not supported but `HW-01K` is supported. That's OK. 

Now `HWCLT` has been supported according to Google Play -> Device Catalog from last week. But user of my still can not download app from google play, still saying `not compatibility`. Why.

Thank you.

**Comment by AJoensuu** [comment] 2018-12-06 22:08
@littleylv Support for some Huawei devices was temporarily pulled a few weeks ago because of an issue preventing tracking. The ARCore app and apps using ARCore are not currently listed in Play Store. The issue is fixed in ARCore v1.6 which is now available here in releases. I assume that it will return to Play Store shortly.

**Comment by inio** [comment] 2018-12-06 22:47
The 1.6 release (and actually any version of ARCore) is not yet visible for all P20 devices. Over the next few days it should become available and fix this issue. Please watch #585 for updates.

**Comment by inio** [comment] 2018-12-06 22:47
Duplicate of #585

**Closed by inio** 2018-12-06 22:47 UTC

**Comment by littleylv** [comment] 2018-12-07 01:42
@AJoensuu @inio  Thank your for your kindly reply.

**Comment by littleylv** [comment] 2018-12-10 02:12
@inio  Just another question. Is `Samsung Galaxy Note8 greatqltechn SM-N9500` the same as `P20` ? Will it be available soon? Thanks.

**Comment by SalvatoreMeschini** [comment] 2019-02-28 11:06
This is what I found in my Logcat (P20 Pro Dual SIM: **CLT-L29**):

02-28 11:56:07.393 I/native (19540): device_profile_database_helpers.cc:419 Found nothing for UUpC5W
02-28 11:56:07.393 I/native (19540): device_profile_database_helpers.cc:419 Found nothing for CLT-L29/HWCLT_accelerometer-lsm6dsm_OFILM
02-28 11:56:07.393 I/native (19540): device_profile_database_helpers.cc:419 Found nothing for J1ASAV
02-28 11:56:07.393 I/native (19540): device_profile_database_helpers.cc:419 Found nothing for HWCLT_accelerometer-lsm6dsm_OFILM
02-28 11:56:07.393 I/native (19540): device_profile_database_helpers.cc:419 Found nothing for ioG7OZ
02-28 11:56:07.393 I/native (19540): device_profile_database_helpers.cc:419 Found nothing for CLT-L29
02-28 11:56:07.393 I/native (19540): device_profile_database_helpers.cc:421 Could not locate device profile for HUAWEI/CLT-L29/HWCLT_accelerometer-lsm6dsm_OFILM:9/HUAWEICLT-L29/195C432R1:user/release-keys
02-28 11:56:07.393 E/native (19540): calibration_jni.cc:184 No device profile available for build fingerprint HUAWEI/CLT-L29/HWCLT_accelerometer-lsm6dsm_OFILM:9/HUAWEICLT-L29/195C432R1:user/release-keys
02-28 11:56:07.395 E/native (19487): session_create_implementation_shared.cc:870 Unable to obtain device profile from the content provider: generic::not_found: Device is not supported.
02-28 11:56:07.395 E/native (19487): session_create_implementation.cc:108 Failed to create calibration provider.
02-28 11:56:07.395 W/native (19487): session_create_implementation.cc:109 ArSession_createWithSettingsImplementation_private returning ArStatusErrorSpace::**AR_UNAVAILABLE_DEVICE_NOT_COMPATIBLE**: .

**Comment by SalvatoreMeschini** [comment] 2019-03-04 10:49
ARCore version:
Packages:
versionName=1.7.190128066
Hidden system packages:
versionName=0

Device fingerprint:
**HUAWEI/CLT-L29/HWCLT:9/HUAWEICLT-L29/195C432R1:user/release-keys**

That build fingerprint looks different from what is retrieved by ARCore:

Could not locate device profile for **HUAWEI/CLT-L29/HWCLT_accelerometer-lsm6dsm_OFILM:9/HUAWEICLT-L29/195C432R1:user/release-keys**
02-28 11:56:07.393 E/native (19540): calibration_jni.cc:184 No device profile available for build fingerprint **HUAWEI/CLT-L29/HWCLT_accelerometer-lsm6dsm_OFILM:9/HUAWEICLT-L29/195C432R1:user/release-keys**
02-28 11:56:07.395 E/native (19487): session_create_implementation_shared.cc:870 Unable to obtain device profile from the content provider: generic::not_found: Device is not supported.
