### ISSUE TITLE
Can you add support for HTC devices： U11，U11 plus

### ISSUE THREAD

**Issue by nope8** [google-ar/arcore-android-sdk#229] opened 2018-03-08 09:41 UTC

**Comment by inio** [comment] 2018-03-09 22:30
Maybe.

**Comment by inio** [comment] 2018-03-09 22:30
Duplicate of #89

**Closed by inio** 2018-03-09 22:30 UTC
Labels: device support, feature request

**Comment by Tegzek** [comment] 2019-06-23 06:47
Just add damn support lol

**Comment by lvidal1** [comment] 2019-08-07 15:25
Any updates on this?

**Comment by broken-bytes** [comment] 2019-08-12 03:54
@lvidal1 HTC is near to death unfortunately. 
I don't think support will ever happen.
I'm on HTC u11+ and from a developers point of view I really regret going with HTC,

**Comment by lvidal1** [comment] 2019-08-14 02:55
@broken-bytes It is a pity that the current history of HTC is being an obstacle to using the components that HTC has in their phones, which are adequate to support augmented reality technology.
I also understand that supporting a cell phone brand that is about to disappear, from the development point of view, could mean little benefit. However, there is still a large group of developers who have this phone and cannot buy another phone but still wish, like me, to be able to use ARCore just to develop.
On the other hand, I understand that certain configurations within cell phone components such as camera calibrations should be taken into account if this phone brand is supported.

**Please, I would like to know if there is any way to enable ARCore manually. It is frustrating it is disabled to test this type of technology by the hardware barrier.**
