### ISSUE TITLE
Exception running helloAR_java on Samsung S8 SM-G950F

### ISSUE THREAD

**Issue by yuguitao** [google-ar/arcore-android-sdk#187] opened 2018-02-24 03:35 UTC
Android: 7.0
ARCore ( download from google playstore): Version 1.0.180129103
Exception popup: " This device does not support AR   DISMISS"

**Comment by inio** [comment] 2018-02-26 19:18
Duplicate of #198

**Closed** 2018-02-26 19:21 UTC
Labels: bug, device support, fixed in upcoming release

**Comment by yuguitao** [comment] 2018-03-08 07:32
fingerprint:    samsung/dreamltexx/dreamlte:7.0/NRD90M/G950FXXU1AQL1:user/release-keys
I try the latest ARCore : 1.0.180129153
It still not work.
