### ISSUE TITLE
 Compatibility problem with huawei p20

### ISSUE THREAD

**Issue by xtornet** [google-ar/arcore-android-sdk#642] opened 2018-11-13 08:29 UTC
In the page of compatible devices (https://developers.google.com/ar/discover/supported-devices) figure that the huawei p20 (EML-L09) is compatible but at the time of downloading the application I get that it is not compatible, why is this?

**Comment by NTrixner** [comment] 2018-11-13 13:57
I also have this issue, and when I brute force 1.4, my application (which was running fine on Friday) doesn't find any planes anymore on my p20 pro.
This sucks since it's my bachelor thesis and I wanted to submit it tomorrow, but I don't have a different device for testing.

**Comment by xtornet** [comment] 2018-11-13 14:37
I do not understand anything, I bought a p20 because I said it was compatible, and it turns out that it is not compatible

**Comment by rodcibils** [comment] 2018-11-13 15:15
you checked what sensors has the phone? I understand that not all the devices has full compatibility, that depends on hardware

**Comment by xtornet** [comment] 2018-11-13 17:26
According to the web (arcore) this device is compatible but when downloading the app, it says no

**Comment by xtornet** [comment] 2018-11-13 17:26
very rare

**Comment by rodcibils** [comment] 2018-11-13 18:32
Yes, that's a fact. But it is known that not all devices has the same compatibility, and one of the main reasons is the hardware.

https://gadgets.ndtv.com/huawei-p20-4690
https://gadgets.ndtv.com/huawei-p20-pro-4691

In this link you can see that P20 in particular doesn't have gyro, magnetometer, etc. The P20 pro have more sensors, but is not really clear what are needed in particular for each specific feature of ARCore.

The main advantage Arkit have is that Apple knows exactly what hardware include in their phones, and that's the main reason for the short supported devices list for ARCore.

**Comment by xtornet** [comment] 2018-11-13 19:38
on the compatible devices page if it says it's compatible

**Comment by rodcibils** [comment] 2018-11-14 11:12
I know man, i'm sorry. Blame the guy who wrote that list, or blame Google

**Comment by inio** [comment] 2018-11-14 17:59
A recent OS update for the Huawei P20 device family has resulted in some devices experiencing poor motion tracking performance.  To minimize bad user experiences, we have temporarily disabled access to ARCore and AR-Required apps on the affected devices.

We are evaluating a workaround for this issue in ARCore V1.6, which should be released in the coming weeks.  We hope to re-enable all affected devices at that time.

**Comment by xtornet** [comment] 2018-11-14 18:03
ok that explains it all thanks for the answer

**Comment by calmmycode** [comment] 2018-12-05 13:33
Cant stop waiting for release with bugfix.

**Comment by LazerFX** [comment] 2018-12-05 21:57
Thanks for the details on this - is there an approximate release date for this?  My wife has just got a P20 (standard) and we were going to try out the JPL Spacecraft AR but it's not compatible...

**Comment by inio** [comment] 2018-12-06 22:41
Today's release of ARCore 1.6 should resolve this issue.  Please let us know if it does not.

**Closed by inio** 2018-12-06 22:41 UTC
Labels: bug, device support, fixed in upcoming release

**Comment by inio** [comment] 2018-12-06 22:46
Correction, the 1.6 release (and actually *any* version of ARCore) is not yet visible for all P20 devices.  Over the next few days it should become available and fix this issue.  Please watch #585 for updates.

**Comment by inio** [comment] 2018-12-06 22:46
Duplicate of #585

**Comment by raul1991** [comment] 2019-07-04 17:27
Mine is a P20 lite and the arcore is updated to the latest version yet when I press "view it your space" option it says - Unable to create AR session.
