### ISSUE TITLE
Does HUAWEI nova 3e support ARCore?

### ISSUE THREAD

**Issue by wuzeqin** [google-ar/arcore-android-sdk#565] opened 2018-09-17 13:01 UTC
![qq20180917-205756](https://user-images.githubusercontent.com/9404871/45624359-bcdcb900-babc-11e8-82de-4286fb20ead2.png)
No device profile available for build fingerprint HUAWEI/ANE-AL00/HWANE_accelerometer-kx023_null:8.0.0/HUAWEIANE-AL00/165(C00):user/release-keys
    session_create_implementation_shared.cc:493 Device is not supported.

**Comment by inio** [comment] 2018-09-17 18:51
Sorry, but our [Supported Devices page](https://developers.google.com/ar/discover/supported-devices) lists only the **nova 3** and **nova 3i**.

**Comment by inio** [comment] 2018-09-17 18:51
Duplicate of #89

**Closed by inio** 2018-09-17 18:51 UTC
