### ISSUE TITLE
Shared camera session

### ISSUE THREAD

**Issue by youaresoomean** [google-ar/arcore-android-sdk#239] opened 2018-03-14 06:50 UTC
Our application also needs access to the cameras of the device via the camera2 api. Is there any way to still use ARCore and share the camera? Currently ARCore bails out with AR_ERROR_CAMERA_NOT_AVAILABLE. 
Using ARCore to control the camera is no option in this case.
Thanks for any hints

**Comment by inio** [comment] 2018-03-14 18:53
At the moment, this is not possible.

**Comment by inio** [comment] 2018-03-14 18:53
Duplicate of #153

**Closed by inio** 2018-03-14 18:53 UTC
Labels: feature request
