### ISSUE TITLE
Detecting Veritical Surfaces (Walls) using ARCore

### ISSUE THREAD

**Issue by TheMachineHere** [google-ar/arcore-android-sdk#47] opened 2017-10-10 20:27 UTC
Hi, 

ARCore can effectively detect horizontal surfaces. I was curious to know whether anyone has found a way to detect vertical surfaces. My app is basically trying to detect various walls and augment objects on walls.

Has anyone found any solution?

Thanks.

**Comment by nathanmartz** [comment] 2017-10-10 20:57
Closing as dupe of https://github.com/google-ar/arcore-unity-sdk/issues/31

**Closed by nathanmartz** 2017-10-10 20:57 UTC

**Comment by inio** [comment] 2017-12-15 22:59
Duplicate of #18
