### ISSUE TITLE
frame.acquireDepthImage().getHeight() sometimes returns a wrong value

### ISSUE THREAD

**Issue by agGitHub** [google-ar/arcore-android-sdk#1093] opened 2020-07-28 16:49 UTC
### SPECIFIC ISSUE ENCOUNTERED

I develop an app  based on hello_ar_java app (using Depth API).

Somewhere in my code, i have:

```
 Image depthImage = frame.acquireDepthImage();
 depthMapWidth = depthImage.getWidth(); // gives always 160
 depthMapHeight = depthImage.getHeight(); // gives usually 90 but sometimes the wrong value of 120
```

depthImage.getHeight() should always return 90 on my Samsung S10+ but it returns sometimes 120. 

Anybody else has this problem ? Is it possible to fix it ? Thanks for your help !

- ARCore: 
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`

```
Packages:
    versionName=1.18.200603086
Hidden system packages:
    versionName=0
Active APEX packages:
Inactive APEX packages:
Factory APEX packages:
```

- Output of `adb shell getprop ro.build.fingerprint`: 
`samsung/beyond2lteeea/beyond2:10/QP1A.190711.020/G975FXXS7CTF3:user/release-keys`

### STEPS TO REPRODUCE THE ISSUE

Random.

### WORKAROUNDS (IF ANY)

No workaround found. Random bug. May happen several times in sequence even after restart of the app or phone.

### ADDITIONAL COMMENTS

Note that I also have the bug here: https://github.com/google-ar/arcore-android-sdk/issues/1085
I don't know if there might be a link.

**Comment by devbridie** [comment] 2020-07-30 15:51
I can't reproduce it on my device, but I'll pass it on to the team. Is it always the same dimensions in a given session, or do the demensions switch within the same session?

**Comment by agGitHub** [comment] 2020-07-30 21:32
@devbridie I think that the value doesn't change in a given session. Thanks for your help on this topic.

**Comment by devbridie** [comment] 2020-07-31 16:39
We're working on clarifying documentation on this, but the dimensions of the depth image can differ from device to device. I'll close this as working-as-intended.

**Comment by agGitHub** [comment] 2020-08-01 09:06
@devbridie The dimensions change between sessions on the SAME device. I think that is not the expected behavior!

**Comment by devbridie** [comment] 2020-08-05 17:52
Checked in with the team-- we can't seem to reproduce this behavior on this device. If you could provide a log dump and a test application, we could look into it further.

Thanks.

**Comment by agGitHub** [comment] 2020-09-22 07:35
Hi. I have now this very weird problem on my Samsung S20+. Suddenly, after weeks of dev, depthMapWidth and depthMapHeight are incorrect. The values should be 160x90 but now I get 640x360... It seems that I get these wrong values systematically. I changed nothing in my code. Perhaps it happened after updating ARCore from 1.18 to 1.19 inGradle ; but when I come back to 1.8, the bug doesn't disappear.

Restarting my phone didn't solve the problem.

This bug is totally crazy. Please help solving this issue that occurs on both my S10+ (randomly?) and S20+ (systematically now?).

Thanks a lot.

**Comment by devbridie** [comment] 2020-09-23 14:35
After some quick discussion, I don't believe this is a bug: [Frame.acquireDepthImage()](https://developers.google.com/ar/reference/java/com/google/ar/core/Frame#acquireDepthImage()) is explicit in not guaranteeing an image size, so that better resolutions may be offered in the future (which is probably what has happened with your device).

**Comment by agGitHub** [comment] 2020-10-20 09:43
Now I suddenly have randomly a depth map size of 120x160 instead of 90x160 on my Samsung S20+... So, when I do:

`  int depthSample = shortDepthBuffer.get(index); `

I get a OutOfBounds exception...

This problem drives me crazy!

**Closed** 2021-06-11 14:39 UTC
Labels: needs info
