### ISSUE TITLE
What would google have to do to create a a new device calibration.. to support a new device?

### ISSUE THREAD

**Issue by janerivi** [google-ar/arcore-android-sdk#51] opened 2017-10-12 12:40 UTC
There are very few supported devices. And we have no info on when to expect 1.0

How about adding support for devices in increments until  the 1.0 launch?

For example:
I would assume there isn't a huge difference in device specs between Samsung S8 and S8+

I bought an S8+ because it had a more powerful processor and someone wrote in an article that ARCore was supported on S8+ (wich was wrong).

I assume it would not take that many hours for an employee at google to setup the device calibrations for S8+ when there already is one for S8. I assume it might have something to do with stuff like lens distortion parameters for the lens in S8+ wich may differ slightly from the S8. Are my assumptions correct or is there much more to it?

Best regards..

**Comment by rohit1231** [comment] 2017-10-21 21:38
Hey 
follow this https://github.com/tomthecarrot/arcore-for-all
I tested it and works fine.

cheers

**Comment by janerivi** [comment] 2017-10-23 07:54
@rohit1231  I tested it as well. It worked for the s8+, but not "fine"... Planes and anchors tended to have severe drift issues. In my best guess this is due to missing config for the camera optics.

**Comment by rohit1231** [comment] 2017-10-24 12:47
yes, even I noticed this. the anchor point plane just floats and disappears. Even I feel that it's because of missing calibration information. Google engineer have worked exclusively with Samsung in order to get s8 calibrated.

**Comment by inio** [comment] 2017-12-15 22:32
Certifying a device for ARCore require a large amount of calibration work looking at the camera geometry and behavior, IMU behavior, relative position of the two, and most critically the relative timing of the two.

ARCore Developer Preview 2 is only officially supported on the Pixel phones and most models of the Samsung S8.  We're hard at work to support 100M devices with the launch of ARCore 1.0 (coming out of preview) in the coming months.

**Comment by inio** [comment] 2017-12-15 22:32
Duplicate of #89

**Closed by inio** 2017-12-15 22:32 UTC
