### ISSUE TITLE
how can set the camera resolution?

### ISSUE THREAD

**Issue by crisiscain** [google-ar/arcore-android-sdk#331] opened 2018-04-24 08:45 UTC
I got camera image from ArFrame_acquireCameraImage(),but the picture`s resolution is only 640*480. how can i get higher definition image?

**Comment by inio** [comment] 2018-04-24 18:00
Currently CPU image access is limited to the 640x480 image used for motion tracking.

**Comment by inio** [comment] 2018-04-24 18:00
Duplicate of #92

**Closed by inio** 2018-04-24 18:00 UTC
Labels: duplicate, feature request
