### ISSUE TITLE
VirtualObject (setOnTouchListener or setOnClickListener ) Android Studio

### ISSUE THREAD

**Issue by Ahmednagyyy** [google-ar/arcore-android-sdk#328] opened 2018-04-23 15:44 UTC
Hello, 

I tried every way to do some interaction with my virtual object ( touch or click then do something )
I want to know how to do this ?

**Comment by inio** [comment] 2018-04-23 17:55
ARCore's sample code is intended to demonstrate the capabilities of ARCore's motion tracking and scene understanding. It is not intended as a full engine, and things such as hit testing virtual objects are not included.

Consider using Unity or Unreal if you're looking for more engine-level capabilities, and keep an eye on #52.

**Comment by inio** [comment] 2018-04-23 17:55
Duplicate of #52.

**Closed by inio** 2018-04-23 17:55 UTC
