### ISSUE TITLE
ARCore should be now compatible with S9 but it is not...

### ISSUE THREAD

**Issue by RegisAG** [google-ar/arcore-android-sdk#367] opened 2018-05-09 09:34 UTC
Hi,

I see that the last update of ARCore added many compatible devices. Among them: the S9 and S9+.

But, it seems still impossible to install ARCore on a S9 or S9+.

Is there any reason?

Thanks.

**Comment by inio** [comment] 2018-05-09 14:16
ARCore 1.2 is compatible with the S9 and S9+.  It should reach 100% rollout on the Play Store later this week, and is available for download on our releases page today.

**Comment by inio** [comment] 2018-05-09 14:16
Duplicate of #250

**Closed by inio** 2018-05-09 14:16 UTC

**Comment by hectorC** [comment] 2018-05-09 19:25
Is the system update from Samsung still needed for 1.2? I just tested it and no existing ARCore apps work on my S9. Samsung hasn't released anything yet for my region.

**Comment by RegisAG** [comment] 2018-05-14 07:42
I see that the message saying that the new version of ARCore is progressively released has been removed from this page : https://developers.google.com/ar/discover/supported-devices

But I have still some users telling me that the can't install ARCore on their S9.

Is ARCore really fully released ?

Thanks.

**Comment by inio** [comment] 2018-05-14 19:31
ARCore should be fully rolled out to [all listed supported devices](https://developers.google.com/ar/discover/supported-devices).  If you can get a particular model number (or better yet build fingerprint) please let us know.

Note: ARCore is not supported on Samsung SM-****0 and SM-****8 devices at this time, even those shipping with Play Store such as Hong Kong variants.  We're looking at addressing this (and may be forced into it by #350).
