### ISSUE TITLE
Implementing the Trackable interface

### ISSUE THREAD

**Issue by mahjiang** [google-ar/arcore-android-sdk#211] opened 2018-03-01 16:26 UTC
Is it possible to implement the `Trackable` interface such that a `Frame.hitTest(MotionEvent)` can obtain a `Trackable` of this type? Digging into the source code for `Point` and `Plane` reveals that these classes do not directly implement `Trackable`, but instead extend a `TrackableBase` class which directly references native code.

I would like to be able to select assets that I have placed into the scene using `hitTest`, but right now it looks like I need to manually cast a ray from the `Camera` pose to the `Point` pose in order to detect a collision.

Thanks in advance!

**Comment by inio** [comment] 2018-03-02 00:30
To your question: No, you cannot usefully implement Trackable or subclass TrackableBase except for mocking for unit tests.

To your desire: The HelloAR samples are intentionally minimal.  If you want higher level functionality, such as object picking, we recommend using Unity or Unreal for now.

**Comment by inio** [comment] 2018-03-02 00:30
Duplicate of #52

**Closed by inio** 2018-03-02 00:30 UTC
Labels: feature request, question
