### ISSUE TITLE
Does not work with Camera2 shared camera when a still image capture surface is added

### ISSUE THREAD

**Issue by carloshwa** [google-ar/arcore-android-sdk#1670] opened 2024-09-07 03:18 UTC
### SPECIFIC ISSUE ENCOUNTERED
Using the [Shared Camera sample app](https://github.com/google-ar/arcore-android-sdk/blob/main/samples/shared_camera_java), if I add an additional high quality `ImageReader` to the camera capture session, ARCore behaves incorrectly on different devices. See this code sample:
https://github.com/velos/google-arcore-android-sdk/commit/a156e4c39cc02eebb2f4cd87eea365dc3f1b2433

### VERSIONS USED
- Android Studio: 2024.1.1 Patch 2
- ARCore SDK for Android: 1.45.0
- Device manufacturer, model, and O/S: See below
- Google Play Services for AR (ARCore): See below
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: See below

#### Samsung S10e, Android 12
`1.45.242050493`
`samsung/beyond0qltesq/beyond0q:12/SP1A.210812.016/G970USQU9IXE3:user/release-keys`

`ImageFormat.JPEG`: Works, but with these changes, the Camera2 preview fails to update if `Frame.acquireCameraImage()` was called:
https://github.com/velos/google-arcore-android-sdk/commit/b8c3e09fc06bbe7ce06f9e08b3b580bcf42d1e24
`ImageFormat.YUV_420_888`: Camera fails to initialize

#### Google Pixel 4a, Android 13
`1.45.242050493`
`google/sunfish/sunfish:13/TQ3A.230805.001.S1/10786265:user/release-keys`

`ImageFormat.JPEG`: Works as expected
`ImageFormat.YUV_420_888`: Camera fails to initialize

#### Google Pixel 8, Android 14
`1.45.242050493`
`google/shiba/shiba:14/AP2A.240905.003/12231197:user/release-keys`

`ImageFormat.JPEG`: Camera fails to initialize
`ImageFormat.YUV_420_888`: Works as expected

### STEPS TO REPRODUCE THE ISSUE
1. Run this [sample app](https://github.com/velos/google-arcore-android-sdk/tree/shared_camera_testing/samples/shared_camera_java)
2. Launch app on various devices
3. Observe incorrect behavior

### WORKAROUNDS (IF ANY)
See device-specific behaviors above.

**Comment by carloshwa** [comment] 2024-09-09 17:28
Hi @lferrer Thanks for the explanations. Here are the reported hardware levels, and the list of supported capabilities for each device:
Samsung S10e: supportedHardwareLevel 3 (LEVEL_3): [0, 9, 3, 7, 4, 5, 1, 6, 2]
Pixel 4a: supportedHardwareLevel 1 (FULL): [0, 9, 3, 5, 1, 6, 2]
Pixel 8: supportedHardwareLevel 1 (FULL): [0, 1, 5, 2, 6, 19, 3, 9, 11, 18]

Does the behavior I am seeing make sense based on the hardware levels for each device? Are there specific capabilities I should be looking for in order to know if this functionality should be supported?

**Comment by lferrer** [comment] 2024-09-09 23:59
Thanks for the update @carloshwa!

Since all three devices are at least [FULL](https://developer.android.com/reference/android/hardware/camera2/CameraDevice#full-level-additional-guaranteed-configurations), they should be able to support triple streams. It is unclear to me if the issue is the resolution or the format, but you could try reducing the resolution to see if that helps.

You could try creating a sample app that creates a capture session with a 1920x1080 PRIV surface, a 640x480 YUV surface and your surface of choice, independently of ARCore. I'm confident that you will see a similar behavior than with ARCore. 

Since this seems to be a platform/HW limitation, and not an ARCore bug per se, I'll close this issue. Please feel free to reopen it if your sample app does work so we can take a look at why it does and ARCore does not.

**Closed by lferrer** 2024-09-09 23:59 UTC
Labels: bug

**Comment by carloshwa** [comment] 2024-09-10 00:52
Ah thanks for the additional clues. It turns out, with my changes to the `shared_camera_java` sample app, there ended up being **4** surfaces being used. There were already 3 to begin with: 2 ARCore surfaces and 1 for `cpuImageReader`. It turns out the `cpuImageReader` initialized in the sample app is not actually necessary, and seems to just be there as an example. I removed it, and it is now working as intended on all 3 devices with my capture surface added. Thanks for the help!
