### ISSUE TITLE
ArCore Augmented images removed from scene

### ISSUE THREAD

**Issue by efthymios1991** [google-ar/arcore-android-sdk#647] opened 2018-11-17 17:34 UTC
I am tracking 3 images that i have in my database using `Sceneform` and `Augmenting Images`. When the images are recognized  a video start playing in front of the image with the same dimensions. Everythings works fine but when i move the camera or i remove the image from the scene, the video stays there. Is there any way to track if the image or images are still in the scene so that i can stop and hide the video?

**Comment by Canato** [comment] 2018-11-29 13:14
Maybe you should reference this issue in the Sceneform Issues: https://github.com/google-ar/sceneform-android-sdk

I would suggest to put some pictures and code to help to understand the problem.

**Comment by inio** [comment] 2018-12-01 00:47
Currently Augmented Image detections persist indefinitely at the detected location.  The feature request #519 should help provide a way to resolve this.

**Comment by inio** [comment] 2018-12-01 00:47
Duplicate of #519

**Closed by inio** 2018-12-01 00:47 UTC
