### ISSUE TITLE
Feature Request : Add/Remove Augmented Image from database at Runtime 

### ISSUE THREAD

**Issue by bilelmnasser** [google-ar/arcore-android-sdk#420] opened 2018-06-07 13:13 UTC
hello Everybody  ,
this allow flexibility and enormous option to load images from servers online, application scale will be so big, i am indeed looking forward of this feature to many of my currents applications.
thank you all
@gordonbrander @inio @eitanme @richlowenberg @jsantell

**Comment by inio** [comment] 2018-06-15 19:39
Duplicate of #372

**Closed by inio** 2018-06-15 19:39 UTC
Labels: feature request
