### ISSUE TITLE
Camera feature controls

### ISSUE THREAD

**Issue by maxmaynard** [google-ar/arcore-android-sdk#251] opened 2018-03-20 19:47 UTC
Anyone know a way to access flash control in ARCore? I'd like to be able to turn on the light at will; the asset I own for it runs into a problem transferring control to and from ARCore because of the platform's need to manage the camera, and the control has to be transferred between plugins due to the Android OS. Alternatively if there's a 3rd party way to reassign the ARCore camera I'd consider that too.

Thanks.

**Comment by inio** [comment] 2018-03-20 19:48
Duplicate of #56

**Closed by inio** 2018-03-20 19:48 UTC
Labels: feature request

**Comment by inio** [comment] 2018-03-31 15:56
Duplicate of #153 (had deduped onto wrong canonical bug)
