### ISSUE TITLE
Any plans to support more devices?

### ISSUE THREAD

**Issue by dvperv** [google-ar/arcore-android-sdk#297] opened 2018-04-08 10:35 UTC
Nor my Sony Tablet (premium model), nor my Honor 6A(budget model) are supported. Why are so limited range?

**Comment by inio** [comment] 2018-04-08 17:39
We're working on enabling as many devices as we can.

**Comment by inio** [comment] 2018-04-08 17:39
Duplicate of #89

**Closed by inio** 2018-04-08 17:39 UTC
