### ISSUE TITLE
Hello AR C and Java apps crash in emulator (x86 API 27 version 5) 

### ISSUE THREAD

**Issue by oa2013** [google-ar/arcore-android-sdk#294] opened 2018-04-06 15:15 UTC
Hi @avirodov, I've setup the emulator as specified in the guide and it's crashing in both C and Java versions of the Hello Application.

Screenshots and emulator specs below:

![activity](https://user-images.githubusercontent.com/5304739/38429160-a3ae2f84-398b-11e8-89a3-32b9c0c6a4d0.PNG)

![error](https://user-images.githubusercontent.com/5304739/38429069-62552d62-398b-11e8-8257-556d4e040ed3.PNG)

Name: Pixel_API_27

CPU/ABI: Google APIs Intel Atom (x86)

Path: C:\Users\agafonovao\.android\avd\Pixel_API_27.avd

Target: google_apis [Google APIs] (API level 27)

Skin: pixel_silver

SD Card: 512M

hw.dPad: no

hw.lcd.height: 1920

runtime.network.speed: full

hw.accelerometer: yes

hw.device.name: pixel

vm.heapSize: 228

skin.dynamic: yes

hw.device.manufacturer: Google

hw.lcd.width: 1080

hw.gps: yes

hw.initialOrientation: Portrait

image.androidVersion.api: 27

hw.audioInput: yes

image.sysdir.1: system-images\android-27\google_apis\x86\

tag.id: google_apis

showDeviceFrame: yes

hw.camera.back: virtualscene

hw.mainKeys: no

AvdId: Pixel_API_27

hw.camera.front: emulated

hw.lcd.density: 420

avd.ini.displayname: Pixel API 27

hw.arc: false

hw.gpu.mode: auto

hw.device.hash2: MD5:bc5032b2a871da511332401af3ac6bb0

hw.ramSize: 1536

hw.trackBall: no

PlayStore.enabled: false

fastboot.forceColdBoot: no

hw.battery: yes

hw.cpu.ncore: 4

hw.sdCard: yes

tag.display: Google APIs

runtime.network.latency: none

hw.keyboard: yes

hw.sensors.proximity: yes

disk.dataPartition.size: 2000M

hw.sensors.orientation: yes

avd.ini.encoding: UTF-8

hw.gpu.enabled: yes

**Comment by inio** [comment] 2018-04-06 19:37
Looked a little deeper, this looks like a dup of #274 .  For now for the emulator you'll need to use the 1.0 SDK.

**Comment by inio** [comment] 2018-04-06 19:37
Duplicate of #274

**Closed by inio** 2018-04-06 19:37 UTC
Labels: emulator
