### ISSUE TITLE
Object not stable without surface detection

### ISSUE THREAD

**Issue by rramprasad** [google-ar/arcore-android-sdk#508] opened 2018-08-01 06:53 UTC
I am Placing 3D object in 0,0,-1 position as soon as launch ARScreen. It placed object stable but sometimes it moves around the room. We are placing the object in a static point based on device origin point. Then why it moves. Also I didn’t shake mobile, so there is no chance this issue occurs because of motion. Also no white background or similar patterns.Also I didn’t update Anchor on every update, just added one time only. Also I am using a Pixel 2 so there is no device capability issue.

Is it Anchor not stable without surface detection? Is it any workaround to fix this issue?

Is it stable only use Unity instead of Sceneform? Is it any fix we can expect from ARCore team?

I am trying to place 3D object stable for long time.But not able to anchor in stable place.Any technical limitations are not accepted by client as it is works good on ARKit.

Please provide you suggestions, best practices to place object stable without surface detection.

**Comment by dakshsrivastava** [comment] 2018-08-03 12:18
Hey Ram. I'm trying something similar to [JustAline](https://justaline.withgoogle.com/). I believe that's something similar to what you're trying to achieve. I find that my shapes mid-air do not roam around the room if you let ARCore detect a surface first. In a nutshell, let ARCore get a sense of the environment a little bit first before placing any object anywhere. This is something what Google also suggests in one of their development pages. Sorry, unable to find a link to that.

**Comment by fredsa** [comment] 2018-08-07 17:31
Hi @rramprasad,

Placing objects at session start is inherently challenging. You will indeed have the best results if you instead wait for plane detection and then anchor your objects to a detected plane.


I hope some additional context will help provide an understanding of why this is so:

In order to [build an understanding of the environment and track the device's movement through space](https://developers.google.com/ar/discover/concepts), ARCore uses a method called _Visual Inertial Odometry_:

- Images from the camera sensor (the "V" in "VIO") are used to track detected feature points over time. This helps ARCore build an internal 3D model of the environment, and allows ARCore to detect planes after some movement.
- When the devices is moving quickly, the camera image temporarily becomes blurry. During this time, ARCore temporarily uses the IMU sensor data (the "I" in "VIO") to estimate relative movement. Once the device stops moving, a more accurate pose (position + rotation) is again determined using the camera sensor.

In other words, you can think of the camera as the primary sensor for pose determination purposes. The IMU is really only used when the camera image is briefly too blurry. As soon as the blur disappears, camera based tracking resumes. It's the combination of these two methods (together called "VIO") that makes for a seamless experience and allows the phone to both track very accurately (using the camera) and continue to track during rapid movement (using the IMU).

—

What this means for you is that when your AR session starts, ARCore will not yet have been able to build a visual (camera based) 3D model of the world. It needs a little bit of time (and device movement) to start building that 3D model.

When the AR session starts, ARCore has to rely much more on IMU data to determine relative movement of the device. This can result is object that's placed at session start to feel less anchored to the world than objects that are placed later.

Also, as you suggested, objects that are anchored to a detected plane will feel the most stable and appear much more anchored to the world.


Hope that helps

**Comment by rramprasad** [comment] 2018-08-08 07:13
Hi @fredsa Great explanation.Thank you

**Comment by smurfhunter** [comment] 2018-10-13 19:51
@rramprasad , did you ever get this working? If so, the issue should be closed.

**Comment by inio** [comment] 2018-10-22 21:08
Duplicate of #528

**Closed by inio** 2018-10-22 21:08 UTC
Labels: feature request, question

**Comment by zainabk670** [comment] 2018-12-17 10:52
Hi
I'm also placing a 3d object on a detected plane but when I build in mobile it places in mid of the air. it working properly on unity editor but the problem when build in mobile.
                                                                please help if anyone have solution for this issue.

**Comment by zainabk670** [comment] 2018-12-17 10:54
sorry forget to mention I'm using arcore SDK 1.4
