### ISSUE TITLE
Expose more camera functionality & properties

### ISSUE THREAD

**Issue by eddielong** [google-ar/arcore-android-sdk#145] opened 2018-01-25 22:39 UTC
I would like to be able to access various properties of the camera during ARCore:

1) The orientation of the sensor relative to the screen. This isn't necessarily needed as I'm reading back the camera frame from the GPU but if/when we have proper CPU callbacks for the camera frames it will be needed then.
2) Auto-focus (the camera image is really blurry when viewing items close up which is my particular use-case to work alongside ARCore)
3) Torch/flashlight control. Both checking for presence and toggling.
4) FPS control

On a separate note, having to read the camera frames back from the GPU on the render thread is a bit of a pain. Normally I would have a separate camera thread and do certain work on there such as format conversion, not blocking the render thread.

**Comment by inio** [comment] 2018-01-31 17:17
Duplicate of #153

**Closed** 2018-01-31 17:19 UTC
Labels: feature request
