### ISSUE TITLE
Exception running helloAR_java on OnePlus 5 	ONEPLUS A5000

### ISSUE THREAD

**Issue by handymoby** [google-ar/arcore-android-sdk#186] opened 2018-02-23 23:55 UTC
Hello, I built and try to run the helloAR_java project on my oneplus 5 
ONEPLUS A5000(a supported device), but it displayed a "device unsupported" message. I looked into the code and find the exception with adb. Please help!

02-23 15:51:23.029 14916 14928 W native  : helpers.cc:890 Property calibration_cad is not defined.
02-23 15:51:23.030 14916 14928 E native  : device_profile_database_helpers.cc:134 Device profile for OnePlus/OnePlus5/OnePlus5:8.0.0/OPR6.170623.013/01120216:user/release-keys does not exist in /data/user/0/com.google.ar.core/files/device_profile_database
02-23 15:51:23.030 14916 14928 E native  : calibration_jni.cc:74 No device profile available for build fingerprint OnePlus/OnePlus5/OnePlus5:8.0.0/OPR6.170623.013/01120216:user/release-keys
02-23 15:51:23.032 15976 15976 E native  : session_create_implementation.cc:190 Device is not supported.
02-23 15:51:23.032 15976 15976 E native  : session_create_implementation.cc:486 Failed to create calibration provider
02-23 15:51:23.032 15976 15976 W native  : session_create_implementation.cc:487 ArSession_createImplementation returning ArStatusErrorSpace::AR_UNAVAILABLE_DEVICE_NOT_COMPATIBLE: .
02-23 15:51:23.053 15976 15976 E HelloArActivity: Exception creating session
02-23 15:51:23.053 15976 15976 E HelloArActivity: com.google.ar.core.exceptions.UnavailableDeviceNotCompatibleException
02-23 15:51:23.053 15976 15976 E HelloArActivity: 	at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:361)
02-23 15:51:23.053 15976 15976 E HelloArActivity: 	at com.google.ar.core.Session.nativeCreateSession(Native Method)
02-23 15:51:23.053 15976 15976 E HelloArActivity: 	at com.google.ar.core.Session.<init>(Session.java:100)
02-23 15:51:23.053 15976 15976 E HelloArActivity: 	at com.google.ar.core.examples.java.helloar.HelloArActivity.onResume(HelloArActivity.java:155)

**Comment by alchemz** [comment] 2018-02-24 00:11
I only have a OnePlus 5T(A5010), and found it is incompatible to download ARCore 1.0 from the play store.

Could you check to see you could down it https://play.google.com/store/apps/details?id=com.google.ar.core&rdid=com.google.ar.core ?

**Comment by handymoby** [comment] 2018-02-24 00:25
BTW, Yes, I was able to download ARCore 1.0 from google play

**Comment by alchemz** [comment] 2018-02-24 00:27
@handymoby Thx, and what's wrong with OnePlus 5T?

**Comment by Crashthatch** [comment] 2018-02-25 15:39
It seems several devices are hitting this bug. Log from my Samsung S8 SM-G950F:

```
02-25 14:26:45.375  9326  9342 W native  : helpers.cc:913 Defaulting to persistent calibration file.
02-25 14:26:45.375  9326  9342 W native  : helpers.cc:890 Property calibration_cad is not defined.
02-25 14:26:45.376  9326  9342 I native  : device_provider.cc:715 Identified device type: kDreamltexxDreamlte
02-25 14:26:45.382  9326  9342 E native  : device_profile_database_helpers.cc:134 Device profile for samsung/dreamltexx/dreamlte:8.0.0/R16NW/G950FXXU1CRB7:user/release-keys does not exist in /data/use
r/0/com.google.ar.core/files/device_profile_database
02-25 14:26:45.382  9326  9342 E native  : calibration_jni.cc:74 No device profile available for build fingerprint samsung/dreamltexx/dreamlte:8.0.0/R16NW/G950FXXU1CRB7:user/release-keys
02-25 14:26:45.386  9229  9254 E native  : session_create_implementation.cc:190 Device is not supported.
02-25 14:26:45.386  9229  9254 E native  : session_create_implementation.cc:486 Failed to create calibration provider
02-25 14:26:45.386  9229  9254 W native  : session_create_implementation.cc:487 ArSession_createImplementation returning ArStatusErrorSpace::AR_UNAVAILABLE_DEVICE_NOT_COMPATIBLE: .
02-25 14:26:45.386  9229  9254 E ArPresto: ArPresto::ArCore session creation failed.
02-25 14:26:45.386  9229  9254 E native  : session_c_api.cc:183 ArConfig_setUpdateMode: session was passed NULL.
02-25 14:26:45.386  9229  9254 E native  : session_c_api.cc:166 ArConfig_setPlaneFindingMode: session was passed NULL.
02-25 14:26:45.386  9229  9254 E native  : session_c_api.cc:148 ArConfig_setLightEstimationMode: session was passed NULL.
02-25 14:26:45.387  9229  9254 E native  : session_c_api.cc:207 ArSession_configure: session was passed NULL.
```

FWIW, I *think* I saw this message in logs when using developer-preview-2 on the same device, but it didn't actually stop it working.

For me:
`adb shell getprop ro.build.fingerprint`

`samsung/dreamltexx/dreamlte:8.0.0/R16NW/G950FXXU1CRB7:user/release-keys`

I believe all of these are duplicates (same bug, different phones), and these build.fingerprints need adding to the supported device profiles by google in a bugfix release of ARCore?:
* Asus Zenphone: https://github.com/google-ar/arcore-android-sdk/issues/183 (Fixed by @haroldmthyng with a new release!)
ro.build.fingerprint: asus/VZW_ASUS_A002A/ASUS_A002_1:7.0/NRD90M/VZW_ASUS_A002A-V3.7.8-20170922:user/release-keys
* OnePlus 5 ONEPLUS A5000: (this thread)
build fingerprint: OnePlus/OnePlus5/OnePlus5:8.0.0/OPR6.170623.013/01120216:user/release-keys
* Samsung S8 SM-G950F: https://github.com/google-ar/arcore-android-sdk/issues/187
ro.build.fingerprint: samsung/dreamltexx/dreamlte:8.0.0/R16NW/G950FXXU1CRB7:user/release-keys
* huawei P9(Android7.0): https://github.com/google-ar/arcore-android-sdk/issues/189
* Samsung Galaxy S8+: https://github.com/google-ar/arcore-android-sdk/issues/191
ro.build.fingerprint: samsung/dream2ltexx/dream2lte:8.0.0/OPR6/G955FXXU1ZQL8:user/release-keys

Samsung Galaxy S8 & OnePlus5 also reporting the same problem in this thread: https://forum.unity.com/threads/arcore-1-0-samsung-galaxy-s8-no-longer-working.519024/

@alchemz The 5T A5010 is NOT listed under supported devices, and you can't download from google play (whereas the other phones can), so I think that's a different issue.

**Comment by alchemz** [comment] 2018-02-25 18:11
@Crashthatch Thanks for the reply, OnePlus 5T is a new release/upgrade of the 5 series, if OnePlus 5 is on the supported list, how could 5T not be on the list? Do you know who should I contact with about this issue?

**Comment by Crashthatch** [comment] 2018-02-25 18:22
No. I am not affiliated with google. Please keep that separate issue in your own thread, #185.

**Comment by inio** [comment] 2018-02-26 17:38
@Crashthatch thank you so much for the work aggregating those reports!

**Comment by inio** [comment] 2018-02-26 19:19
Duplicate of #198

**Closed** 2018-02-26 19:21 UTC
Labels: bug, device support, fixed in upcoming release
