### ISSUE TITLE
[Bug] arsession_create internal crash 

### ISSUE THREAD

**Issue by wuzeqin** [google-ar/arcore-android-sdk#579] opened 2018-09-26 11:00 UTC
![qq20180926-185244](https://user-images.githubusercontent.com/9404871/46075860-65c29c80-c1be-11e8-8006-83fe3ea95d84.png)
Second time createArSession crash in my Sumsung 9, I have no idea.

**Comment by wuzeqin** [comment] 2018-09-27 01:41
specific crash log in demo
 
![_07c4f5e9-4bec-410d-8f55-38c6efdefbc0](https://user-images.githubusercontent.com/9404871/46118505-7106de00-c239-11e8-9862-a962ee94a75c.png)

**Comment by inio** [comment] 2018-09-27 16:37
Duplicate of #563

**Closed by inio** 2018-09-27 16:37 UTC
