### ISSUE TITLE
ARCore Developer Preview 2

### ISSUE THREAD

**Issue by TheMachineHere** [google-ar/arcore-android-sdk#88] opened 2017-12-15 18:37 UTC
Some Great news finally "https://blog.google/products/google-vr/arcore-developer-preview-2/"

> In the coming months, we’ll launch ARCore v1.0, with support for over 100 million devices

What devices can we expect?

**Comment by inio** [comment] 2017-12-15 22:39
ARCore Developer Preview 2 is only officially supported on the Pixel phones and most models of the Samsung S8.  We're hard at work to support 100M devices with the launch of ARCore 1.0 (coming out of preview) in the coming months.  We can't yet commit to support of any devices beyond those listed above.

**Comment by inio** [comment] 2017-12-15 22:39
Duplicate of #89

**Closed by inio** 2017-12-15 22:39 UTC

**Comment by Thaina** [comment] 2017-12-17 14:06
@inio Does that means ARCore 1.0 will support more device? Or not?

**Comment by inio** [comment] 2017-12-18 18:25
Lots.

**Comment by Thaina** [comment] 2017-12-19 02:22
@inio Does it will cover the devices I ask for in another thread ? 

Specifically
motorola Nexus 6 (I was currently owned)
ZTE Blade Z Max (Next one I would get)
